### PR TITLE
style: reformat to the Black default line length of 88

### PR DESCRIPTION
**Pull request by cpcloud**
This PR changes the line length of the codebase to the black default of 88

### CODE REVIEW

**Comment by kszucs** [comment]
Strangely github doesn't crosslink discussions here. See the relevant thread at https://github.com/ibis-project/ibis/discussions/4515

**Comment by jcrist** [comment]
Based on the discussion in #4515, it looks like a line length of 88 is preferred, matching what's done here. Is there anything left to do here?

**Comment by kszucs** [comment]
We need to rerun the formatter on the current main branch, also we should add the created formatting commit to `.git-blame-ignore-revs`

**Comment by cpcloud** [comment]
@kszucs Are you opposed to this change?

**Comment by kszucs** [comment]
> @kszucs Are you opposed to this change?

Nope.

**Comment by cpcloud** [comment]
@kszucs Shall we merge? I'll add the commit once it lands upstream.

**Review by kszucs — APPROVED** [review]

**Pull request merged**
