### PR TITLE
Added pre commit hook

### PR DESCRIPTION
**Pull request by xmnlab**

### CODE REVIEW

**Comment by xmnlab** [comment]
@cpcloud @kszucs I think it is done for review :)

**Comment by xmnlab** [comment]
@cpcloud @kszucs any feedback about this PR?

**Comment by kszucs** [comment]
@xmnlab it looks good to me.
Could You please mention it in the developer [documentation](https://github.com/ibis-project/ibis/blob/master/docs/source/developer.rst)?

@cpcloud should We merge [developer.rst](https://github.com/ibis-project/ibis/blob/master/docs/source/developer.rst) and [contributing.rst](https://github.com/ibis-project/ibis/blob/master/docs/source/contributing.rst)?

**Comment by xmnlab** [comment]
@kszucs sure! I will do it now. thanks!

**Comment by xmnlab** [comment]
@kszucs it is done for a new review!

**Pull request closed without merging**
