### PR TITLE
DOC: Restructuring the documentation of the backends

### PR DESCRIPTION
**Pull request by datapythonista**
xref #2281

Creating a better structure for the documentation of backends. Once this PR is merged, there will be a top-level `Backends` section in the docs, with one page for each existing backend. Some of the backends already had a page, and most had a section in the `Getting started` page. This creates a uniform structure for all the backends.

This PR doesn't change any content, it just moves the texts. The only exception is the `Spark` backend, which was missing a quickstart section, and is created here.

I'll follow up with improvements to the pages, but this first restructuring makes it easier to find the documentation for a specific backend, and also to keep things consistent and expand the content.

### CODE REVIEW

**Comment by jreback** [comment]
thanks @datapythonista

**Comment by westurner** [comment]
Does this break existing links to part of the value proposition of Ibis?

**Comment by datapythonista** [comment]
@westurner are you referring to the `Getting started` page? That page disappeared in this PR. But existing links were probably broken before this PR. The docs were quite difficult to navigate, and there is a major refactoring going on, including the creation of the website, using ibis-project.org instead of docs.ibis-project.org...

If there is any link in particular let me know (probably better to open an issue and tag me). But I'm not aiming to keep old links working in general.

**Comment by westurner** [comment]
E.g. #2281 (and other existing extra-docs references) link to user_guide/backends/ : https://docs.ibis-project.org/docs/user_guide/backends/bigquery.html

Even if there was a tool for creating a centralized map of page-level or #fragment-level JS redirects with Sphinx (that added appropriate sitemap.xml support), I'm not sure it's that big of a deal. But having versioned links like RTD would be helpful for that reason as well (see: #2290)

**Comment by datapythonista** [comment]
Not sure if I fully understand you. But I see two different topics that I'm not sure if are being mixed.

We're currently at the end of a major refactor of the docs, where we probably broke every external link to Ibis. Because of the domain change, adding a new website and moving the docs to `/docs/` and most pages being moved (I created top sections `user guide`... and move all pages inside). This has been a one-off, and trying to keep previous external links wasn't doable. Things will be stable from now on.

Having the docs of every released version of Ibis would surely be nice. I don't see it happening in the short term, because of lack of resources. There are lots of things to do, and very few contributors. Just couple of months ago, the CI was broken for several months because of lack of resources. So, I personally don't think we can be very ambitious with javascript redirects, sitemaps, versioned docs... I think there are other priorities. Like making the docs useful for the users, improve the CI that wastes a lot of our time, and keep reviewing and merging PRs. But those are good ideas, feel free to open issues, and hopefully at some point they can be implemented.

**Pull request merged**
