### PR TITLE
feat(api): add `to_geo` methods for writing geospatial output

### LINKED ISSUE #10296: feat: add to_geo() method
### Describe the solution you'd like

duckdb spatial extension provides the ability to both read a wide variety of spatial formats (geojson, flatgeobuf, etc) and write data out into these formats ([duckdb docs](https://duckdb.org/docs/extensions/spatial/gdal#gdal-based-copy-function)).  

ibis gives us `read_geo()` to read all those formats, but no `to_geo()` method to write back out.  It would be awesome to have a `to_geo()` method!    

Being able to write out to these formats is a great way to make sure ibis geospatial workflows can easily interoperate in workflows with other spatial software or with other users that require these formats.  

### What version of ibis are you running?

9.5.0

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by cpcloud**
Adds an experimental `to_geo` method to the duckdb backend.

Closes #10296.

### CODE REVIEW

**Review by gforsyth — COMMENTED** [review]
That windows exception is going to be hilarious to track down.  I wonder which format is causing it to barf?

Overall I think this looks good -- should probably have a docstring with a link to the DuckDB geospatial page that lists all of the output options (and their names)

**Comment by cpcloud** [comment]
DuckDB 1.1.2 was just released today (and I've merged a PR to update our lockfile to test against it). Let's see if that helps windows .

**Comment by cpcloud** [comment]
Well, it turns out that it's the WAsP format, and I don't know why it crashes, so I just `skipif`'d it.

**Review by gforsyth — APPROVED** [review]
:shipit:

**Pull request merged**
