### PR TITLE
Escape column names and types in png_repr.

### LINKED ISSUE #2022: BUG: Graphviz repr should escape HTML
The current notebook graphviz repr breaks when there are unintentional HTML characters in column names or types. An example of this is array types, which includes angle brackets, so a type like `array<string>` fails to render because it produces invalid HTML.

The fix is fairly straightforward: names and columns should be escaped. I should be able to submit a PR.

### PR DESCRIPTION
**Pull request by ian-r-rose**
Fixes #2022

### CODE REVIEW

**Comment by ian-r-rose** [comment]
I don't understand the docs error, but it doesn't look related to me.

**Comment by xmnlab** [comment]
@ian-r-rose it seems it is a problem with a sphinx https://github.com/ibis-project/ibis/pull/2024#issuecomment-550143737

**Comment by ian-r-rose** [comment]
Rebased

**Comment by ian-r-rose** [comment]
green

**Pull request merged**
