### PR TITLE
Clean conda recipe

### LINKED ISSUE #2489: Conda solver taking too long
xref: https://github.com/ibis-project/ibis/pull/2476#issuecomment-714429790

Looks like the conda package build is taking too long (2 hours in some cases).

That build is installing all the dependencies of all the backends, which seem to be causing the problem. `pymapd` has been in the past the main source of conda solving time, so #2356 (moving omnisci to a separate repo should help). Also, for that particular build, #2448 (have independent conda packages for each backend) should fix the problem.

As a more immediate solution, #2486 (bumping `pymapd` version) seems to be decreasing the solver time significantly.

### PR DESCRIPTION
**Pull request by matthewmturner**
Closes #2489 

@jreback @datapythonista 

Im starting the PR - let me know how you want proceed.

### CODE REVIEW

**Comment by jreback** [comment]
do we still need this job: https://github.com/ibis-project/ibis/pull/2515/checks?check_run_id=1369342542

as have (LinuxTest py37_impala_kudu_clickhouse already

**Comment by matthewmturner** [comment]
@jreback is that question for me or @datapythonista ?  it sounds reasonable to me, especially since were currently skipping.  was there anything that job was meant to test (even though not running currently) that the LinuxTest jobs werent able to?

**Comment by jreback** [comment]
haha both

is there any reason we need both jobs?

i guess i i can dig in and see can remove the currently disabled one - new issue / PR

**Comment by datapythonista** [comment]
The Impala build in GitHub actions is disabled because the docker container still doesn't work. I'm working on that in #2480. I'll remove the azure jobs, that are quite tricky, and enable the Impala build in actions, once it's working.

**Comment by jreback** [comment]
> The Impala build in GitHub actions is disabled because the docker container still doesn't work. I'm working on that in #2480. I'll remove the azure jobs, that are quite tricky, and enable the Impala build in actions, once it's working.

ok great.

**Comment by datapythonista** [comment]
Regarding this PR, I don't think we want to clean up the build, but split the Ibis core package from the backend packages, as proposed in #2448.

I think we should release things as previously now, and after the release, implement the entrypoints, move backends to other repos when it makes sense, and have the packaging separate.

**Comment by jreback** [comment]
not against the entry points idea but making separate conda packages is massively increasing complexity 

why is not fixing the builds first important? we can't keep having builds that time out because of 60 solving - that's ridiculous 

that said splitting out the prime offender omnisci is ok by me as a test

**Comment by datapythonista** [comment]
> why is not fixing the builds first important? we can't keep having builds that time out because of 60 solving - that's ridiculous
> 
> that said splitting out the prime offender omnisci is ok by me as a test

Making the CI reliable is a top priority to me. But it's not trivial, been trying few things, but need to have more ideas on what's wrong. If I knew how to fix it, it'd already be fixed. :) Feel free to have a look if you have ideas on how to fix it.

**Comment by datapythonista** [comment]
As per discussion in #2448, more than cleaning the recipe, we will split it by backend. This PR will be conflicting with the changes in the recipe in https://github.com/conda-forge/ibis-framework-feedstock/pull/51. So, I think it's better we close this, and start over with the splitting after the release. Let me know if you disagree @matthewmturner, and I'll reopen.

**Comment by matthewmturner** [comment]
> 
> 
> As per discussion in #2448, more than cleaning the recipe, we will split it by backend. This PR will be conflicting with the changes in the recipe in [conda-forge/ibis-framework-feedstock#51](https://github.com/conda-forge/ibis-framework-feedstock/pull/51). So, I think it's better we close this, and start over with the splitting after the release. Let me know if you disagree @matthewmturner, and I'll reopen.

Good for me.

**Pull request closed without merging**
