### PR TITLE
ci(cloud-run): add label checkout and remove label after used

### PR DESCRIPTION
**Pull request by gforsyth**
docs only change to test ci labels

### CODE REVIEW

**Comment by gforsyth** [comment]
YESSSSSSSSS

**Comment by cpcloud** [comment]
We'll still need to verify that the correct commit is being checked out, but we can do that on one of the other PRs.

**Comment by gforsyth** [comment]
oh right -- well, I'll reopen this one

**Comment by gforsyth** [comment]
I'm going to merge this and reopen another docs change PR

**Pull request merged**
