### PR TITLE
feat(snowflake): add support for alias in snowflake

### PR DESCRIPTION
**Pull request by thegreymatter**
add support for alias() in snowflake.

### CODE REVIEW

**Review by cpcloud — APPROVED** [review]
Fixed a couple xfailing snowflake tests that now start to pass after this PR!

LGTM!

**Comment by cpcloud** [comment]
@thegreymatter Just out of curiosity is there any functionality missing from the snowflake backend that we could add to avoid you needing to reach for `.sql`/`.alias`?

These APIs are meant as escape hatches for when ibis is missing functionality and as entry points into ibis when you're saddled with a large amount of existing SQL, and I'm wondering if you're hitting the former case.

**Comment by thegreymatter** [comment]
> @thegreymatter Just out of curiosity is there any functionality missing from the snowflake backend that we could add to avoid you needing to reach for `.sql`/`.alias`?
> 
> These APIs are meant as escape hatches for when ibis is missing functionality and as entry points into ibis when you're saddled with a large amount of existing SQL, and I'm wondering if you're hitting the former case.

@cpcloud there are few reasons for us to use this capability. 
+ making complex queries simpler to debug and analyze in case of error or weird behavior (basically a cheap CTE alternative) 
+ ability to bring in already existing queries and code while we do the transition, i.e. sort of backward compatibility. 
+ few capabilities we use SQL  - PIVOT, SAMPLE, TABLESAMPLE, MERGE (i.e. upserts), APPROX_PERCENTILE (and  its family of functions)

**Comment by cpcloud** [comment]
@thegreymatter Awesome, thanks for your reply. This is all very useful information for us.

Couple of thoughts:

> @cpcloud there are few reasons for us to use this capability.
> 
> * making complex queries simpler to debug and analyze in case of error or weird behavior (basically a cheap CTE alternative)

Nice. We would like to improve the error reporting in ibis overall. It sounds like there's maybe an area of "successfully compiled but failed-to-run SQL queries" that we can focus on as part of that effort.

> * ability to bring in already existing queries and code while we do the transition, i.e. sort of backward compatibility.

Sweet, this is definitely one of major use cases for `.sql` :)

> * few capabilities we use SQL  - PIVOT, SAMPLE, TABLESAMPLE, MERGE (i.e. upserts), APPROX_PERCENTILE (and  its family of functions)

Some of these are 100% candidates for inclusion into core ibis:

- `PIVOT`, definitely
- `SAMPLE`, definitely
- `MERGE`, not sure, but maybe. We'd have to look at how to roll this into the expression API if that makes sense.
- `APPROX_PERCENTILE`, we do have `quantile` but no explicit `approx_quantile`, definitely a candidate for a new API. The state accumulation/estimation APIs may also be eligible but we'd have to look into it more.

**Pull request merged**
