### PR TITLE
test(datatypes): update test to test double quotes

### PR DESCRIPTION
**Pull request by deepyaman**
## Description of changes

Minor issue I found while looking at examples of string specification for datatypes.

### CODE REVIEW

**Review by cpcloud — DISMISSED** [review]
Thanks!

**Comment by cpcloud** [comment]
@deepyaman This should actually test both single and double quotes, instead of only testing one variant.

**Comment by deepyaman** [comment]
> @deepyaman This should actually test both single and double quotes, instead of only testing one variant.

@cpcloud There's also an existing single quote test just above.  I can parameterize it? Thought about it,  but just made the most minimal fix initially.

**Comment by cpcloud** [comment]
Ah, ok. Then this is fine as is!

**Review by cpcloud — APPROVED** [review]

**Pull request merged**
