### PR TITLE
CI: Removing backends from docs build to fix disk space problem

### PR DESCRIPTION
**Pull request by datapythonista**

### CODE REVIEW

**Comment by datapythonista** [comment]
@jreback this fixes the disk space error in the docs build, by using only the impala and postgres backends, and discarding the rest. I need to reintroduce the `pymapd` dependency. It makes the resolution of the conda environment significantly slower, but the docs won't work without it, unless we remove all the omnisci documentation.

Once this is merged, there are still two pending errors to make the CI green:
- The disk space error in the Linux tests. I discussed with @xmnlab and the best solution (at least for now) is probably the one implemented in #2194. There are still few broken tests there, including the doctests, that I can't easily ignore in the build where their backend is not tested.
- The `LinuxBuildConda` build. From what I understood from @xmnlab the problem is that conda build is using Python 3.8, and in the recipe there are dependencies that are not compatible with 3.8. He implemented a workaround in #2195, which uses this feedstock branch: https://github.com/conda-forge/ibis-framework-feedstock/pull/41

**Comment by jreback** [comment]
@datapythonista does this need to be rebased before merge?

**Comment by datapythonista** [comment]
Should be all right, nothing had been merged since this was opened.

**Comment by jreback** [comment]
great. want to get us to a green build.

**Comment by datapythonista** [comment]
Sure, I'll try to finish #2194. There are couple of errors I don't understand there, but hopefully can leave those builds green soon.

What's your view on the `LinuxBuildConda` problem (conda building with Python 3.8, but some dependencies failing on that version)?

**Pull request merged**
