### PR TITLE
fix: uint upper bounds

### PR DESCRIPTION
**Pull request by NickCrews**
followup to #7332. A bug was sneaking through before :)

### CODE REVIEW

**Review by gforsyth — COMMENTED** [review]
Thanks for the follow-up fix, @NickCrews !  Guess that'll show me to ignore explicit bounds.

I think the fix is causing the test failure in the implicit casting checks -- I would just remove or comment out the `(dt.uint64, dt.int64),` case for now and we can take care of that when we fix up the implicit vs. explicit casting stuff.

**Comment by NickCrews** [comment]
Sorry if that snarky ":)" came out harsh! I didn't mean for that to be a dig at all.

**Comment by gforsyth** [comment]
> Sorry if that snarky ":)" came out harsh! I didn't mean for that to be a dig at all.

not at all!

**Comment by cpcloud** [comment]
This LGTM!

I removed the castable string changes, since they don't seem necessary to address the issue here. Those can be done in a follow-up but I also am -0.5 on the idea, `castable` isn't a public API, and we should avoid input transformation in internal APIs as much as we can, it makes the code harder to reason about.

**Review by cpcloud — APPROVED** [review]

**Pull request merged**
