### PR TITLE
Updated MapD server-CI

### PR DESCRIPTION
**Pull request by xmnlab**
Updated MapD Server/CI

### CODE REVIEW

**Comment by cpcloud** [comment]
@xmnlab Can you rebase to pick up the azure pipelines change?

**Comment by xmnlab** [comment]
@cpcloud sure! done! :+1:

**Comment by xmnlab** [comment]
@cpcloud it seems there is some error with azure conda upload ... any idea how to deal with this problem?

**Comment by cpcloud** [comment]
@xmnlab Working on it over here: https://github.com/ibis-project/ibis/pull/1642

**Comment by cpcloud** [comment]
@xmnlab Can you rebase again?

**Comment by xmnlab** [comment]
@cpcloud sure! done! thanks!

**Comment by xmnlab** [comment]
green :)

**Comment by cpcloud** [comment]
Thanks @xm

**Pull request closed without merging**
