### PR TITLE
test(backends): strict validate exceptions in test_string

### PR DESCRIPTION
**Pull request by krzysztof-kwitt**

### CODE REVIEW

**Comment by krzysztof-kwitt** [comment]
I testing cloud backends now.

**Comment by krzysztof-kwitt** [comment]
'''
$ pytest -m 'snowflake or bigquery' ibis/backends/tests/test_string.py --numprocesses 6 --dist=loadgroup
========================================================================================== test session starts ===========================================================================================
platform darwin -- Python 3.10.7, pytest-7.2.1, pluggy-1.0.0
Using --randomly-seed=1973097733
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /ibis/ibis, configfile: pyproject.toml
plugins: snapshot-0.9.0, xdist-3.1.0, mock-3.10.0, clarity-1.0.1, randomly-3.12.0, profiling-1.7.0, cov-4.0.0, repeat-0.9.1, benchmark-4.0.0, hypothesis-6.65.2
gw0 [134] / gw1 [134] / gw2 [134] / gw3 [134] / gw4 [134] / gw5 [134]
x....x.xx..............x........x.....x.x...x.x..........x........x...........x.......................x..xxx..........................                                                             [100%]
=============================================================================== 117 passed, 17 xfailed in 73.23s (0:01:13) ===============================================================================

'''

**Comment by cpcloud** [comment]
@krzysztof-kwitt This LGTM, is it ready for merge?

**Comment by krzysztof-kwitt** [comment]
Yes. I tested it again on the cloud backend, CI is green too so it's ready for review.
```
$ pytest -m 'bigquery or snowflake' ibis/backends/tests/test_string.py --numprocesses auto --dist=loadgroup
========================================================================================== test session starts ===========================================================================================
platform darwin -- Python 3.10.7, pytest-7.2.1, pluggy-1.0.0
Using --randomly-seed=224880308
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /ibis/ibis, configfile: pyproject.toml
plugins: snapshot-0.9.0, xdist-3.1.0, mock-3.10.0, clarity-1.0.1, randomly-3.12.0, profiling-1.7.0, cov-4.0.0, repeat-0.9.1, benchmark-4.0.0, hypothesis-6.65.2
gw0 [134] / gw1 [134] / gw2 [134] / gw3 [134]
............xxx..xx.xxx...................x...............xxx..........x...........................x................x..x....x.........                                                             [100%]
=============================================================================== 117 passed, 17 xfailed in 96.90s (0:01:36) ===============================================================================

```

**Review by cpcloud — APPROVED** [review]
LGTM!

**Pull request merged**
