### PR TITLE
ENH: add find_nodes to lineage

### PR DESCRIPTION
**Pull request by toryhaavik**

### CODE REVIEW

**Comment by toryhaavik** [comment]
@cpcloud i can see that circleci pipelines are succeeding from the circleci website, what do i need to do to get it updating here?

**Comment by cpcloud** [comment]
@toryhaavik Can you rebase when you get a chance?

**Comment by cpcloud** [comment]
@kszucs I would also like to get this one in before release as well

**Comment by toryhaavik** [comment]
@cpcloud done.

**Comment by cpcloud** [comment]
Sweet. Merging.

**Pull request closed without merging**
