### PR TITLE
Pin bitarray version to 2.0.1 to fix CI

### PR DESCRIPTION
**Pull request by emilyreff7**
Issue to investigate failures: https://github.com/ibis-project/ibis/issues/2780

Noticed a maybe related PR here: https://github.com/ibis-project/ibis/pull/2737

### CODE REVIEW

**Comment by jreback** [comment]
cc @datapythonista

**Review by datapythonista — APPROVED** [review]
Looks good as a quick fix. Do you know if this has been reported in Impyla? I think they should fix it, and we should unpin when a new impyla is available.

Would be good to have an issue in Impyla for this (we can create it ourselves if it doesn't exist), and to have an issue in Ibis to unpin bitarray when Impyla has fixed it. Actually more than unpin, we should require the new Impyla when released, and bitarray should be required to be whatever compatible version automatically from Impyla dependencies.

Can you take care of the issues?

**Comment by jreback** [comment]
thanks @emilyreff7

**Comment by emilyreff7** [comment]
> Looks good as a quick fix. Do you know if this has been reported in Impyla? I think they should fix it, and we should unpin when a new impyla is available.
> 
> Would be good to have an issue in Impyla for this (we can create it ourselves if it doesn't exist), and to have an issue in Ibis to unpin bitarray when Impyla has fixed it. Actually more than unpin, we should require the new Impyla when released, and bitarray should be required to be whatever compatible version automatically from Impyla dependencies.
> 
> Can you take care of the issues?

Thanks @datapythonista  - I didn't see a related issue on the Impyla side so created one here: https://github.com/cloudera/impyla/issues/450.

And updated our ibis issue to reflect your comments above: https://github.com/ibis-project/ibis/issues/2780

**Comment by datapythonista** [comment]
Amazing, thank you @emilyreff7

**Pull request merged**
