### PR TITLE
Make sure we cast when NULL is else in CASE expressions

### LINKED ISSUE #1620: MapD  bucket() : MapD backend doesn't support <class 'ibis.expr.operations.NullLiteral'> operation!
`>>> buckets = [0, 1, 3]`
`>>> bucketed = table.price_col.bucket(buckets).name('bucket')`
`>>> bucketed.value_counts().execute()`
return error : 
  File "/home/sw/anaconda3/lib/python3.6/site-packages/ibis/mapd/operations.py", line 365, in raise_unsupported_op_error
    raise com.UnsupportedOperationError(msg.format(type(op)))
ibis.common.UnsupportedOperationError: MapD backend doesn't support <class 'ibis.expr.operations.NullLiteral'> operation!

Backend=MapD    MapD=4.1.1    ibis=0.14    Python=3.6
Ubuntu=18.04    Anaconda=5.1

### PR DESCRIPTION
**Pull request by cpcloud**
cc @xmnlab

Closes #1620

### CODE REVIEW

**Comment by kszucs** [comment]
@cpcloud tests are failing

**Comment by kszucs** [comment]
I've pinned clickhouse-driver to 0.0.15 until the following issue is going to be resolved: https://github.com/mymarilyn/clickhouse-driver/issues/59

**Comment by cpcloud** [comment]
@kszucs thanks. I'll fix up the tests today.

**Comment by cpcloud** [comment]
Merging on green.

**Pull request closed without merging**
