### PR TITLE
feat(examples): enable progressbar and faster hashing

### PR DESCRIPTION
**Pull request by cpcloud**
This PR enables the progress bar for pooch downloads, which is a nice UX improvement for end users. It also enables the xxhash extra which is a non-cryptographic and faster hashing algorithm used to hash pooch data when generating the registry.

### CODE REVIEW

**Review by kszucs — APPROVED** [review]

**Comment by syvlabs** [comment]
@cpcloud @kszucs is there any way to make the xxHash dependency optional? It is currently the only blocker to running this library in [Pyodide](https://pyodide.org/en/stable/) (i.e. running Ibis completely inside the browser, through wasm). Running Ibis in-browser would greatly expand the potential of the library 🙂

**Comment by cpcloud** [comment]
Yes, we can remove that as an optional dependency. It's not clearly adding a lot of value.

**Comment by cpcloud** [comment]
@syvlabs Out of curiosity is `pyarrow` available with Pyodide? We are taking on pyarrow as a required dependency in the next major release (6.0.0) of ibis to simplify a bunch of data conversion internals as well as make output types much more consistent across backends.

**Comment by syvlabs** [comment]
@cpcloud not yet -- see https://pyodide.org/en/latest/usage/packages-in-pyodide.html

**Comment by syvlabs** [comment]
In that case maybe it doesnt make sense yet to run ibis in-browser -- the pyarrow integration seems like a good workaround though!

**Comment by cpcloud** [comment]
We are happy to help in whatever way we can though!

Please keep us updated, and we'll keep an eye on that package list 😃

**Pull request merged**
