### PR TITLE
Add day_of_week* API

### LINKED ISSUE #306: Day of week API for timestamp values

### PR DESCRIPTION
**Pull request by cpcloud**
closes #306

### CODE REVIEW

**Comment by cpcloud** [comment]
@wesm @jreback Curious about your thoughts on the API here.

I've defined
- `day_of_week_index()`: the index of the value's day relative to Sunday which starts at 1
- `day_of_week_name()`: name of the day of the week

Originally I had `day_of_week(name=False)` which would return a different type depending on the input, which I thought might be confusing to users. OTOH it does reduce the API surface a tiny bit.

**Comment by jreback** [comment]
maybe have day_of_week be a node which can have index() or name() in it?

**Comment by cpcloud** [comment]
Interesting. This *could* be modeled as a `struct<index: int32, name: string>` logically.

So for example a user could do the following:

```python
dow = t.date_column.day_of_week()
result = dow.execute()  # this returns a Series of dict

index = dow.index().execute()  # series of int32
name = dow.name().execute()  # series of strings
```

**Comment by cpcloud** [comment]
closes #306

**Comment by cpcloud** [comment]
Merging on green.

**Pull request closed without merging**
