### PR TITLE
Fix pandas benchmark test functions

### LINKED ISSUE #2455: BENCH: cleanup errors around benchmarks
we are showing some errors in the benchmark suite: https://github.com/ibis-project/ibis/pull/2451/checks?check_run_id=1220781799

would be nice to have these run fully w/o errors.

### PR DESCRIPTION
**Pull request by matthewmturner**
closes #2455 

@datapythonista @jreback

Actually it looked like the functions existed but just werent being called with the correct name.  Lmk if you think otherwise.

### CODE REVIEW

**Comment by jreback** [comment]
hmm
```
[ 34.78%] ··· ...dasBackend.time_low_card_grouped_rolling_udf             failed
[ 34.78%] ···· asv: benchmark timed out (timeout 60.0s)
[ 36.96%] ··· ...Backend.time_low_card_grouped_rolling_udf_wm             failed
[ 36.96%] ···· asv: benchmark timed out (timeout 60.0s)
```

**Comment by matthewmturner** [comment]
@jreback i timed the functions locally and got the following:
```
In [7]: %timeit p.time_low_card_grouped_rolling_udf()
1min 5s ± 1.08 s per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [8]: %timeit p.time_high_card_grouped_rolling_udf()
40.3 s ± 881 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [9]: %timeit p.time_high_card_grouped_rolling_udf_wm()
3min 32s ± 2.12 s per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [10]: %timeit p.time_low_card_grouped_rolling_udf_wm()
3min 34s ± 4.93 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
Are you ok if i add `timeout=240` to the PandasBackend class?

**Comment by jreback** [comment]
instead of changing the timeout can u trim thr tests so they r faster

**Comment by matthewmturner** [comment]
> 
> 
> instead of changing the timeout can u trim thr tests so they r faster

Would that be by reducing `n` in `setup` (i.e. decreasing testing data set size)?  If so, all other tests would be impacted as well and wouldnt that make their benchmark times non comparable before and after the change?  I could also move the slow tests to their own class if thats the approach you want to take.

**Comment by jreback** [comment]
it's fine 

benchmarks should be relatively fast - seconds at most

**Comment by matthewmturner** [comment]
@jreback i think were good on the pandas backend benchmarks now.

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
thanks @matthewmturner 


these are also failing (prob for an import issue)
```
ram [7121292]: · Discovering benchmarks
· Running 23 total benchmarks (1 commits * 1 environments * 23 benchmarks)
[  0.00%] ·· Benchmarking existing-py_usr_share_miniconda_bin_python3.7
[  2.17%] ··· benchmarks.Compilation.time_impala_base_compile             failed
[  2.17%] ···· Traceback (most recent call last):
                 File "/usr/share/miniconda/lib/python3.7/site-packages/asv/benchmark.py", line 1184, in main_run_server
                   main_run(run_args)
                 File "/usr/share/miniconda/lib/python3.7/site-packages/asv/benchmark.py", line 1058, in main_run
                   result = benchmark.do_run()
                 File "/usr/share/miniconda/lib/python3.7/site-packages/asv/benchmark.py", line 537, in do_run
                   return self.run(*self._current_params)
                 File "/usr/share/miniconda/lib/python3.7/site-packages/asv/benchmark.py", line 631, in run
                   min_run_count=self.min_run_count)
                 File "/usr/share/miniconda/lib/python3.7/site-packages/asv/benchmark.py", line 694, in benchmark_timing
                   timing = timer.timeit(number)
                 File "/usr/share/miniconda/lib/python3.7/timeit.py", line 177, in timeit
                   timing = self.inner(it, self.timer)
                 File "<timeit-src>", line 6, in inner
                 File "/home/runner/work/ibis/ibis/benchmarks/benchmarks.py", line 133, in time_impala_base_compile
                   ibis.impala.compile(self.base)
                 File "/home/runner/work/ibis/ibis/ibis/__init__.py", line 88, in __getattr__
                   raise AttributeError
               AttributeError

[  4.35%] ··· ...s.Compilation.time_impala_large_expr_compile             failed
[  4.35%] ···· Traceback (most recent call last):
                 File "/usr/share/miniconda/lib/python3.7/site-packages/asv/benchmark.py", line 1184, in main_run_server
                   main_run(run_args)
                 File "/usr/share/miniconda/lib/python3.7/site-packages/asv/benchmark.py", line 1058, in main_run
                   result = benchmark.do_run()
                 File "/usr/share/miniconda/lib/python3.7/site-packages/asv/benchmark.py", line 537, in do_run
                   return self.run(*self._current_params)
                 File "/usr/share/miniconda/lib/python3.7/site-packages/asv/benchmark.py", line 631, in run
                   min_run_count=self.min_run_count)
                 File "/usr/share/miniconda/lib/python3.7/site-packages/asv/benchmark.py", line 694, in benchmark_timing
                   timing = timer.timeit(number)
                 File "/usr/share/miniconda/lib/python3.7/timeit.py", line 177, in timeit
                   timing = self.inner(it, self.timer)
                 File "<timeit-src>", line 6, in inner
                 File "/home/runner/work/ibis/ibis/benchmarks/benchmarks.py", line 136, in time_impala_large_expr_compile
                   ibis.impala.compile(self.expr)
                 File "/home/runner/work/ibis/ibis/ibis/__init__.py", line 88, in __getattr__
                   raise AttributeError
               AttributeError
```

**Pull request merged**
