### PR TITLE
FEAT: [Omnisci] fillna and nullif implementations

### PR DESCRIPTION
**Pull request by semelianova**
Omnisci doesn't support ISNULL() function, but it is possible to replace it with another sql request.

### CODE REVIEW

**Comment by semelianova** [comment]
CI should be green after merging #2077 and #2051

**Comment by anmyachev** [comment]
@semelianova use `omnisci/core-os-cpu-dev:latest` and fix pep8 errors

**Comment by anmyachev** [comment]
@semelianova should `ibis/tests/all/test_generic.py::test_fillna_nullif` pass since your change?

**Comment by semelianova** [comment]
@anmyachev Not completely, only 2 out of 4 cases which test fillna

**Comment by semelianova** [comment]
@xmnlab @jreback PR is ready for review

**Comment by xmnlab** [comment]
@jreback when you have time could you give a second review pls? thanks!

**Comment by xmnlab** [comment]
@semelianova I will ping here when #2084 is merged.

**Comment by jreback** [comment]
can you merge master, remove the updated image, and update the release note

**Comment by semelianova** [comment]
Need to wait for #2084 is merged

**Comment by anmyachev** [comment]
> Need to wait for #2084 is merged

#2084 was be merged

**Comment by jreback** [comment]
can u merge master 

checks are failing

**Comment by xmnlab** [comment]
@semelianova please try to use the omniscidb image tag used by master `d7e34d4`
the tag you set doesn't exist

**Comment by anmyachev** [comment]
@xmnlab this PR can be closed :)

**Comment by xmnlab** [comment]
thanks @semelianova @anmyachev !

**Pull request closed without merging**
