### PR TITLE
Update to handle change in sql_validate return type

### PR DESCRIPTION
**Pull request by jclay**
This is to accommodate the changes made to the OmniSci client in https://github.com/omnisci/pymapd/pull/325

### CODE REVIEW

**Comment by jclay** [comment]
@datapythonista I have updated the CI suite to use the latest pymapd released today. I will open a PR on the feedstock repo as well.

Note that this was only affecting OmnisciDB v5.3.0 users, so while Ibis had good test coverage for this already, we were testing against v5.2.2 so it was not showing up in the tests. I have added coverage of `sql_validate` functionality on the pymapd side.

I'm not sure if it's related to the pymapd version bump, but I am noticing a drastic increase in the time it takes for conda to resolve the dependency constraints. Once `cudf` 0.15 is released, we should be able to relax some of the dependency constraints on the pymapd side.

**Comment by xmnlab** [comment]
mmm for some reason it is raising this error:

```
ibis/omniscidb/tests/test_operations.py:87: AssertionError
```

not sure why it is changing the result size:

```
>       assert df.size == 80
E       assert 70 == 80
```

**Comment by datapythonista** [comment]
@jclay, `pymapd=0.24` was giving us problems in the CI, conda never finished to solve the environment, and we had to pin the version to `0.23` in #2272. Does this PR still makes sense?

You can investigate the problems with `pymapd` and conda, but for now we'll keep pinning to a specific version, and upgrade only when we know that the solver is not causing trouble.

**Comment by datapythonista** [comment]
@jclay is this something we still want to get merged?

**Comment by jclay** [comment]
I think we will want to get this merged at some point given it fixes the `sql_execute` breakage we were seeing on OmniSci 5.3. Let me close this out for now until I have a chance to revisit and get the failing test resolved.

**Comment by tmostak** [comment]
Hi @jclay, any update on this?

**Pull request closed without merging**
