### PR TITLE
Move pyspark backend to backends directory

### LINKED ISSUE #2424: Move PYSPARK backend to the backends/ directory
**Move the `pyspark/` backend to `backends/pyspark`.**

The current Ibis directory structure is a bit confusing, since backends are mixed with core modules. For example, it's not obvious to know if `pandas/` is a backend, or core functionality. Many of the backends live in the root directory, and some are grouped, like in a directory `sql/`. This makes things even harder and difficult to maintain. Also, ibis uses attributes to access the backends (e.g. `ibis.spark.connect`), and `ibis.spark` in code seems to be the `ibis/spark/` module, but it's not, making things confusing, and even creating problems with pytest.

We're moving backends to a standardized structure, in the `backends/` directory, one backend at a time (each backend in a separate pull request). We started by the OmniSciDB backend, and its PR can be a reference for the changes that need to be made here: #2392

The exact tasks to perform are:
- Move the backend from its original location to `backends/` (if the backend is in a subdirectory, like `sql/`, ignore the subdirectory and just have the backend inside `backends/`, so `sql/sqlite/` -> `backends/sqlite`)
- Move the content of `backends/<your-backend>/api.py` to `backends/<your-backend>/__init__.py`. Backends are using `api.py` for historical reasons, but the public backend API should be in the standard `__init__.py` file of the module.
- Update `ibis/__init__.py` so the backend is imported from the new module (`from ibis.<your-backend> import api` -> `from ibis import <your-backend>`)
- Look for places in the code where your backend is being imported, and update the imports. For imports inside the same backend, please use relative imports (e.g. `import ibis.<your-backend>.whatever` -> `import .whatever`). See the reference PR for examples.
- Update the documentation (in `doc/source/backends/<your-backend>.rst`) so the API is generated from the right location.

After performing the changes, the CI should be green, except for the packaging build (which requires changes in the conda-forge feedstock). You can ignore that error, those changes will be performed later for all moved backends.

### PR DESCRIPTION
**Pull request by saurabhsjain**
Closes #2424

### CODE REVIEW

**Comment by datapythonista** [comment]
This is very strange, there are some imports that need to be updated in `ibis/backends/pyspark/compiler.py` for example, and the CI for the pyspark build is not failing. Looks like the module it's not even imported, `import ibis.backends.pyspark.compiler` should be failing in this PR.

So, not sure if the pyspark backend is being tested at all (the CI looks ok).

CC: @jreback

**Comment by jreback** [comment]
cc @icexelloss @timothydijamco

**Comment by icexelloss** [comment]
I think lots of the tests are "skipped" because the tests skip on import errors?

**Comment by icexelloss** [comment]
```
ibis/tests/all/test_numeric.py sssssssssssssssssssssssssssssssssssssssss [ 10%]
ssssssssssssssssssssssssssssss                                           [ 10%]
ibis/tests/all/test_param.py ssssssssss                                  [ 10%]
ibis/tests/all/test_string.py ssssssssssssssssssssssssssssssssssssssssss [ 11%]
                                                                         [ 11%]
ibis/tests/all/test_temporal.py ssssssssssssssssssssssssssssssssssssssss [ 12%]
ssssssssssssssssssssssssssssssssss                                       [ 13%]
ibis/tests/all/test_union.py ss                                          [ 13%]
ibis/tests/all/test_vectorized_udf.py ssssssssss                         [ 13%]
ibis/tests/all/test_window.py sssssssssssssssssssssssssssssssssssssssss  [ 14%]
```
Copied from the CI log.

**Comment by icexelloss** [comment]
Let me investigate further

**Comment by datapythonista** [comment]
> I think lots of the tests are "skipped" because the tests skip on import errors?

I removed some of those skip if importing fails when I moved to GitHub actions, but looks like not enough of them:
```
SKIPPED [351] ibis/tests/backends.py:132: Unable to access module ibis.pyspark
```
The good news is that I think other PRs are testing pyspark correctly. Feels like it's just that since the error here is an ImportError, instead of reporting it, the tests are just being skipped.

**Comment by icexelloss** [comment]
When I ran the command of this job here: https://github.com/ibis-project/ibis/pull/2431/checks?check_run_id=1194857104

```
PYTEST_BACKENDS='pyspark' PYTEST_EXPRESSION="not hdfs" ./ci/run_tests.sh
```

I got a bunch of test errors instead of skip:
"
ERROR ibis/tests/all/test_window.py::test_ungrouped_unbounded_window[PySpark-unordered-zscore_udf] - AttributeError: module 'ibis.pyspark' has no attribute 'connect'
"

So something different from what I am doing locally and the ci.

**Comment by icexelloss** [comment]
I struggle to run reproduce the ci behavior locally so any help would be much appreciated!

**Comment by datapythonista** [comment]
> I struggle to reproduce the ci behavior locally so any help would be much appreciated!

The CI just calls `ci/setup_env.sh` and then `ci/run_tests.sh`. Did you try with a clean conda environment? I don't think it's great that tests are skipped based on the imports that fail, but for now it's what we have.

**Comment by datapythonista** [comment]
@saurabhsjain the CI problems should be fixed now. Can you merge master and fix the conflicts please?

Also, you'll need to change the module in https://github.com/ibis-project/ibis/blob/master/ci/recipe/meta.yaml#L64 to get the CI passing (ibis.pyspark -> ibis.backends.pyspark).

**Comment by saurabhsjain** [comment]
@datapythonista I am not really sure what needs to be done here. Can you please help me?

**Comment by datapythonista** [comment]
> @datapythonista I am not really sure what needs to be done here. Can you please help me?

What is unclear from the previous message? For merging master, it's mainly `git fetch upstream && git merge upstream/master`. For fixing the import, I think it's quite detailed already, with the link to the line of the block where you need to update, and what needs to be changed.

If it's still unclear, please formulate the question in a specific way, on what you don't understand.

**Comment by datapythonista** [comment]
@saurabhsjain do you have time to finish this PR?

**Comment by datapythonista** [comment]
Closing as stale, so someone else can pick this, and we can finish moving the backends and release soon.

**Pull request closed without merging**
