### PR TITLE
ci: clean up issue assignment job

### PR DESCRIPTION
**Pull request by cpcloud**
This PR removes `assign.yml` which currently doesn't seem to serve a purpose
other than to eat up CI time.

### CODE REVIEW

**Comment by cpcloud** [comment]
This jobs does have an effect, but only when someone writes `<slash> take`. No one appears to be doing that, so there's no reason to keep the job around.

**Comment by jreback** [comment]
hmm this is how contributors take issues.....

**Comment by cpcloud** [comment]
I haven't seen anyone use it for a while. Maybe we just need to publicize it better?

**Comment by jreback** [comment]
> I haven't seen anyone use it for a while. Maybe we just need to publicize it better?

yeah i would add to the docs

**Comment by cpcloud** [comment]
> > I haven't seen anyone use it for a while. Maybe we just need to publicize it better?
> 
> yeah i would add to the docs

Turns out it was already there, I updated a bit.

**Review by jreback — APPROVED** [review]

**Pull request merged**
