### PR TITLE
refactor(snowflake): remove broken fetch_arrow functionality

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by cpcloud** [comment]
Snowflake tests look good:

```
…/ibis on  test-snowflake-pyarrow is 📦 v4.1.0 via 🐍 v3.10.9 via ❄️  impure (ibis-3.10.9-env) took 14s
❯ pytest -m snowflake -n auto --dist=loadgroup -q
bringing up nodes...
ssss.ss.x..s..sx............x.......x....x............x.x..x.x....x..xx....x.xxx.x...xx.x...x......x..x......x....x..x.x..x.xx.xx..xxx.............x.....xx...........x.x.x......x...x.. [ 22%]
.......xxx.x.x..x...x...x...x..xxx.x........xxx.....xxxx.x........x.x........x..xx.x...xx.xxxx.xxxx..x..x.x..x.......x..x..x...x...x.xx.s........x....................x..xx..x.......... [ 44%]
.....x..................................x.....................................x...................................x..............x..x......x..............x..............x.............x [ 66%]
..........x......x.x........................x...xxx..xxx...xx.x..........xxxx.x....x.xx....x..x.......x....xx........x..........x...x.........x................x.....x.................. [ 88%]
...................................x.................x....x.......xx....x...........xs..x.....x.                                                                                         [100%]
675 passed, 10 skipped, 147 xfailed in 85.75s (0:01:25)
…/ibis on  test-snowflake-pyarrow is 📦 v4.1.0 via 🐍 v3.10.9 via ❄️  impure (ibis-3.10.9-env) took 1m26s
```

**Comment by malthe** [comment]
@cpcloud what's the story on this one – we're looking to utilize this faster querying API, but it seems some stuff was considered broken enough that it's been pulled out again.

**Comment by malthe** [comment]
I tried to set this query result format to "ARROW" (making some minor changes to the code) and both using `fetch_arrow_all` and `fetch_pandas_all` I get significantly faster query time.

For those users that are just querying for structured data in native tables, it would be great to have the option to use this capability. I understand that there could be some lacking support for nested data, but perhaps there could be an opt-in to use the faster API for structured results.

**Comment by cpcloud** [comment]
@malthe That sounds like a fine idea to me. We could expose that via a kwarg + url parameter for snowflake. This can go in after 5.0, which we are releasing this week!

**Pull request merged**
