### PR TITLE
CI: Trying to find a point where the disk space problem didn't happen

### PR DESCRIPTION
**Pull request by datapythonista**
Seems like the master builds have been failing since December last year, for broken tests.

The disk space problems started to fail the doc build after #2153 was merged. I guess the different version of the omnisci image is the cause. We can check the increase in those images if it doesn't fail here, and revert that commit, if CI doesn't break with the disk space error here.

### CODE REVIEW

**Comment by datapythonista** [comment]
Looks like the compressed size of both (compressed) images are around the same, 1.65/1.66 Gb:
- https://hub.docker.com/layers/omnisci/core-os-cpu-dev/cecceef/images/sha256-ea04b3cde11daf97e7da7c40393a69e828a3fb87ea2aa642ad78639f21b167a1?context=explore
- https://hub.docker.com/layers/omnisci/core-os-cpu-dev/d7e34d4/images/sha256-a3905cbdae812a83539ce68d1e6eddc7fd0b6ffb5f4887f6782886c4a83eea1e?context=explore

**Comment by datapythonista** [comment]
For the record. So far I reverted every commit to master up to #2153. CI keeps failing, must builds. I see the `No space left on device` only in `LinuxTest py36` and `37`, other builds fail with other problems.

Windows 36 and 37 have 10 failing tests, caused by an `access violation`, the failures show as:
```
2020-04-22T10:32:23.1302709Z _____________________ ibis/tests/all/test_aggregation.py ______________________
2020-04-22T10:32:23.1303595Z [gw1] win32 -- Python 3.7.6 c:\miniconda\envs\ibis37\python.exe
2020-04-22T10:32:23.1304546Z worker 'gw1' crashed while running 'ibis/tests/all/test_aggregation.py::test_aggregation[Parquet-no_cond-count]'
```

The docs build fails when installing the pip dependencies with the next error from pip: `EOFError: marshal data too short`.

**Comment by jreback** [comment]
FYI @xmnlab is also looking at this in : https://github.com/ibis-project/ibis/pull/2182

I don't think its an actual ibis code change issue itself, rather some combination of changes in infrastrue on the CI / conda changes.

**Comment by jreback** [comment]
happy to have multiple eyes here though.

**Pull request closed without merging**
