### PR TITLE
fix(oracle): use case statements to grab table metadata instead of bools

### PR DESCRIPTION
**Pull request by gforsyth**
xref: #9179 #9378 

Definitely more fixes needed, I just didn't want to lose track of this branch.

I was able to get some sense of the failures by switching the Oracle docker container:

```diff
       - druid
 
   oracle:
-    image: gvenzl/oracle-free:23.4-slim
+    image: gvenzl/oracle-xe:18.4.0-slim
     environment:
       ORACLE_PASSWORD: ibis
       ORACLE_DATABASE: IBIS_TESTING
```

I couldn't find a version 19 container.
Also note that this requires a bunch of annoying changes to the conftest setup because Oracle 18 doesn't support `DROP TABLE IF EXISTS`

### CODE REVIEW

**Comment by cpcloud** [comment]
Started playing around with this some more and the outlook isn't great.

I was able to get the test setup working on 18c, but that's the tip of the iceberg.

Here are some things we'd have to do to get this to work:

1. The conversion of boolean -> `CASE`-with-int needs to happen in subqueries, not just the final outer query, otherwise the database errors with this beautiful error message

> oracledb.exceptions.DatabaseError: ORA-00923: FROM keyword not found where expected

getting this right has proved to be elusive for MS SQL which in 2024 **still** does not have boolean type 😮‍💨 

2. The bool conversion also has to handle the null case (which isn't a huge deal)

which has effectively nothing to do with what the problem is

2. `DROP` has to execute some PL/SQL, but only in the case that `force=True`, yay.

My vote is to scrap this PR and only support Oracle starting at version `v${THE_ONE_WITH_PROPER_BOOLS}`.

**Comment by gforsyth** [comment]
> My vote is to scrap this PR and only support Oracle starting at version `v${THE_ONE_WITH_PROPER_BOOLS}`.

That is definitely OK with me.

**Comment by gitgud5000** [comment]
I'm using an Oracle v19 db and this fix solved the error I was getting when using `con.table()`:
> oracledb.exceptions.DatabaseError: ORA-00923: FROM keyword not found where expected

Will this fix be available in the next release?

**Comment by gforsyth** [comment]
> Will this fix be available in the next release or will you only officially support >=23c?

Hey @gitgud5000 -- I think we currently have to limit ourselves to only supporting >=23c.  While some of the fixes in here get you further along using Ibis with Oracle 19 (as you have discovered), there are many remaining pitfalls, especially around query correctness, that need to be addressed due to the lack of proper bool support (among other things).

**Pull request closed without merging**
