### PR TITLE
fix(flink): correct the translation of `ops.Power`

### PR DESCRIPTION
**Pull request by deepyaman**

### CODE REVIEW

**Review by cpcloud — APPROVED** [review]

**Comment by cpcloud** [comment]
Does this need a test to prevent a regression?

**Comment by deepyaman** [comment]
> Does this need a test to prevent a regression?

It's already being (or will be?) tested as part of the common backend test suite. As I've been going through the failures in https://github.com/ibis-project/ibis/pull/6920, I've been extracting the fixes for whatever I can (so, in the end, that PR will just contain all the stuff marked `notimpl`, etc.). Once that is able to be merged, all of these kinds of things are getting tested automatically.

Prior to this PR, if I run the test suite, as enabled on that branch:

```
E                   py4j.protocol.Py4JJavaError: An error occurred while calling o8.sqlQuery.
E                   : org.apache.flink.table.api.ValidationException: SQL validation failed. From line 1, column 8 to line 1, column 67: No match found for function signature pow(<NUMERIC>, <NUMERIC>)
E                       at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.org$apache$flink$table$planner$calcite$FlinkPlannerImpl$$validate(FlinkPlannerImpl.scala:187)
E                       at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.validate(FlinkPlannerImpl.scala:113)
E                       at org.apache.flink.table.planner.operations.SqlToOperationConverter.convert(SqlToOperationConverter.java:281)
E                       at org.apache.flink.table.planner.delegation.ParserImpl.parse(ParserImpl.java:106)
E                       at org.apache.flink.table.api.internal.TableEnvironmentImpl.sqlQuery(TableEnvironmentImpl.java:738)
E                       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
E                       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
E                       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
E                       at java.base/java.lang.reflect.Method.invoke(Method.java:566)
E                       at org.apache.flink.api.python.shaded.py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
E                       at org.apache.flink.api.python.shaded.py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
E                       at org.apache.flink.api.python.shaded.py4j.Gateway.invoke(Gateway.java:282)
E                       at org.apache.flink.api.python.shaded.py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
E                       at org.apache.flink.api.python.shaded.py4j.commands.CallCommand.execute(CallCommand.java:79)
E                       at org.apache.flink.api.python.shaded.py4j.GatewayConnection.run(GatewayConnection.java:238)
E                       at java.base/java.lang.Thread.run(Thread.java:829)
E                   Caused by: org.apache.calcite.runtime.CalciteContextException: From line 1, column 8 to line 1, column 67: No match found for function signature pow(<NUMERIC>, <NUMERIC>)
E                       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
E                       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
E                       at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
E                       at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
E                       at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:505)
E                       at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:932)
E                       at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:917)
E                       at org.apache.calcite.sql.validate.SqlValidatorImpl.newValidationError(SqlValidatorImpl.java:5163)
E                       at org.apache.calcite.sql.validate.SqlValidatorImpl.handleUnresolvedFunction(SqlValidatorImpl.java:1949)
E                       at org.apache.calcite.sql.SqlFunction.deriveType(SqlFunction.java:326)
E                       at org.apache.calcite.sql.SqlFunction.deriveType(SqlFunction.java:231)
E                       at org.apache.calcite.sql.validate.SqlValidatorImpl$DeriveTypeVisitor.visit(SqlValidatorImpl.java:6218)
E                       at org.apache.calcite.sql.validate.SqlValidatorImpl$DeriveTypeVisitor.visit(SqlValidatorImpl.java:6203)
E                       at org.apache.calcite.sql.SqlCall.accept(SqlCall.java:161)
E                       at org.apache.calcite.sql.validate.SqlValidatorImpl.deriveTypeImpl(SqlValidatorImpl.java:1861)
E                       at org.apache.calcite.sql.validate.SqlValidatorImpl.deriveType(SqlValidatorImpl.java:1852)
E                       at org.apache.calcite.sql.SqlAsOperator.deriveType(SqlAsOperator.java:133)
E                       at org.apache.calcite.sql.validate.SqlValidatorImpl$DeriveTypeVisitor.visit(SqlValidatorImpl.java:6218)
E                       at org.apache.calcite.sql.validate.SqlValidatorImpl$DeriveTypeVisitor.visit(SqlValidatorImpl.java:6203)
E                       at org.apache.calcite.sql.SqlCall.accept(SqlCall.java:161)
E                       at org.apache.calcite.sql.validate.SqlValidatorImpl.deriveTypeImpl(SqlValidatorImpl.java:1861)
E                       at org.apache.calcite.sql.validate.SqlValidatorImpl.deriveType(SqlValidatorImpl.java:1852)
E                       at org.apache.calcite.sql.validate.SqlValidatorImpl.expandSelectItem(SqlValidatorImpl.java:449)
E                       at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelectList(SqlValidatorImpl.java:4324)
E                       at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3570)
E                       at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:64)
E                       at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:89)
E                       at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1042)
E                       at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:1017)
E                       at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:247)
E                       at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:992)
E                       at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:741)
E                       at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.org$apache$flink$table$planner$calcite$FlinkPlannerImpl$$validate(FlinkPlannerImpl.scala:183)
E                       ... 15 more
E                   Caused by: org.apache.calcite.sql.validate.SqlValidatorException: No match found for function signature pow(<NUMERIC>, <NUMERIC>)
E                       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
E                       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
E                       at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
E                       at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
E                       at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:505)
E                       at org.apache.calcite.runtime.Resources$ExInst.ex(Resources.java:599)
E                       ... 43 more

/home/vscode/miniconda3/envs/ibis-dev/lib/python3.10/site-packages/py4j/protocol.py:326: Py4JJavaError
-------------------------------------------- generated xml file: /workspaces/ibis/junit.xml ---------------------------------------------

---------- coverage: platform linux, python 3.10.12-final-0 ----------
Coverage XML written to file coverage.xml

======================================================== short test summary info ========================================================
FAILED ibis/backends/tests/test_numeric.py::test_binary_arithmetic_operations[flink-pow] - py4j.protocol.Py4JJavaError: An error occurred while calling o8.sqlQuery.
================================================== 1 failed, 2537 deselected in 18.08s ==================================================
```

**Comment by cpcloud** [comment]
SGTM! Thanks for the explanation.

**Comment by cpcloud** [comment]
The impala failure is unrelated (github actions hiccup)

**Pull request merged**
