### PR TITLE
CI: Splitting OmniSci and Spark jobs, and allowing to install minimum supported dependencies

### PR DESCRIPTION
**Pull request by datapythonista**
Making OmniSci and Spark CI jobs independent. And letting the CI test with the minimum supported dependencies for a backend. For example, if we are testing spark with `pyspark>=3.0` in `deps/pyspark.yml`, but the minimum support version is `2.0`, we can simply add a `deps/pyspark-min.yml` with `pyspark=2.0`, and then both sets of dependencies will be tested (the minimum supported dependencies will be tested in the 3.7 job).

xref #2348

@timothydijamco does this leave the CI in a way that you can implement the pyspark udf stuff?

### CODE REVIEW

**Comment by jreback** [comment]
would leave 3.8 out the matrix for both of these for now (wasn't there before)

i know we have an issue for spark and 3.8 not sure about omnisci

**Comment by datapythonista** [comment]
> i know we have an issue for spark and 3.8 not sure about omnisci

Yes, both are failing. I saw 3.8 in the previous PR, and wanted to check if they were working now, but will revert now, thanks.

**Comment by datapythonista** [comment]
> i know we have an issue for spark and 3.8

We'll see now in the new run, but I think in Python 3.7 pyspark 2 is installed, and the issue with 3.8 is probably because pyspark 3 is being installed. So, I guess the issue is not with 3.8, but with pyspark 3.0.

**Comment by timothydijamco** [comment]
@datapythonista I think your idea in #2348 (which you're implementing here) will work great. Thank you so much for doing this!

Here is the roadmap of future work to get to the point where we can test UDFs on PySpark and Spark and also test on PySpark 3:

_To successfully enable the UDF tests for the PySpark and Spark min build:_
- Pin `pyspark>=2.4.3, <3.0.0` and `pyarrow>=0.12, <=0.14.1` in `pyspark-min.yml` and `spark-min.yml`
- Add dep on `doubleconversion` in `pyspark-min.yml` and `spark-min.yml`
- Remove `not udf` for PySpark and Spark CI group

_To successfully test on `pyspark` 3.0:_
- Fix some tests in the Spark backend that will start to not `xfail` due to `pyspark` being 3.0, but will still fail as they are broken
- Change some PySpark and Spark backend tests to accept both `pyspark` 2 and `pyspark` 3 behavior in regards to `None` vs `np.nan`
- Fix remaining tests that would fail (should all be tests that are marked `xfail` but no longer fail due to `pyspark` being 3.0)

I can open up a follow-up PR for each of these two things once this is merged. The first PR will be pretty simple. The second PR is a bit more involved, but I've done some of the changes (fix broken Spark backend tests) already in #2348 (will copy the changes from #2348 into the new PR) and have a decent idea for what needs to be done to for the other changes

**Comment by datapythonista** [comment]
Thanks for the feedback @timothydijamco, this sounds great.

Just one comment. We usually pin with `package>=version` so when there is an update we get it tested. Mainly, because when users do `conda install ibis` the new package is the one that they are likely to get, since they don't specify the version. We do specify a version to make conda resolve faster.

For the minimum version, not sure if it can make more sense to use `package=minumum_supported_version`. With probably rare exceptions, I think using something like `pyarrow>=0.12, <=0.14.1` would simply install `0.14.1` and give the misleading exception that we're supporting (testing) `0.12`. So, it may make more sense to use `pyarrow=0.12` or `pyarrow=0.14.1`.

@jreback this is green and should be ready now (I removed 3.8 as you said).

**Review by jreback — APPROVED** [review]
thanks @datapythonista

**Comment by timothydijamco** [comment]
> Thanks for the feedback @timothydijamco, this sounds great.
> 
> Just one comment. We usually pin with `package>=version` so when there is an update we get it tested. Mainly, because when users do `conda install ibis` the new package is the one that they are likely to get, since they don't specify the version. We do specify a version to make conda resolve faster.
> 
> For the minimum version, not sure if it can make more sense to use `package=minumum_supported_version`. With probably rare exceptions, I think using something like `pyarrow>=0.12, <=0.14.1` would simply install `0.14.1` and give the misleading exception that we're supporting (testing) `0.12`. So, it may make more sense to use `pyarrow=0.12` or `pyarrow=0.14.1`.

@datapythonista  That makes sense. I'll use fixed versions in the future PR for the minimum dependencies

**Pull request merged**
