### PR TITLE
Changed from pygdf to cudf

### LINKED ISSUE #1693: [MapD] gpu dataframe output not working as of pymapd >= 0.7.0 in ibis-mapd
With pymapd=>0.7.0, there is support for ability to output query results as cudf DataFrames (cudf.dataframe.dataframe.DataFrame, ugh). The ibis client for mapd raises a `NotImplementedError` when I attempt to call the `select_ipc_gpu` method by setting the `execution_type` parameter = `EXECUTION_TYPE_ICP_GPU` on the connection, although executing the same query directly with pymapd works fine

### PR DESCRIPTION
**Pull request by xmnlab**
Fixes #1693

### CODE REVIEW

**Comment by xmnlab** [comment]
waiting for #1696

**Comment by xmnlab** [comment]
cc @niviksha

**Comment by kszucs** [comment]
@xmnlab please rebase on top of master

**Comment by xmnlab** [comment]
logs:

windowstest py37

```

2019-01-31T16:17:51.1349414Z ##[section]Starting: Load PostgreSQL data
2019-01-31T16:17:51.1449954Z ==============================================================================
2019-01-31T16:17:51.1450171Z Task         : Command Line
2019-01-31T16:17:51.1450227Z Description  : Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
2019-01-31T16:17:51.1450263Z Version      : 2.146.1
2019-01-31T16:17:51.1450311Z Author       : Microsoft Corporation
2019-01-31T16:17:51.1450369Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
2019-01-31T16:17:51.1450406Z ==============================================================================
2019-01-31T16:17:52.3496590Z Generating script.
2019-01-31T16:17:52.3496670Z Script contents:
2019-01-31T16:17:52.3496716Z python ci/datamgr.py postgres --psql-path="C:/Program Files/PostgreSQL/10/bin/psql.exe"
2019-01-31T16:17:52.3496952Z ##[command]"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\d8f6df15-a0eb-4349-af3e-8595cb3e7254.cmd""
2019-01-31T16:17:53.0834184Z Traceback (most recent call last):
2019-01-31T16:17:53.0834344Z   File "ci/datamgr.py", line 484, in <module>
2019-01-31T16:17:53.0834428Z     cli(auto_envvar_prefix='IBIS_TEST')
2019-01-31T16:17:53.0834490Z   File "C:\Users\VssAdministrator\.conda\envs\ibis_3.7\lib\site-packages\click\core.py", line 764, in __call__
2019-01-31T16:17:53.0834597Z     return self.main(*args, **kwargs)
2019-01-31T16:17:53.0834659Z   File "C:\Users\VssAdministrator\.conda\envs\ibis_3.7\lib\site-packages\click\core.py", line 717, in main
2019-01-31T16:17:53.0834712Z     rv = self.invoke(ctx)
2019-01-31T16:17:53.0834791Z   File "C:\Users\VssAdministrator\.conda\envs\ibis_3.7\lib\site-packages\click\core.py", line 1137, in invoke
2019-01-31T16:17:53.0834849Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2019-01-31T16:17:53.0834910Z   File "C:\Users\VssAdministrator\.conda\envs\ibis_3.7\lib\site-packages\click\core.py", line 956, in invoke
2019-01-31T16:17:53.0834996Z     return ctx.invoke(self.callback, **ctx.params)
2019-01-31T16:17:53.0835059Z   File "C:\Users\VssAdministrator\.conda\envs\ibis_3.7\lib\site-packages\click\core.py", line 555, in invoke
2019-01-31T16:17:53.0835113Z     return callback(*args, **kwargs)
2019-01-31T16:17:53.0835184Z   File "ci/datamgr.py", line 180, in postgres
2019-01-31T16:17:53.0835397Z     isolation_level='AUTOCOMMIT')
2019-01-31T16:17:53.0835620Z   File "ci/datamgr.py", line 47, in init_database
2019-01-31T16:17:53.0835666Z     recreate_database(driver, new_params, **kwargs)
2019-01-31T16:17:53.0835728Z   File "ci/datamgr.py", line 35, in recreate_database
2019-01-31T16:17:53.0835769Z     engine = sa.create_engine(url, **kwargs)
2019-01-31T16:17:53.0835820Z   File "C:\Users\VssAdministrator\.conda\envs\ibis_3.7\lib\site-packages\sqlalchemy\engine\__init__.py", line 431, in create_engine
2019-01-31T16:17:53.0835887Z     return strategy.create(*args, **kwargs)
2019-01-31T16:17:53.0835940Z   File "C:\Users\VssAdministrator\.conda\envs\ibis_3.7\lib\site-packages\sqlalchemy\engine\strategies.py", line 87, in create
2019-01-31T16:17:53.0836011Z     dbapi = dialect_cls.dbapi(**dbapi_args)
2019-01-31T16:17:53.0836064Z   File "C:\Users\VssAdministrator\.conda\envs\ibis_3.7\lib\site-packages\sqlalchemy\dialects\postgresql\psycopg2.py", line 599, in dbapi
2019-01-31T16:17:53.0836108Z     import psycopg2
2019-01-31T16:17:53.0836180Z   File "C:\Users\VssAdministrator\.conda\envs\ibis_3.7\lib\site-packages\psycopg2\__init__.py", line 50, in <module>
2019-01-31T16:17:53.0836229Z     from psycopg2._psycopg import (                     # noqa
2019-01-31T16:17:53.0836275Z ImportError: DLL load failed: The specified module could not be found.
2019-01-31T16:17:53.2853967Z ##[error]Cmd.exe exited with code '1'.
2019-01-31T16:17:53.3208928Z ##[section]Finishing: Load PostgreSQL data

```

**Comment by kszucs** [comment]
That seems sporious... I'll restart it.
Please use rebase instead of merge, that makes it easier to review and maintain a flat history.

**Comment by xmnlab** [comment]
Ok thanks for the advice! In another project we were losting code using rebase. Do you have any tip or recommendation for using rebase to avoid this problem?

**Comment by kszucs** [comment]
@xmnlab Well, not really. I'm aware of the disadvantages of a force push, but We both ibis and apache arrow prefer rebase. Need to be careful :)

**Comment by xmnlab** [comment]
I will be careful! thanks @kszucs!

it seems pipelines is working! thanks! could you review this PR?

**Comment by kszucs** [comment]
Rebased

**Comment by xmnlab** [comment]
thanks @kszucs !

**Pull request closed without merging**
