### PR TITLE
ci: migrate to setup-python dependency caching

### PR DESCRIPTION
**Pull request by cpcloud**
Apparently these actions are archived and functionality is rolled into setup-python. This PR attempts to validate that.

### CODE REVIEW

**Comment by cpcloud** [comment]
It looks like because we were caching dependencies in the sqlalchemy2 jobs, we were incorrectly passing some tests and failing to expose some incomplete skipping in duckdb geospatial testing. I've fixed those issues in this PR.

**Comment by cpcloud** [comment]
Since we're moving away from sqlalchemy entirely (and thus sqlalchemy2 will no longer be a thing we have to deal with 🎉) I opted to avoid the complexity of generating a single lock file and downloading that file in dependent jobs. The sqlalchemy2 CI will be a bit slower until we land the port to sqlglot.

**Comment by cpcloud** [comment]
Well, I guess it's not even that much slower to avoid generating the lockfile, even better!

**Review by gforsyth — APPROVED** [review]
:shipit:

**Pull request merged**
