### PR TITLE
DOC: add bigquery client reference and privacy policy

### PR DESCRIPTION
**Pull request by tswast**
Adds intersphinx extension to facilitate links to relevant related
libraries.

Towards #2179 and #2025

### CODE REVIEW

**Comment by tswast** [comment]
I had trouble getting `make doc` to run. Seems to be issues with impala. I was able to build just the affected docs with the `sphinx-build` command.

```
sphinx-build -b html -d ../build/doctrees . ../build/html api.rst
```

Screen Shot 2020-04-16 at 2 46 05 PM

```
sphinx-build -b html -d ../build/doctrees . ../build/html privacy.rst
```

Screen Shot 2020-04-16 at 2 50 42 PM

**Comment by tswast** [comment]
commit 8888425e5e6b8d9579add1b2a02690e2c5331810 adds a meta tag, similar to the one we use to verify the pandas-gbq app (https://raw.githubusercontent.com/pydata/pandas-gbq/master/docs/source/index.rst), but that app verification predated the new "Domain" type in the Google Search Console, so I'm not sure that it'll be sufficient for Ibis.

**Comment by tswast** [comment]
Build docs error is

```

ruamel.yaml.clib-0.2 | 156 KB    |            |   0% 
ruamel.yaml.clib-0.2 | 156 KB    | ########## | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... failed

NoSpaceLeftError: No space left on devices.

Service 'ibis' failed to build: The command '/bin/sh -c /opt/conda/bin/conda env create --name ibis-env --file /requirements-$PYTHON_VERSION-dev.yml   && /opt/conda/bin/conda clean --all --yes' returned a non-zero code: 1
Makefile:100: recipe for target 'build' failed
make: *** [build] Error 1
```

Not sure what can be done about lack of space.

**Comment by datapythonista** [comment]
Thanks for this PR @tswast, and sorry for the very delayed review.

The CI should be fixed now. The doc build should work.

You've got conflicts to fix. And besides that, I don't think we want a top-level page in the docs for legal stuff about using Bigquery. Ideally, I think we should have a page for each backend, with all the information for every backend (API + anything else).

What do you think if for now you move the `Using Ibis with Impala` inside a `Backends` directory in the `User guide`. And you add a page `Bigquery` there, with the content of privacy? You can move the current `Backends` page to be the index of this new directory.

Also, I think it would be useful to have links from the API to the page in `User guide > Backends`, and the other way round.

Thanks!

**Comment by datapythonista** [comment]
Thanks for the changes @tswast, looks good.

There is a failure in the CI. I think all the references from the moved Impala page to the API pages need to be updated (paths are relative, and moving the page is causing to look for the API pages somewhere else).

I don't think we want to fix all those in this PR, so I guess it's better to move back the Impala page where it was, and move it in a separate PR. Sorry for making you move it in the first place.

**Comment by jreback** [comment]
thanks @tswast

**Pull request merged**
