### PR TITLE
Restructure SQL compiler

### PR DESCRIPTION
**Pull request by datapythonista**
- Move SQL compiler from `base/sql_alchemy` to `base/sql/compiler`
- Split `compiler.py` (was around 3,000 lines) into different files (same structure as the SQLAlchemy compiler)
- Make the public API of the compiler explicit

No code changes, only moving functions.

### CODE REVIEW

**Comment by datapythonista** [comment]
@jreback the diff here is big, but the changes are trivial, just moving the functions of `compiler.py` into the same files we split the base SQLAlchemy backend. And adding a `__init__.py`. This is a blocker to continue the clean up of the base backend, so if you can give it a bit of priority, that would be great. Thanks!

**Comment by jreback** [comment]
sure (I had merged the other PR first), so need to rebase here. (if this is a problem, then could revert that, then merge this).

**Comment by datapythonista** [comment]
@jreback merged master, all green again. Thanks!

**Comment by jreback** [comment]
thanks @datapythonista

**Pull request merged**
