### PR TITLE
CI: Fix disk space issue

### PR DESCRIPTION
**Pull request by xmnlab**

### CODE REVIEW

**Comment by xmnlab** [comment]
@jreback it is ready for review. thanks!

**Comment by jreback** [comment]
can u explain why the docker change makes this work?

**Comment by xmnlab** [comment]
as I commented in the previous PR, it seems each make command for `docker-compose run` was building the image again that probably why it was raising the error `no space left on device`. also I split the conda update/install into 2 separate `RUN` to use less space during the building.

**Comment by jreback** [comment]
thanks

**Pull request merged**
