### PR TITLE
CI: Fix mypy error in ibis/backends/clickhouse/registry.py

### PR DESCRIPTION
**Pull request by napoles-uach**
xref #2856
Running `mypy ibis/backends/clickhouse/` gave this error below
`ibis/backends/clickhouse/registry.py:698: error: Incompatible types in assignment (expression has type "Dict[AnnotableMeta, Callable[[Any, Any, VarArg(Any)], Any]]", variable has type "List[AnnotableMeta]")`

It was fixed by simply renaming in line 675 the list `_unsupported_ops` to `_unsupported_ops_list` which is used in line 698 to build the Dictionary named `_unsupported_ops`

### CODE REVIEW

**Review by datapythonista — APPROVED** [review]
Thanks @napoles-uach

**Comment by datapythonista** [comment]
Looks good, but it looks like you've got a conflict. Can you merge master (`git fetch upstream && git merge upstream/master`) and resolve the conflict please?

**Comment by datapythonista** [comment]
@napoles-uach you need to run `isort .` in the project, and commit the changes that the command produces. We've got that command to keep the imports sorted in a deterministic way. Not sure if that's a good idea or not, but we've got it, so the CI won't be green until the imports are sorted with isort. Thanks!

**Comment by jreback** [comment]
thanks @napoles-uach

**Comment by napoles-uach** [comment]
> thanks @napoles-uach

Glad to contribute!

**Pull request merged**
