### PR TITLE
TST: test value counts on all backends

### PR DESCRIPTION
**Pull request by kszucs**
Csv and Parquet give empty resultsets, but pandas works fine.

### CODE REVIEW

**Comment by cpcloud** [comment]
@kszucs Is this PR still valid?

**Comment by kszucs** [comment]
The file backends fail with:

```bash
py.test -sv ibis/tests/all/test_aggregation.py::test_value_counts
================================================= test session starts =================================================
platform darwin -- Python 3.6.5, pytest-3.5.0, py-1.5.3, pluggy-0.6.0 -- /Users/krisz/.miniconda/envs/ibis36/bin/python
cachedir: .pytest_cache
rootdir: /Users/krisz/Workspace/ibis, inifile:
collected 9 items

ibis/tests/all/test_aggregation.py::test_value_counts[Csv] FAILED
ibis/tests/all/test_aggregation.py::test_value_counts[Parquet] FAILED
ibis/tests/all/test_aggregation.py::test_value_counts[Pandas] PASSED
ibis/tests/all/test_aggregation.py::test_value_counts[SQLite] PASSED
ibis/tests/all/test_aggregation.py::test_value_counts[Postgres] PASSED
ibis/tests/all/test_aggregation.py::test_value_counts[MySQL] PASSED
ibis/tests/all/test_aggregation.py::test_value_counts[Clickhouse] PASSED
ibis/tests/all/test_aggregation.py::test_value_counts[BigQuery] PASSED
ibis/tests/all/test_aggregation.py::test_value_counts[Impala] PASSED
```

with error

```bash
    def test_value_counts(backend, alltypes, df):
        bool_clause = alltypes.string_col.isin(['1', '4', '7'])
        expr = alltypes[bool_clause].string_col.value_counts()
        result = expr.execute()

        where = df.string_col.isin(['1', '4', '7'])
        expected = (df.loc[where, 'string_col']
                    .value_counts()
                    .to_frame()
                    .reset_index()
                    .rename(columns={'index': 'string_col',
                                     'string_col': 'count'}))

        backend.assert_frame_equal(
>           result.sort_values('string_col').reset_index(drop=True),
            expected.sort_values('string_col').reset_index(drop=True)
        )

...
>   ???
E   KeyError: 'string_col'
```

**Comment by cpcloud** [comment]
Ok, I'll take a look and see if I can get this passing.

**Comment by xmnlab** [comment]
hey @kszucs @cpcloud what is the status of this PR?

do you need any help with this PR?

**Comment by datapythonista** [comment]
Closing this as stale.

**Pull request closed without merging**
