### PR TITLE
refactor(tests): move remaining unittest.TestCase definitions to pytest

### PR DESCRIPTION
**Pull request by cpcloud**
Move remaining tests to pytest and away from unittest.TestCase. The only remaining tests are test_kudu_support.py which I plan to remove entirely in a follow up, and test_patched.py which is only using mocks

### CODE REVIEW

**Comment by jreback** [comment]
lgtm

**Comment by cpcloud** [comment]
@jreback Mind approving?

**Comment by jreback** [comment]
oh yeah this was ok (needs a rebase)

**Comment by cpcloud** [comment]
Merging this on green.

**Pull request merged**
