### PR TITLE
Use new backend classes

### PR DESCRIPTION
**Pull request by datapythonista**
This makes `ibis.imapala` (or any other backend) to be the class `Backend` and not the `ibis/backends/impala/__init__.py` module.

With this, all backends implement `compile`, `verify` and `dialect` (now some do and some don't), and there is just one implementation in the `BaseBackend` class, so no code of those functions is repeated.

### CODE REVIEW

**Comment by datapythonista** [comment]
@jreback this is green now. The idea is that `ibis.sqlite`... are not `ibis/backends/sqlite/__init__.py` anymore, but the `Backend` class on them only, So we know that what it's exposed follows the API in the ABC class.

The final goal is #2678, while the code continues to work and tests pass, this is just an intermediate PR that makes sure everything implemented until now in `Backend` works, and makes it easy to implement the public API step by step.

**Comment by datapythonista** [comment]
@jreback if possible would be great to prioritize this PR. I need this to continue with the public API for the backends.

Looks big, but actually it's quite small, just that changes need to be made to the 14 backends. The only big diffs are moving the `connect` functions inside the `Backend` class. There are no changes to the code, just moving it.

Thanks!

**Comment by jreback** [comment]
@icexelloss any issues here?

**Comment by jreback** [comment]
@datapythonista is there any user api change here?

**Comment by jreback** [comment]
cc @gerrymanoim if you have a chance to look

**Comment by datapythonista** [comment]
> @datapythonista is there any user api change here?

No, all user code should continue to work and be unaffected. `ibis.any_backend` will be a class instead of a module, but the class will have the same exact attributes, so `ibis.my_backend.anything` will still be valid for all cases.

**Comment by jreback** [comment]
can you merge master and ping on green

**Comment by gerrymanoim** [comment]
This seems reasonable to me

**Comment by jreback** [comment]
hmm https://github.com/ibis-project/ibis/pull/2661/checks?check_run_id=2122417598 is now failing, cc @icexelloss

**Comment by datapythonista** [comment]
It started to fail in master when unpinning graphviz, but I guess that's unrelated. Not sure what's the problem, we are pinning pyspark in that build, so not a compatibility problem, unless it's an indirect dependency.

**Comment by datapythonista** [comment]
> can you merge master and ping on green

@jreback CI is now green here, do you want to have a last look?

**Review by jreback — APPROVED** [review]
lgtm. will merge in a bit.

**Comment by jreback** [comment]
@datapythonista this is good
can u rebase once more

**Comment by datapythonista** [comment]
> @datapythonista this is good
> can u rebase once more

done

**Comment by jreback** [comment]
thanks @datapythonista

**Pull request merged**
