### PR TITLE
feat(sqlite): add argmin and argmax functions

### PR DESCRIPTION
**Pull request by mesejo**
### Implementation

Since version [3.7.11]( http://www.sqlite.org/releaselog/3_7_11.html), SQLite supports queries of the form:

```sqlite
SELECT max(x), y FROM table
```
that:

> returns the value of y on the same row that contains the maximum x value.

The same applies to the min aggregate function. 

This solution combines the max (min) aggregate function with the JSON functions: [json_array](https://www.sqlite.org/json1.html#jarray) and [json_extract](https://www.sqlite.org/json1.html#jex) to first build an array: `[y, max(x)]` from the aggregate and then extract `y`.

### CODE REVIEW

**Comment by cpcloud** [comment]
I can help with the Windows failure.

**Comment by mesejo** [comment]
> I can help with the Windows failure.

Thanks 🙏

**Comment by cpcloud** [comment]
Ended up skipping on Windows CI. It seems like the documentation for JSON functions isn't entirely correct, or there's some mismatch/my own misunderstanding of what the Python reported version of SQLite means.

For example, Linux reports the version of SQLite to be 3.37, but the SQLite JSON docs say that JSON functions weren't available until 3.38.

Windows claims that the version is at least 3.38, and yet the JSON functions aren't available.

**Review by cpcloud — APPROVED** [review]
Thanks, LGTM!

**Pull request merged**
