### PR TITLE
CI: Unpin sphinx version

### LINKED ISSUE #2580: Unpin sphinx
Sphinx was pinned to <=3.3.1 to fix the failing LinuxBuildDocs (see issue #2578)

We should unpin sphinx depending on the result of https://github.com/sphinx-doc/sphinx/issues/8583, which I think is the underlying issue

### PR DESCRIPTION
**Pull request by timothydijamco**
Closes #2580 

[Sphinx 3.4.1 was released](https://github.com/sphinx-doc/sphinx/milestone/95?closed=1), which includes the fix to the issue that the Ibis docs CI was having

### CODE REVIEW

**Review by datapythonista — APPROVED** [review]
Looks good, thanks. Can you check the CI and leave it green please?

**Comment by jreback** [comment]
@timothydijamco can you roll the graphviz patches in here as well.

**Comment by timothydijamco** [comment]
@datapythonista @jreback thanks, I'll get the graphviz tests working in #2583 and then we can merge this one after

**Comment by jreback** [comment]
@timothydijamco pls rebase this

**Comment by jreback** [comment]
thanks @timothydijamco

**Pull request merged**
