### PR TITLE
docs(release-notes): fix up version header

### LINKED ISSUE #8624: docs: Make links to sections in release notes stable across releases
### Please describe the issue

I noticed while grabbing a hyperlink to the latest Ibis release from https://ibis-project.org/release_notes that the fragment identifier for the most recent release is ambiguous: https://ibis-project.org/release_notes#section. I then noticed that all the anchor links are similar. Quarto (or pandoc?) appears to not like when headings start with numbers and falls back to some sort of other behavior. The result is that, on every new Ibis release https://ibis-project.org/release_notes#section will jump the user to the latest release and it won't be possible to have a stable link to a particular release section.

While Ibis' users may not expect these links to be stable, I think it's really nice to just have stable anchor hyperlinks.

I'd be happy to send in a PR for a change if this is of interest. I think just changing the headers is the way to go, rather than messing with any custom hacks with Pandoc or similar. Perhaps just prepending "v" or "Ibis " to each heading? While I'm in there I could take a look around the rest of the site to find any other issues.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by cpcloud**
Add permalinks to release notes versions.

Fixes #8624.

### CODE REVIEW

**Comment by cpcloud** [comment]
Not a huge fan of having to write Lua to do this, but c'est la vie.

**Comment by amoeba** [comment]
Hey @cpcloud, following https://github.com/quarto-dev/quarto/issues/413, this seems to work for me locally, in case that would work here:

```patch
diff --git a/docs/release_notes.md b/docs/release_notes.md
index f8def1134..e28af30ea 100644
--- a/docs/release_notes.md
+++ b/docs/release_notes.md
@@ -1,7 +1,7 @@
 Release notes
 ---

-## [8.0.0](https://github.com/ibis-project/ibis/compare/7.2.0...8.0.0) (2024-02-05)
+## [8.0.0](https://github.com/ibis-project/ibis/compare/7.2.0...8.0.0) (2024-02-05) {#8.0.0}


 ### ⚠ BREAKING CHANGES
```

**Comment by cpcloud** [comment]
It might, but the automation around release notes makes it probably roughly the same amount of work as what we currently have

**Comment by cderv** [comment]
@amoeba yes this  is indeed (bad?) Pandoc default for auto identifier for section that does not have explicit and don't start with letter. 
Not that `# v8.0.0` would correctly get you `id="v8.0.0"` on the HTML  - any header starting with a letter first really. 

but probably not what you want here. I'm sharing just in case changing headers would be worth making to prevent special processing.

**Comment by amoeba** [comment]
Right, thanks for pointing that out @cderv. Pandoc is probably saving users from some awful edge cases elsewhere else.

**Pull request merged**
