### PR TITLE
CI: Re-enabled CI for building step.

### LINKED ISSUE #1700: Re-enable conda-forge CI build steps
Had to disable conda build steps in #1696 until We update the recipe in the conda forge feedstock.
There were a lot of changes around conda-forge lately: compiler migration, dropped python3.5 support and ibis also dropped python2.7.

### PR DESCRIPTION
**Pull request by xmnlab**
Resolves #1700

### CODE REVIEW

**Comment by xmnlab** [comment]
waiting https://github.com/conda-forge/ibis-framework-feedstock/pull/26

**Comment by xmnlab** [comment]
# Azure task: CondaEnvironment@1 This task is deprecated. Use `conda` directly in script to work with Anaconda environments.

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/conda-environment?view=azure-devops#yaml-snippet

**Comment by xmnlab** [comment]
not sure why the score in codecov decreased, because it seems the files changes is not tracked by codecov. @cpcloud @kszucs any thought?

**Comment by xmnlab** [comment]
not sure why but locally this change https://github.com/ibis-project/ibis/pull/1710/files#diff-6f1f859c6ca5c4cae7310924786cf661R14 increased the total coverage from 26% to 44% .. but here it seems the coverage decreased ... maybe I am doing something wrong :disappointed:

**Comment by xmnlab** [comment]
it seems it is raising an error related to `google_auth_oauthlib`, any thoughts?

**Comment by kszucs** [comment]
@xmnlab coverage only measures the proportion of lines ran by the test script. If We account the test code as well then the coverage contains both the test and implementation parts of the code. Does it make sense?

**Comment by kszucs** [comment]
It tries to read from the prompt, probably because of missing credentials?

**Comment by xmnlab** [comment]
hey @kszucs thanks for the feedback!

> @xmnlab coverage only measures the proportion of lines ran by the test script. If We account the test code as well then the coverage contains both the test and implementation parts of the code. Does it make sense?

I am not sure if I am following you ... I changed from `tests/*` to `*tests*` to omit all tests not just a subset. for me makes more sense to omit all tests on coverage, because if we add any test in the coverage the report will be confusing ... I also added `__init__` into omit section because probably we don't want to create test for the code there, but if it doesn't make sense, let me know.

> It tries to read from the prompt, probably because of missing credentials?

it seems there was a PR changing something related to that ... but not sure how to fix that in the CI. any thoughts ?

**Comment by xmnlab** [comment]
some reference about the coverage and tests folders: https://commitcode.com/measure-your-tests-coverage/ when the last time says: `You notice I have tests as the ommited files, because we want to analize the code, not the tests themselves.`

**Comment by xmnlab** [comment]
@cpcloud it seems it is done for review!

**Comment by xmnlab** [comment]
hey @cpcloud do you have any thoughts about this PR?

**Comment by cpcloud** [comment]
LGTM. Will merge shortly.

**Pull request merged**
