### PR TITLE
Reduce duplicated compiler code

### PR DESCRIPTION
**Pull request by kszucs**
First step to simplify sql compilers.

### CODE REVIEW

**Comment by kszucs** [comment]
@cpcloud thoughts?

**Comment by kszucs** [comment]
How about an alternative way for dependency injection, a bit more declarative one? 

For example:

```py
class ClickhouseSelect(comp.Select):
    translator = ClickhouseExprTranslator
    table_set_formatter = ClickhouseTableSetFormatter
```

instead of

```py
class ClickhouseSelect(comp.Select):

    @property
    def translator(self):
        return ClickhouseExprTranslator

    @property
    def table_set_formatter(self):
        return ClickhouseTableSetFormatter
```

There is also mixed usage of class variables and object properties, like here https://github.com/kszucs/ibis/blob/1906e61a146ae7f522b6e5d8132130e468c885f2/ibis/clickhouse/compiler.py#L39

I prefer more consistent APIs.

**Comment by cpcloud** [comment]
@kszucs Can you rebase to bring in the changes from #1185? Thanks.

**Comment by kszucs** [comment]
@cpcloud done

**Comment by cpcloud** [comment]
@kszucs Thanks!

**Pull request closed without merging**
