### PR TITLE
fix: exclude null values from `first` and `last` aggregations

### PR DESCRIPTION
**Pull request by jcrist**
Similar to #9318. The handling of `NULL` values in `first`/`last` previously was backend specific. We now standardize all backends to exclude `NULL` values from these aggregations.

### CODE REVIEW

**Review by cpcloud — APPROVED** [review]
LGTM!

**Comment by jcrist** [comment]
Gah, this has surfaced a `datafusion` bug: https://github.com/apache/datafusion/issues/10878.

A few options:

- `xfail` the bad queries for now. They pass fine on earlier versions of `datafusion`, and should pass again in the future
- Drop `FILTER` clause usage in datafusion (maybe only for the faulty version?) in favor of using `ifelse` and `NULL` exclusion. This would ensure `datafusion` code works on all `datafusion` releases, with some slight added code complexity for us.

**Comment by gforsyth** [comment]
> `xfail` the bad queries for now. They pass fine on earlier versions of `datafusion`, and should pass again in the future

I vote for marking this as a `notyet`

**Comment by cpcloud** [comment]
> Drop FILTER clause usage in datafusion (maybe only for the faulty version?) in favor of using ifelse and NULL exclusion. This would ensure datafusion code works on all datafusion releases, with some slight added code complexity for us.

If you've already got this working, then great! I remember looking into it awhile ago and it not being particularly straightforward to get working.

**Comment by cpcloud** [comment]
Also

> xfail the bad queries for now. They pass fine on earlier versions of datafusion, and should pass again in the future

SGTM.

**Pull request merged**
