### PR TITLE
docs: move to mkdocs

### PR DESCRIPTION
**Pull request by cpcloud**
This PR moves us off of pysuerga and onto mkdocs.

pysuerga appears to be unmaintained and duplicates
nearly all of the functionality of mkdocs.

### CODE REVIEW

**Comment by cpcloud** [comment]
Some screenshots from the new docs:

Landing page:

image

API docs:

image

image

**Review by kszucs — APPROVED** [review]
LGTM

**Comment by kszucs** [comment]
Unrelated, but we should consider to use the [pydata sphinx theme](https://pydata-sphinx-theme.readthedocs.io/en/latest/#) and move the markdown files to sphinx.

**Comment by jreback** [comment]
note a superfan of the dark landing page (when everything else is light). is this a change?

> Unrelated, but we should consider to use the pydata sphinx theme and move the markdown files to sphinx.
+1 on @kszucs suggestion

**Comment by jreback** [comment]
https://ibis-project.org/ yeah this looks light

**Comment by cpcloud** [comment]
> not a superfan of the dark landing page (when everything else is light). is this a change?
> 
> > Unrelated, but we should consider to use the pydata sphinx theme and move the markdown files to sphinx.
> > +1 on @kszucs suggestion

It's dependent on the user's system theme

**Comment by cpcloud** [comment]
-1 on moving towards sphinx. I think we should be moving away from sphinx as much as possible and towards markdown.

**Comment by cpcloud** [comment]
@jreback @kszucs if you want to discuss sphinx vs markdown vs `$another_shiny_thing` please open up a Discussion.

**Comment by jreback** [comment]
> > not a superfan of the dark landing page (when everything else is light). is this a change?
> > > Unrelated, but we should consider to use the pydata sphinx theme and move the markdown files to sphinx.
> > > +1 on @kszucs suggestion
> 
> It's dependent on the user's system theme

got it

**Review by jreback — APPROVED** [review]
looks fine to me

**Comment by cpcloud** [comment]
Merging. This may need follow ups, let's see.

**Pull request merged**
