### PR TITLE
Fix hdfs_connect on GHA

### LINKED ISSUE #2533: Ibis failing to connect to hdfs in GitHub Actions
xref: #2388

For some reason Ibis doesn't seem to be connecting to hdfs when in localhost.

In GitHub actions, the port is open, as shown by:
```
$ nc -zvw3 $IBIS_TEST_IMPALA_HOST 50070
Connection to localhost 50070 port [tcp/*] succeeded!
```

But when trying to connect to hdfs from Ibis:

```python
import io
import ibis

hdfs_conn = ibis.impala.hdfs_connect(
    host='localhost',
    port=50070,
    auth_mechanism='NOSASL',
    verify=True,
    user='hdfs',
)
hdfs_conn.put('/tmp/test_file', io.BytesIO(b'1234'))
```

It fails with the next error, like if the host was `impala`, and couldn't be resolved:

```
Traceback (most recent call last):
  File "/usr/share/miniconda/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/share/miniconda/lib/python3.7/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/share/miniconda/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/miniconda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/share/miniconda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/share/miniconda/lib/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/share/miniconda/lib/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/share/miniconda/lib/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/share/miniconda/lib/python3.7/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/usr/share/miniconda/lib/python3.7/http/client.py", line 972, in send
    self.connect()
  File "/usr/share/miniconda/lib/python3.7/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/share/miniconda/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f2505ca41d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/miniconda/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/share/miniconda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/share/miniconda/lib/python3.7/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='impala', port=50075): Max retries exceeded with url: /webhdfs/v1/tmp/test_file?op=CREATE&user.name=hdfs&namenoderpcaddress=impala:8020&overwrite=false&user.name=hdfs (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2505ca41d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ci/test_impala.py", line 12, in <module>
    hdfs_conn.put('/tmp/test_file', io.BytesIO(b'1234'))
  File "/home/runner/work/ibis/ibis/ibis/backends/impala/hdfs.py", line 621, in put
    hdfs_path, data=resource, overwrite=overwrite, **kwargs
  File "/usr/share/miniconda/lib/python3.7/site-packages/hdfs/client.py", line 477, in write
    consumer(data)
  File "/usr/share/miniconda/lib/python3.7/site-packages/hdfs/client.py", line 469, in consumer
    data=(c.encode(encoding) for c in _data) if encoding else _data,
  File "/usr/share/miniconda/lib/python3.7/site-packages/hdfs/client.py", line 214, in _request
    **kwargs
  File "/usr/share/miniconda/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/miniconda/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/miniconda/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='impala', port=50075): Max retries exceeded with url: /webhdfs/v1/tmp/test_file?op=CREATE&user.name=hdfs&namenoderpcaddress=impala:8020&overwrite=false&user.name=hdfs (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2505ca41d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```

### PR DESCRIPTION
**Pull request by matthewmturner**
closes #2533

### CODE REVIEW

**Comment by matthewmturner** [comment]
@datapythonista   I'm struggling to get the image working locally to play around with.  I followed what @gerrymanoim laid out in #2388 after cloning https://github.com/ibis-project/docker-impala.  Im on windows and use WSL2.  Going to keep trying though.

In the meantime i tried adding some prints to see how the connection parameters are being executed in CI.  Not sure if it will work like that but will keep you posted.

**Comment by datapythonista** [comment]
The docker image is starting correctly on GitHub Actions, you should be able to get it working by using the same configuration. Also note that for whatever reason the impala docker requires the postgres one.

When I was trying to make things work, I had the feeling that the problem was that hdfs is trying to connect to the host `impala` instead of `localhost`, but no idea where this is coming from, I couldn't find it.

**Comment by matthewmturner** [comment]
For my understanding - ive been trying to see when/why the 

> 
> 
> The docker image is starting correctly on GitHub Actions, you should be able to get it working by using the same configuration. Also note that for whatever reason the impala docker requires the postgres one.
> 
> When I was trying to make things work, I had the feeling that the problem was that hdfs is trying to connect to the host `impala` instead of `localhost`, but no idea where this is coming from, I couldn't find it.

Yup noticed that and thats what i was focusing on as well (the port and host in the error being different than what was passed into `hdfs_connect`).

**Comment by matthewmturner** [comment]
@datapythonista took a shot in the dark by changing the `--hostname` option to `localhost` from `impala` in `.github/workflows/main.yaml`.  I think it allowed it to connect because now the error is coming from further on in the `load` function.  Specfically, now it fails at `build_udfs`.  

From your view is this a step in the right direction - or should i try something else?

**Comment by datapythonista** [comment]
My understanding is that the `--hostname` is for docker to set its host name. I think it is set in pipelines too. Feels like it should be ibis who decides whether it's connecting to one host or the other, not docker. But if it works, happy to move forward.

The error now seems that a dependency `boost` is missing. Not sure if it's being installed in pipelines but not in actions, or maybe the pipelines image provides it by default but no the actions one. But looks like we're getting closer, thanks for having a look, it'll be really amazing to move everything out of pipelines, we'll be able to clean a lot of stuff and have more stable CI.

**Comment by matthewmturner** [comment]
Do azp and gha both use the dockerhub `ibisproject/impala` image?

I looked into azp and see the following during build ibis image step:

```
Step 2/13 : RUN apt-get -qq update --yes  && apt-get -qq install --yes --no-install-recommends     build-essential git make clang libboost-dev postgresql-client ca-certificates  && rm -rf /var/lib/apt/lists/*
 ---> Running in 313d6d2762a2
debconf: delaying package configuration, since apt-utils is not installed
```

The point of interest being `libboost-dev`, i believe.  Also, i see conda is installing it.

```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    arrow-cpp-0.15.1           |   py37h982ac2c_6        18.4 MB  conda-forge
    bokeh-2.1.1                |   py37hc8dfbb8_0         6.9 MB  conda-forge
    boost-cpp-1.70.0           |       ha2d47e9_1        21.1 MB  conda-forge
```

Looking at the dockerfile for impala on dockerhub (https://hub.docker.com/r/ibisproject/impala/dockerfile) i dont see it there and dont see it as part of conda install.

Does it need to be fixed in both places?

**Comment by datapythonista** [comment]
I think they both should just that image. I created the actions build recently and never worked, if anything needs to be changed feel free to.

I'm wondering if `boost` needs to be in the docker image with the impala server or in the build directly. In azure we use two nested docker images (3 counting the CI one). What about trying to `apt-get` those packages in a step in the actions build?

**Comment by matthewmturner** [comment]
@datapythonista were getting very close! connected and tests running with just 1 error.

**Comment by matthewmturner** [comment]
Im not entirely sure but it looks like kudu might not be starting based on the new `health-cmd` i added for it.  I see on azp there is a `kudu-master` BACKEND that is run but i dont think that our `setup_env.sh` can handle that currently as kudu isnt in `ci/deps`.

Going to keep digging around - let me know if anything sticks out to you.

**Comment by datapythonista** [comment]
That's great @matthewmturner, good to see some progress.

I think we can create an issue for the kudu problem, and get your improvements here merged, since the problem with kudu seems unrelated to the original issue.

Do you want to clean the diff here so we can merge this, keeping the build still skipped, and open the issue?

I don't know much about kudu, but I can have a look too after this is merged.

**Review by datapythonista — COMMENTED** [review]
Can you remove the blank lines, particularly the ones with spaces, and the prints please?

**Comment by datapythonista** [comment]
Also, if you merge master, the time test should stop failing.

**Review by datapythonista — APPROVED** [review]
Very nice @matthewmturner, thanks for working on this!

**Comment by jreback** [comment]
thanks @matthewmturner

**Pull request merged**
