### PR TITLE
BUG: change clickhouse-driver version to >=0.1.3

### LINKED ISSUE #2088: BUG: load test datasets CI step failed
```Traceback (most recent call last):
  File "/ibis/ci/datamgr.py", line 624, in <module>
    cli(auto_envvar_prefix='IBIS_TEST')
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/ibis/ci/datamgr.py", line 462, in clickhouse
    engine = init_database('clickhouse+native', params, schema)
  File "/ibis/ci/datamgr.py", line 65, in init_database
    recreate_database(driver, new_params, **kwargs)
  File "/ibis/ci/datamgr.py", line 53, in recreate_database
    engine = sa.create_engine(url, **kwargs)
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 479, in create_engine
    return strategy.create(*args, **kwargs)
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 61, in create
    entrypoint = u._get_entrypoint()
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/sqlalchemy/engine/url.py", line 172, in _get_entrypoint
    cls = registry.load(name)
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 237, in load
    return impl.load()
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2444, in load
    self.require(*args, **kwargs)
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2467, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/opt/conda/envs/ibis-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (clickhouse-driver 0.1.1 (/opt/conda/envs/ibis-env/lib/python3.6/site-packages), Requirement.parse('clickhouse-driver>=0.1.2'))
```

### PR DESCRIPTION
**Pull request by anmyachev**
closes #2088

### CODE REVIEW

**Comment by xmnlab** [comment]
@anmyachev just a question, in the issue the error message says: `Requirement.parse('clickhouse-driver>=0.1.2')` ... is there any reason you pinned >=0.1.3?

**Comment by xmnlab** [comment]
@anmyachev you also will need to change https://github.com/ibis-project/ibis/blob/master/setup.py#L29

**Comment by anmyachev** [comment]
> @anmyachev just a question, in the issue the error message says: `Requirement.parse('clickhouse-driver>=0.1.2')` ... is there any reason you pinned >=0.1.3?

I found #2005 which says about incompatibility with version 0.1.2

**Comment by anmyachev** [comment]
> update setup.py as well. pls add a note to the whatsnew and under the clickhouse section in the docs on min requirements

I didn't find clickhouse section place for version update :(

**Comment by anmyachev** [comment]
@jreback  the `clickhouse-driver` version is service information that the ordinary user does not need, unlike the server version(`yandex/clickhouse-server:18.12`). I did not add mention of the driver's changed version, but I think the PR ready for review :)

**Comment by jreback** [comment]
> > update setup.py as well. pls add a note to the whatsnew and under the clickhouse section in the docs on min requirements
> 
> I didn't find clickhouse section place for version update :(

https://docs.ibis-project.org/getting-started.html?highlight=clickhouse#clickhouse-quickstart

add a versionadded tag (1.3), saying that the required versions of clickhouse have now increased to ....

**Comment by jreback** [comment]
great ping on green

**Comment by anmyachev** [comment]
@jreback ping on green

**Comment by jreback** [comment]
thanks @anmyachev

**Pull request merged**
