### PR TITLE
feat(ux): easy interactive setup

### PR DESCRIPTION
**Pull request by cpcloud**
This PR adds an `ibis.interactive` module that is explicitly designed to be star-imported, including the option-setting side-effect, for maximum interactive use convenience.

It is expressly *not* for any kind of production or pipeline use and named in such a way that hopefully makes that obvious.

```
In [4]: from ibis.interactive import *

In [5]: t = ibis.read_json("/data/test/products.jsonl")

In [6]: t
Out[6]:
┏━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┓
┃ sku    ┃ desc                                                                            ┃ baseprice ┃ weight_kg ┃ dims_cm              ┃
┡━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━┩
│ string │ string                                                                          │ float64   │ float64   │ array<float64>       │
├────────┼─────────────────────────────────────────────────────────────────────────────────┼───────────┼───────────┼──────────────────────┤
│ UG27   │ Cellular Modem                                                                  │      3.95 │       2.5 │ [18.2, 6.8, ... +1]  │
│ UG30   │ Mechanical Tuna Crusher                                                         │      3.50 │       3.1 │ [14.4, 14.0, ... +1] │
│ UG50   │ Electric Timer (Puce)                                                           │      4.95 │       2.7 │ [22.1, 16.0, ... +1] │
│ UG68   │ Vintage Blender                                                                 │      3.90 │       2.1 │ [18.7, 13.6, ... +1] │
│ OM16   │ Steel Crusher                                                                   │      2.50 │       3.4 │ [13.6, 12.2, ... +1] │
│ UG75   │ Power Soybean Scale                                                             │      2.90 │       3.5 │ [14.9, 14.8, ... +1] │
│ OM21   │ Bluetooth Keyboard                                                              │      2.50 │       3.5 │ [14.7, 14.5, ... +1] │
│ OM15   │ Pan                                                                             │      2.99 │       3.0 │ [19.3, 12.4, ... +1] │
│ OM58   │ Ultra Mixer (Red)                                                               │      2.99 │       3.3 │ [20.7, 18.9, ... +1] │
│ UG48   │ Network Webcam                                                                  │      2.50 │       3.1 │ [16.4, 13.9, ... +1] │
└────────┴─────────────────────────────────────────────────────────────────────────────────┴───────────┴───────────┴──────────────────────┘
```

### CODE REVIEW

**Review by kszucs — COMMENTED** [review]
LGTM, but going to let others to chime in.

**Review by gforsyth — APPROVED** [review]
I'm a +0.5(?) on this.  
I like the idea, but I have a learned wariness around specifying preferences in code.
That doesn't mean we shouldn't do this, and it's a nice convenience to have, but we should prepare for the inevitable "I'd like each of the named selectors to be available in the top-level interactive mode" issue.  (<-- which isn't a bad thing, but will be where the world-cleaver is between folks that want fewer names imported and those that want everything top-level).

**Comment by cpcloud** [comment]
Yeah, I'm just tired of typing all the things here in every session and live stream.

**Comment by cpcloud** [comment]
Let's see how it goes. I have no problem pushing back on bringing in more names. The goal is to make the one-time interactive boiler plate less, which IMO rules out bringing in all the selectors and everything under `ibis`.

**Pull request merged**
