### PR TITLE
docs: add allowed input for memtable constructor

### LINKED ISSUE #5982: docs: printing a memtable with a map freezes in interactive mode, document allowed input
### What happened?

```
import ibis
ibis.options.interactive = True
t = ibis.memtable({"a": [ibis.map({"a": 1, "b": 2})]})
t
```

Freezes up my Python process and doesn't print anything.

### What version of ibis are you using?

On current master branch.

### What backend(s) are you using, if any?

the default one, so DuckDB?

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by anjakefala**
Closes #5982

### CODE REVIEW

**Comment by cpcloud** [comment]
@anjakefala Does this close an issue? If so, can you add some `Closes #issuenumber` text to the PR desciption?

**Review by cpcloud — COMMENTED** [review]
LGTM!

**Review by cpcloud — APPROVED** [review]

**Comment by anjakefala** [comment]
> @anjakefala Does this close an issue? If so, can you add some Closes #issuenumber text to the PR desciption?

Where is the facepalm emoji as a default emoji react.

**Comment by cpcloud** [comment]
The SQLAlchemy failures have since been fixed, merging!

**Pull request merged**
