### PR TITLE
CI: Pinning pymapd to 0.23 to speed up conda solver

### LINKED ISSUE #2271: Conda takes too long to solve for the CI (again)
Builds in the CI are failing again, apparently conda couldn't solve in one hour (the timeout for builds).

See for example: https://dev.azure.com/ibis-project/ibis/_build/results?buildId=2697&view=logs&j=9e44c89c-30a9-51db-3587-8ac019948434&t=6577b211-5bee-5bb8-9b94-e94e42a9e8f4&l=688

### PR DESCRIPTION
**Pull request by datapythonista**
Closes #2271 

This should speed up conda, from taking more than one hour, to taking 30 minutes. It's still a lot, without pymapd it takes less than 5 minutes. But if this leaves the CI green, probably worth merging while we find a better solution.

### CODE REVIEW

**Comment by jreback** [comment]
I would rather pin <= but let's see if this works, this version changing is really annoying.

**Comment by jreback** [comment]
i think we need to pin the conda build itself first.

**Comment by jreback** [comment]
https://github.com/conda-forge/ibis-framework-feedstock/pull/45 but actually just pin to 0.23

**Comment by datapythonista** [comment]
@jreback, this is green now, and fixes the CI.

I'll have a look later, and see if anything else can be done, the solver is still slower than what I would like. But I'm wondering if the best solution could be to move backends that add too much complexity to separate repos.

**Comment by jreback** [comment]
well
i think we just need to split up more ci jobs - mainly ban pymapd from most of the env files as this is very unstable

**Pull request merged**
