### PR TITLE
Move ClickHouse backend to backends/ directory

### LINKED ISSUE #2418: Move CLICKHOUSE backend to the backends/ directory
**Move the `clickhouse/` backend to `backends/clickhouse`.**

The current Ibis directory structure is a bit confusing, since backends are mixed with core modules. For example, it's not obvious to know if `pandas/` is a backend, or core functionality. Many of the backends live in the root directory, and some are grouped, like in a directory `sql/`. This makes things even harder and difficult to maintain. Also, ibis uses attributes to access the backends (e.g. `ibis.spark.connect`), and `ibis.spark` in code seems to be the `ibis/spark/` module, but it's not, making things confusing, and even creating problems with pytest.

We're moving backends to a standardized structure, in the `backends/` directory, one backend at a time (each backend in a separate pull request). We started by the OmniSciDB backend, and its PR can be a reference for the changes that need to be made here: #2392

The exact tasks to perform are:
- Move the backend from its original location to `backends/` (if the backend is in a subdirectory, like `sql/`, ignore the subdirectory and just have the backend inside `backends/`, so `sql/sqlite/` -> `backends/sqlite`)
- Move the content of `backends/<your-backend>/api.py` to `backends/<your-backend>/__init__.py`. Backends are using `api.py` for historical reasons, but the public backend API should be in the standard `__init__.py` file of the module.
- Update `ibis/__init__.py` so the backend is imported from the new module (`from ibis.<your-backend> import api` -> `from ibis import <your-backend>`)
- Look for places in the code where your backend is being imported, and update the imports. For imports inside the same backend, please use relative imports (e.g. `import ibis.<your-backend>.whatever` -> `import .whatever`). See the reference PR for examples.
- Update the documentation (in `doc/source/backends/<your-backend>.rst`) so the API is generated from the right location.

After performing the changes, the CI should be green, except for the packaging build (which requires changes in the conda-forge feedstock). You can ignore that error, those changes will be performed later for all moved backends.

### PR DESCRIPTION
**Pull request by EdAbati**
As part of the Ibis sprint, I am making this PR that closes #2418

Please let me know if and how I can improve it.

Thanks,

### CODE REVIEW

**Review by datapythonista — COMMENTED** [review]
Thanks @EdAbati looks good. If clickhouse has a page in the docs with an autosummary of its API (I guess it does), you'll need to update to the new path there too.

**Comment by EdAbati** [comment]
Hi @datapythonista ,

I actually checked, but it does not seem to have the autosummary: http://ibis-project.org/docs/backends/clickhouse.html
Do you want me to add it? Probably it will be good for another issue/PR, what do you think?

Also I have noticed that one of the tests (_LinuxTest py38_impala_kudu_clickhouse_) is failing because of:
`ERROR: file or directory not found: ibis/clickhouse/tests`

If I am understanding correctly (I am not super familiar with the ci pipeline), it may be because the clickhouse tests path is hardcoded here:
https://github.com/ibis-project/ibis/blob/8f7c048a6161c0d2712d65b8593147e04b823344/ci/azure/linux.yml#L67

I think I should change this to the new backend location. What do you think?

**Comment by datapythonista** [comment]
> Do you want me to add it? Probably it will be good for another issue/PR, what do you think?

That sounds good. If you want to add it, better a separate PR.


> I think I should change this to the new backend location. What do you think?

That's right, in GitHub Actions the paths are a bit "smarter", but in Azure some are hardcoded. We should be moving everything to GitHub Action soon, but if you can change that path for now, that will be great.

**Review by datapythonista — APPROVED** [review]
Thanks @EdAbati, looks great.

**Comment by EdAbati** [comment]
Thank you very much!:) 

I have also saw that the "Main / Conda package" pipeline failed because of
`Traceback (most recent call last):
  File "/usr/share/miniconda/conda-bld/ibis-framework_1601659577214/test_tmp/run_test.py", line 8, in <module>
    import ibis.clickhouse
ModuleNotFoundError: No module named 'ibis.clickhouse'
`

Not entirely sure where this is coming from instead. Is it something that I should fix or it is a problem with the CI?

**Comment by datapythonista** [comment]
That's expected, needs to be changed in the conda-forge repo independently. We'll do it later.

**Comment by datapythonista** [comment]
@EdAbati CI problems should be fixed now. You'll have to merge master into your branch, and also change the module in https://github.com/ibis-project/ibis/blob/master/ci/recipe/meta.yaml#L64 to get the CI passing (`ibis.clockhouse` -> `ibis.backends.clickhouse`).

**Comment by EdAbati** [comment]
Hi @datapythonista , thank you for letting me know I have made the changes and applied the same suggestion in the other PR #2434 too. It seems that the azure pipeline has the same issues in both PRs. Is something that I should change or help with?

**Comment by datapythonista** [comment]
Looks like azure was having some issues, let's see if now we get a green build.

**Comment by jreback** [comment]
i guess this is fine, but we aren't running the tests, so hard to tell.

**Comment by jreback** [comment]
thanks @EdAbati

**Comment by datapythonista** [comment]
> i guess this is fine, but we aren't running the tests, so hard to tell.

Afaik the clickhouse tests are running in azure with the impala build.

**Comment by EdAbati** [comment]
Thank you both. :)
@datapythonista now that this is merged, I will make another PR on the documentation autosummary discussed above.

**Pull request merged**
