### PR TITLE
[MapD] Resolves Joining with different column names

### LINKED ISSUE #1619: MapD : ibis.common.TranslationError: Joining on different column names is not supported
```
>>> expr = tb10.num == tb12.id
>>> join = tb10.left_join(tb12, expr)
>>> join.execute()
Return Error : 
  File "/home/sw/anaconda3/lib/python3.6/site-packages/ibis/mapd/compiler.py", line 167, in _validate_join_predicates
    'Joining on different column names is not supported'
ibis.common.TranslationError: Joining on different column names is not supported

>>> join.materialize().execute()
  File "/home/sw/anaconda3/lib/python3.6/site-packages/ibis/mapd/compiler.py", line 167, in _validate_join_predicates
    'Joining on different column names is not supported'
ibis.common.TranslationError: Joining on different column names is not supported

>>> join.materialize().schema()
ibis.Schema {
  num     int32
  txt     string
  id      int32
  letter  string
}
```
```
--------------- tb10
   num txt
0    1   a
1    2   b
2    3   c
--------------- tb12
   id letter
0   1      a
1   3      c
2   3      c
```

Backend=MapD    MapD=4.1.1    ibis=0.14    Python=3.6
Ubuntu=18.04    Anaconda=5.1

### LINKED ISSUE #1620: MapD  bucket() : MapD backend doesn't support <class 'ibis.expr.operations.NullLiteral'> operation!
`>>> buckets = [0, 1, 3]`
`>>> bucketed = table.price_col.bucket(buckets).name('bucket')`
`>>> bucketed.value_counts().execute()`
return error : 
  File "/home/sw/anaconda3/lib/python3.6/site-packages/ibis/mapd/operations.py", line 365, in raise_unsupported_op_error
    raise com.UnsupportedOperationError(msg.format(type(op)))
ibis.common.UnsupportedOperationError: MapD backend doesn't support <class 'ibis.expr.operations.NullLiteral'> operation!

Backend=MapD    MapD=4.1.1    ibis=0.14    Python=3.6
Ubuntu=18.04    Anaconda=5.1

### PR DESCRIPTION
**Pull request by xmnlab**
Fixes #1619

### CODE REVIEW

**Comment by cpcloud** [comment]
@xmnlab I will fix the null type issue in a different PR. Basically, we need to cast the null in the case statement to the results type so that there isn't an untyped null hanging around.

**Comment by xmnlab** [comment]
@cpcloud thank you so much! If you can ping me in the PR, please ... I really want to learn how to do this :)
I will remove the literal null changes in this PR.

**Comment by cpcloud** [comment]
@xmnlab Can you add a test for this?

**Comment by cpcloud** [comment]
@xmnlab Can you rebase and push all of your PRs?

**Comment by xmnlab** [comment]
@cpcloud sure! I am working on that! thanks!

**Comment by xmnlab** [comment]
it raised a error for maiadb installation on windows+py36

```
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://downloads.mariadb.org/f/mariadb-10.2.14/winx64-packages/mariadb-10.2.14-winx64.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (403) Forbidden."
2018-10-23T02:19:58.6711299Z The install of mariadb was NOT successful.
```

**Comment by xmnlab** [comment]
azure pipelines is still raising error on windows_test py35 for mariadb:

```
2018-10-25T16:51:17.8292526Z Downloading mariadb 64 bit
2018-10-25T16:51:17.8293327Z   from 'https://downloads.mariadb.org/f/mariadb-10.2.14/winx64-packages/mariadb-10.2.14-winx64.msi'
2018-10-25T16:51:20.3065302Z ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://downloads.mariadb.org/f/mariadb-10.2.14/winx64-packages/mariadb-10.2.14-winx64.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (403) Forbidden."
2018-10-25T16:51:20.6532187Z The install of mariadb was NOT successful.
2018-10-25T16:51:20.6551619Z Error while running 'C:\ProgramData\chocolatey\lib\mariadb\tools\chocolateyInstall.ps1'.
2018-10-25T16:51:20.6551954Z  See log for details.
2018-10-25T16:51:22.7495596Z 
2018-10-25T16:51:22.7496068Z Chocolatey installed 0/1 packages. 1 packages failed.
2018-10-25T16:51:22.7496140Z  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
2018-10-25T16:51:22.7505864Z 
2018-10-25T16:51:22.7511324Z Failures
2018-10-25T16:51:22.7518311Z  - mariadb (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\mariadb\tools\chocolateyInstall.ps1'.
2018-10-25T16:51:22.7518456Z  See log for details.
2018-10-25T16:51:23.5270254Z ##[error]Cmd.exe exited with code '404'.
```

**Comment by cpcloud** [comment]
@xmnlab can your resolve the merge conflicts? i will merge after that.

**Comment by xmnlab** [comment]
rebased! thanks @cpcloud !

**Pull request closed without merging**
