### PR TITLE
ENH: [OmniSciDB] Add/Enable supported OmniSciDB operations

### PR DESCRIPTION
**Pull request by fexolm**
These operations are suported in current omnisci release.

### CODE REVIEW

**Comment by xmnlab** [comment]
hey @fexolm could you rebase your code on top of master?

**Comment by xmnlab** [comment]
hey @fexolm thanks for working on that! 
could you rebase your code on top of master?

**Comment by fexolm** [comment]
@xmnlab done, sorry for the delay. I've missed notification somehow :)

**Comment by xmnlab** [comment]
@fexolm it seems there still are some issues. 
as your logs are not available anymore could you rebase again on top of master ?
thanks!

also feel free to join us on ibis gitter channel https://gitter.im/ibis-dev/Lobby

**Pull request closed without merging**
