### PR TITLE
FEAT: Add window ops support to SQLite

### LINKED ISSUE #2231: ENH: Add support for window operation to ibis.sqlite
Currently ibis.sqlite doesn't support window operations but sqlite supports such functions (https://www.sqlitetutorial.net/sqlite-window-functions/).

### PR DESCRIPTION
**Pull request by xmnlab**
This PR adds window operations support to SQLite

Resolve #2231

### CODE REVIEW

**Comment by xmnlab** [comment]
this PR is ready for review. thanks!

**Comment by xmnlab** [comment]
`ibis-project.ibis (LinuxTest py38_impala_kudu_clickhouse)` tests passed. but `Publish Linux environment YAML to Azure` raised an error:

```
Information, ApplicationInsightsTelemetrySender correlated 2 events with X-TFS-Session dba36af5-380b-4393-8afc-9018370188b1
##[error]Artifact LinuxCondaEnvironment-38-main already exists for build 2597.
Finishing: Publish Linux environment YAML to Azure
```

probably it is not a block for review or merge.

it is ready again for review. thanks!

**Comment by xmnlab** [comment]
thanks @icexelloss ! branch rebased.

**Comment by jreback** [comment]
thanks @xmnlab

**Pull request merged**
