### PR TITLE
fix(clickhouse): register in-memory tables in pyarrow-related calls

### PR DESCRIPTION
**Pull request by cpcloud**
Fixes a bug where memtables were not being registered before calling `to_pyarrow` et al.

### CODE REVIEW

**Review by gforsyth — APPROVED** [review]
:shipit:

**Comment by kszucs** [comment]
Is there a reproducer test case?

**Comment by cpcloud** [comment]
These both fail for me locally without this change:

```
FAILED ibis/backends/tests/test_export.py::test_to_pyarrow_batches_memtable[clickhouse] - clickhouse_driver.dbapi.errors.OperationalError: Code: 60.
FAILED ibis/backends/tests/test_export.py::test_to_pyarrow_memtable[clickhouse] - clickhouse_driver.dbapi.errors.OperationalError: Code: 60.
```

**Comment by cpcloud** [comment]
I don't have a great idea of why this wasn't failing on `master`

**Comment by cpcloud** [comment]
Ah, it's not failing because we don't install `pyarrow` in the clickhouse CI jobs so the test is skipped.

We avoid installing pyarrow to avoid inadvertently introducing a dependency on it.

**Comment by kszucs** [comment]
Shall we have another build including pyarrow then?

**Comment by cpcloud** [comment]
Sure, what's one more build between colleagues!

**Pull request merged**
