### PR TITLE
WIP: Move pandas backend to backends/ directory

### LINKED ISSUE #2423: Move PANDAS backend to the backends/ directory
**Move the `pandas/` backend to `backends/pandas`.**

The current Ibis directory structure is a bit confusing, since backends are mixed with core modules. For example, it's not obvious to know if `pandas/` is a backend, or core functionality. Many of the backends live in the root directory, and some are grouped, like in a directory `sql/`. This makes things even harder and difficult to maintain. Also, ibis uses attributes to access the backends (e.g. `ibis.spark.connect`), and `ibis.spark` in code seems to be the `ibis/spark/` module, but it's not, making things confusing, and even creating problems with pytest.

We're moving backends to a standardized structure, in the `backends/` directory, one backend at a time (each backend in a separate pull request). We started by the OmniSciDB backend, and its PR can be a reference for the changes that need to be made here: #2392

The exact tasks to perform are:
- Move the backend from its original location to `backends/` (if the backend is in a subdirectory, like `sql/`, ignore the subdirectory and just have the backend inside `backends/`, so `sql/sqlite/` -> `backends/sqlite`)
- Move the content of `backends/<your-backend>/api.py` to `backends/<your-backend>/__init__.py`. Backends are using `api.py` for historical reasons, but the public backend API should be in the standard `__init__.py` file of the module.
- Update `ibis/__init__.py` so the backend is imported from the new module (`from ibis.<your-backend> import api` -> `from ibis import <your-backend>`)
- Look for places in the code where your backend is being imported, and update the imports. For imports inside the same backend, please use relative imports (e.g. `import ibis.<your-backend>.whatever` -> `import .whatever`). See the reference PR for examples.
- Update the documentation (in `doc/source/backends/<your-backend>.rst`) so the API is generated from the right location.

After performing the changes, the CI should be green, except for the packaging build (which requires changes in the conda-forge feedstock). You can ignore that error, those changes will be performed later for all moved backends.

### PR DESCRIPTION
**Pull request by joy-rosie**
Closes #2423

### CODE REVIEW

**Comment by joy-rosie** [comment]
@datapythonista should I be using relative imports inside the tests as well for ibis/pandas?

**Comment by datapythonista** [comment]
> @datapythonista should I be using relative imports inside the tests as well for ibis/pandas?

For the tests inside the backend yes, please. The idea is that if eventually we want to move a backend to a separate repo (and we probably will move at least couple), all imports in it are relative and we don't need to change paths.

**Comment by joy-rosie** [comment]
@datapythonista , I am a bit confused about the failures on the last commit, how do I debug them?

**Comment by datapythonista** [comment]
I see this in the logs: `ERROR: file or directory not found: ibis/pandas/tests`. Looks like you need to update a path, not sure where, `grep` should tell you.

**Comment by datapythonista** [comment]
The errors of the Windows build seem genuine errors of this PR. Not sure what the cause:
```
self = <dispatched execute>
args = (IntervalMultiply[interval<int16>(unit='D')]
  left:
    Literal[interval<int8>(unit='D')]
      1
  right:
    Literal[int8]
      3,)
kwargs = {}, types = (<class 'ibis.expr.types.IntervalScalar'>,), func = None

    def __call__(self, *args, **kwargs):
        types = tuple([type(arg) for arg in args])
        try:
            func = self._cache[types]
        except KeyError:
            func = self.dispatch(*types)
            if not func:
>               raise NotImplementedError(
                    'Could not find signature for %s: <%s>' %
                    (self.name, str_signature(types)))
E               NotImplementedError: Could not find signature for execute: <IntervalScalar>
```

**Comment by joy-rosie** [comment]
Thanks for the heads up, for some reason the local package ibis/backends/pandas is being import where `import pandas as pd`

I am looking into it

**Pull request closed without merging**
