### PR TITLE
refactor(ir): remove unused lineage `roots` and `find_nodes` functions

### PR DESCRIPTION
**Pull request by kszucs**
BREAKING CHANGE: removed `ibis.expr.lineage.{roots,find_nodes}` functions

### CODE REVIEW

**Review by cpcloud — APPROVED** [review]

**Comment by cpcloud** [comment]
Nice work! Merging.

**Comment by cpcloud** [comment]
@icexelloss We can revert, or if you'd be okay copying this out then we can avoid reverting.

The main reason was that this code isn't being used anywhere in the codebase.

**Comment by gerrymanoim** [comment]
Let me see if I can rewrite the equivalents via `traverse`.

**Comment by icexelloss** [comment]
@cpcloud Gotcha. Don't think we necessarily need to revert because it's a small thing (worst case we just copy the code)

But IMO `lineage` is a semi-public/util API that people might just need to inspect their ibis trees.

**Pull request merged**
