### PR TITLE
chore: master -> main in relevant places throughout

### LINKED ISSUE #7683: rename `master` branch to `main`
see linked discussion. we need to update GitHub Actions, documentation, and perhaps other places in the repo before making this change. we could/should keep the `master` branch around (and synced w/ `main` if not difficult) 

---

should we make this change? particularly as ibis-substrait, ibisml, ibis-birdbrain, and any future projects in the org will default to main. any reason not to switch over at this point? GitHub should do a decent job at redirects and everything

_Originally posted by @lostmygithubaccount in https://github.com/ibis-project/ibis/discussions/3460#discussioncomment-7139143_

### PR DESCRIPTION
**Pull request by lostmygithubaccount**
## Description of changes

manually update "master" to "main" for all relevant instances to change the default branch for the repo

## Issues closed

closes #7683 (with additional change by an admin for the default branch)

### CODE REVIEW

**Review by cpcloud — APPROVED** [review]

**Comment by lostmygithubaccount** [comment]
not sure why the CI isn't running -- I did accidentally create this branch in the upstream repo instead of my fork

**Comment by cpcloud** [comment]
It's not running because we don't actually have a `main` branch yet!

**Comment by cpcloud** [comment]
I created one. Can you retarget the base branch to `main`?

**Comment by cpcloud** [comment]
Actually I did it

**Comment by cpcloud** [comment]
I can help update the docs

**Pull request merged**
