### PR TITLE
FEAT: Add ST_START_POINT and ST_END_POINT to PostGIS backend

### PR DESCRIPTION
**Pull request by ian-r-rose**
This adds a couple of missing geospatial operations to the PostGIS backend.

### CODE REVIEW

**Comment by xmnlab** [comment]
@ian-r-rose maybe the tests errors are related to the different approach of the 2 backends. IIRC OmniSciDB, for example, doesn't recognize that a geometry contains a point that touch the border ... and PostGreSQL recognize it. So maybe the data tests need to be changed to some data that don't touch the border.

**Comment by xmnlab** [comment]
but not sure yet if it is the case ... I would need to investigate that

**Comment by ian-r-rose** [comment]
Yeah, it seems it is some issue with the way the two backends handle
boundaries. I'll take a closer look.

**Comment by xmnlab** [comment]
@ian-r-rose I am talking to the OmniSci team to check this issue.

**Comment by ian-r-rose** [comment]
Thanks @xmnlab!

**Comment by datapythonista** [comment]
@xmnlab, @ian-r-rose is this still active?

If it is, can you please add a release note, and merge master?

**Comment by ian-r-rose** [comment]
Hi @datapythonista, sorry, missed your note. Yes, I can update this PR.

**Comment by datapythonista** [comment]
Thanks @ian-r-rose. Do you mind adding a release note in https://github.com/ibis-project/ibis/blob/master/docs/source/release/index.rst please? And also merge master again? We've got some problems with the CI that should be fixed now. Thanks!

**Comment by datapythonista** [comment]
@ian-r-rose do you have time to add the release note and merge master?

**Comment by ian-r-rose** [comment]
@datapythonista I'm remembering why this stalled in the first place -- there are some apparent differences in how the omniscidb geo functionality works and how postgis works with respect to boundary points.  I was initially unable to find a test that worked for both of them.

Probably the best thing to do is to have separate tests for those two backends.

**Comment by datapythonista** [comment]
If the difference is small, and it's just in the cases where the point is in the boundary, I think we can have a single test with an `if`. Otherwise I guess we'll be duplicating code.

In any case, that doesn't sound as a major blocker, I think should be easy to implement. Can you take care of it? Thanks!

**Comment by datapythonista** [comment]
@ian-r-rose do you still want to move forward with this?

**Comment by ian-r-rose** [comment]
@datapythonista I'm interested in getting this wrapped up, but I must say, I am having a really tough time getting the new test suite setup working. Is it documented anywhere?

**Comment by datapythonista** [comment]
> @datapythonista I'm interested in getting this wrapped up, but I must say, I am having a really tough time getting the new test suite setup working. Is it documented anywhere?

Good point. Things didn't change much, and there is still some refactoring pending, but you should be able to run tests for postgres with `PYTEST_BACKENDS="postgres" python -m pytest -m "not hdfs and not udf" ibis/tests ibis/expr/tests`

**Review by jreback — CHANGES_REQUESTED** [review]
lgtm. can you add a release note; pls ping on green.

**Comment by ian-r-rose** [comment]
Thanks @datapythonista and @jreback 

All green except for one skipped backend that seems to be unrelated.

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
thanks @ian-r-rose

**Pull request merged**
