### PR TITLE
[MapD] Cast to float

### LINKED ISSUE #1682: Cast to float in OmniSci
For using `floor` with omnisci, sometimes we need to cast literals to `float` in omnisci, see https://github.com/omnisci/mapd-core/issues/305#issuecomment-450295257

However I can figure out how to get ibis to produce SQL like `CAST(-124.39000000000038 AS FLOAT)`. 

If I use `ibis.literal(x_min, 'float32').cast('float64')` I get `CAST(-124.39000000000038 AS NUMERIC)`.

And if I use the opposite `ibis.literal(x_min, 'float64').cast('float32')` I get `CAST(-124.39000000000038 AS REAL)`.

Is it possible to change how OmniSci does the casting?

### PR DESCRIPTION
**Pull request by xmnlab**
Resolves #1682

### CODE REVIEW

**Comment by cpcloud** [comment]
@xmnlab I've put up #1738 to address the BigQuery auth issues.

**Comment by xmnlab** [comment]
awesome! thank you so much @cpcloud !

**Comment by cpcloud** [comment]
@xmnlab Can you rebase?

**Comment by xmnlab** [comment]
rebase done!

**Comment by cpcloud** [comment]
It looks like I didn't fix the auth stuff. I know why, putting up a PR.

**Comment by xmnlab** [comment]
@cpcloud thanks!

**Comment by cpcloud** [comment]
Ah actually there appear to be a few cases where I call `ibis.bigquery.connect` without checking for credentials first.

**Comment by cpcloud** [comment]
@xmnlab Can you cherry-pick from https://github.com/ibis-project/ibis/pull/1741 and see if that fixes the CI for you?

**Comment by xmnlab** [comment]
@cpcloud awesome! thanks I will do it!

**Comment by xmnlab** [comment]
I am trying your changes on https://github.com/ibis-project/ibis/pull/1683

**Comment by xmnlab** [comment]
@cpcloud @kszucs it seems it is done for review :)

**Comment by cpcloud** [comment]
@xmnlab LGTM! Merging.

**Pull request closed without merging**
