### PR TITLE
Collection of doc fixes

### PR DESCRIPTION
**Pull request by anjakefala**
I am going through the tutorial, and going to collect any fixes to the documentation here. Feel free to review and merge at any point. I will just continue collecting things in this branch, and open a new PR.

Fix 1:
Change broken link https://ibis-project.org/backends/SQLite/#install
to https://ibis-project.org/docs/latest/backends/SQLite/#install

### CODE REVIEW

**Comment by anjakefala** [comment]
Why does `codecov` not like me.

**Comment by cpcloud** [comment]
@anjakefala This should already be fixed in the `dev` docs. Probably best to start from there when looking for doc bugs 😄

**Comment by anjakefala** [comment]
> This should already be fixed in the dev docs. Probably best to start from there when looking for doc bugs

Ah, good to know!

Do we want to change the edit button on the website (top right, underneath the GitHub widget) to point to the `dev` branch?

**Comment by cpcloud** [comment]
> > This should already be fixed in the dev docs. Probably best to start from there when looking for doc bugs
> 
> Ah, good to know!
> 
> Do we want to change the edit button on the website (top right, underneath the GitHub widget) to point to the `dev` branch?

Yeah, that sounds like a great idea.

**Pull request closed without merging**
