### PR TITLE
ci(dev-tools): add PR title and body linter to verify conventional commits and allow squash merges

### LINKED ISSUE #6549: feat: squash merges on PRs
### Is your feature request related to a problem?

After some internal discussion, opening this issue for tracking. There were recently 2 issues with PRs due to the requirement to squash commits into a single commit, which can be a more complicated git operation (edit: adding a third more recent example, certainly others): 

1. https://github.com/ibis-project/ibis/pull/6543
2. https://github.com/ibis-project/ibis/pull/6460#issuecomment-1594987395
3. https://github.com/ibis-project/ibis/pull/7804

It would be easier to accept PRs if this requirement were removed. We should enable PR squash merge on GitHub. This likely involves some work to ensure the changelog and everything else works as expected.

### Describe the solution you'd like

As a user, I can simply push commits to a PR and have it merged without a rebase or other more advanced git operations.

### What version of ibis are you running?

n/a

### What backend(s) are you using, if any?

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by cpcloud**
Adapt the https://github.com/substrait-io/substrait-python/blob/main/.github/workflows/pr_title.yml workflow for our needs, so that we can allow squash merges.

Closes #6549.

### CODE REVIEW

**Comment by gforsyth** [comment]
The one thing I want to figure out here is how to disable conventional commits caring about line length in the commit body.  It's been very confusing for me when I'm failing the commit lint and it's because I need to manually insert some line breaks in the PR description.

Trying to find where the conventional commits configuration reference lives...

**Comment by cpcloud** [comment]
I think it's here: https://www.npmjs.com/package/@commitlint/config-conventional#body-max-line-length

which should be configurable in our `.commitlintrc.json`

We have it set to 1000 right now. I **think** that should be sufficient, but we can always disable it entirely.

```
    "body-max-line-length": [2, "always", 1000],
```

**Comment by gforsyth** [comment]
Oh, sweet, that's plenty.

**Review by gforsyth — APPROVED** [review]
:shipit:

**Pull request merged**
