### PR TITLE
Codecov setup

### LINKED ISSUE #1444: Setup code coverage integration
@cpcloud what do You think?

### PR DESCRIPTION
**Pull request by kszucs**
resolves #1444 

uploading requires a circleci env variable `CODECOV_TOKEN=<token>` which is generated after adding `ibis-project/ibis` on codecov

### CODE REVIEW

**Comment by kszucs** [comment]
2.7 segfaults somewhy, I'll investigate it...

**Comment by cpcloud** [comment]
According to this link we don't need to set the token: https://docs.codecov.io/docs/about-the-codecov-bash-uploader#section-upload-token

Is that inconsistent with something else you read @kszucs

**Comment by kszucs** [comment]
That's inconsistent with I've experienced. Without the token it instantly complains about it. For uploading the token is mandatory.

**Comment by kszucs** [comment]
@cpcloud Great, thanks! How about a codecov badge into the readme?

**Comment by cpcloud** [comment]
Sounds good! Feel free to add to this PR or another one

**Comment by cpcloud** [comment]
@kszucs Can you rebase on top of master?

**Comment by kszucs** [comment]
@cpcloud done

**Comment by cpcloud** [comment]
@kszucs Just merged the 2.7 PR (#1514). Can you rebase?

**Comment by cpcloud** [comment]
@kszucs Actually, no need to rebase. This is fine.

**Comment by cpcloud** [comment]
Thanks @kszucs!

**Pull request closed without merging**
