### PR TITLE
fix: handle NULLs consistently in String.concat()

### PR DESCRIPTION
**Pull request by NickCrews**
Partially fixes https://github.com/ibis-project/ibis/issues/8302.
Still need to make pandas actually handle NULLs at all.

### CODE REVIEW

**Comment by NickCrews** [comment]
Actually, is this going to just get made outdated by `the-epic-split`? Maybe we should wait for that to land before fixing this up. It would also be great if a core dev could finish this up: since I don't have the creds for all the backends, I can only test some backends by submitting them to CI. I think it should be obvious what needs to happen.

**Comment by cpcloud** [comment]
This seems to be a postgres-specific behavior that duckdb inherited.

ClickHouse, Trino and BigQuery all propagate nulls.

**Comment by cpcloud** [comment]
Agree that we should revisit this after `the-epic-split` is merged which will very likely be this upcoming week.

**Comment by cpcloud** [comment]
I put up #8305 instead, against `the-epic-split`

**Comment by cpcloud** [comment]
I'll cherry pick your tests and examples over to that PR, thanks!

**Pull request closed without merging**
