### PR TITLE
feat(polars): support version 1.0 and later

### PR DESCRIPTION
**Pull request by cpcloud**
Support Polars 1.0 and set lower bound to 1.0. There are many behavioral changes in Polars 1.0, such that it makes it difficult to justify supporting so many older versions. I say we cut losses and jump to 1.0 as the lower bound.

### CODE REVIEW

**Comment by cpcloud** [comment]
Core dump reported upstream in https://github.com/pola-rs/polars/issues/17425.

**Comment by chloeh13q** [comment]
p.s. probably want to update the conda env files too - they're not upper bounded right now and I was running into problems when I updated my environment, but since this is going in soon (I think?) maybe we can just directly bump it to 1.+ there too instead of having an intermediary change?

**Comment by cpcloud** [comment]
@chloeh13q Yep, thanks!

**Review by gforsyth — APPROVED** [review]
:shipit:

**Pull request merged**
