### PR TITLE
docs: add Polars SQL example to why article

### PR DESCRIPTION
**Pull request by lostmygithubaccount**
## Description of changes

add Polars SQL example to the Why Ibis concept article after https://github.com/ibis-project/ibis/pull/8528

for some reason, this is failing on `docs-preview` locally but works fine for my locally otherwise. opening the PR to see if issues in CI

### CODE REVIEW

**Comment by lostmygithubaccount** [comment]
failure is:

```python
  Cell 16/22: ''...ERROR: 

An error occurred while executing the following cell:
------------------
con = ibis.polars.connect()
t = con.read_parquet("penguins.parquet")
g = t.alias("penguins").sql(sql)
g
------------------


---------------------------------------------------------------------------
ComputeError                              Traceback (most recent call last)
Cell In[16], line 3
      1 con = ibis.polars.connect()
      2 t = con.read_parquet("penguins.parquet")
----> 3 g = t.alias("penguins").sql(sql)
      4 g

File ~/repos/ibis/ibis/expr/types/relations.py:3320, in Table.sql(self, query, dialect)
   3317     name = util.gen_name("sql_query")
   3318     expr = self
-> 3320 schema = backend._get_sql_string_view_schema(name, expr, query)
   3321 node = ops.SQLStringView(child=self.op(), query=query, schema=schema)
   3322 return node.to_expr()

File ~/repos/ibis/ibis/backends/polars/__init__.py:420, in Backend._get_sql_string_view_schema(self, name, table, query)
    415 parsed = parsed.with_(
    416     sg.to_identifier(name, quoted=True), as_=cte, dialect=self.dialect
    417 )
    419 sql = parsed.sql(self.dialect)
--> 420 return self._get_schema_using_query(sql)

File ~/repos/ibis/ibis/backends/polars/__init__.py:423, in Backend._get_schema_using_query(self, query)
    422 def _get_schema_using_query(self, query: str) -> sch.Schema:
--> 423     return PolarsSchema.to_ibis(self._context.execute(query).schema)

File ~/repos/ibis/venv/lib/python3.11/site-packages/polars/sql/context.py:268, in SQLContext.execute(self, query, eager)
    190 def execute(self, query: str, eager: bool | None = None) -> LazyFrame | DataFrame:
    191     """
    192     Parse the given SQL query and execute it against the registered frame data.
    193 
   (...)
    266     └────────┴─────────────┴─────────┘
    267     """
--> 268     res = wrap_ldf(self._ctxt.execute(query))
    269     return res.collect() if (eager or self._eager_execution) else res

ComputeError: relation 'penguins' was not found
```

but it works just fine for me:

```python
[ins] In [1]: import ibis

[ins] In [2]: ibis.options.interactive = True

[ins] In [3]: con = ibis.polars.connect()

[ins] In [4]: t = ibis.read_parquet("docs/penguins.parquet")

[ins] In [5]: sql = """
         ...: SELECT
         ...:   species,
         ...:   island,
         ...:   COUNT(*) AS count
         ...: FROM penguins
         ...: GROUP BY species, island
         ...: """.strip()

[ins] In [6]: g = t.alias("penguins").sql(sql)

[ins] In [7]: g
Out[7]: 
┏━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━┓
┃ species   ┃ island    ┃ count ┃
┡━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━┩
│ string    │ string    │ int64 │
├───────────┼───────────┼───────┤
│ Adelie    │ Torgersen │    52 │
│ Adelie    │ Biscoe    │    44 │
│ Adelie    │ Dream     │    56 │
│ Gentoo    │ Biscoe    │   124 │
│ Chinstrap │ Dream     │    68 │
└───────────┴───────────┴───────┘
```

**Comment by lostmygithubaccount** [comment]
same failure in CI, odd

**Comment by cpcloud** [comment]
Your example doesn't use the polars backend, it's using duckdb by default.

You need to run `ibis.set_backend(con)`

**Comment by cpcloud** [comment]
Polars SQL support doesn't include support for quoted identifiers at the moment so `.sql` is extremely limited in value there: we quote every identifier.

**Comment by lostmygithubaccount** [comment]
ah yep that should have been `con.read_parquet`, and the same failure. I'll just close this for now

**Pull request closed without merging**
