### PR TITLE
FIX: refresh list of supported and unsupported operations for omnisci

### PR DESCRIPTION
**Pull request by dchigarev**
- **Log2 and Log**: Ibis supports `Log2` and `Log` for omnisci backend, but for some reasons that operations are still in unsupported list
- **Hash**: `Hash` does not supported for omnisci backend, enabled in related list
- **IdenticalTo**: works via `Impala` implementation, had been enabled and passed `test_generic.py::test_identical_to`

### CODE REVIEW

**Comment by dchigarev** [comment]
@xmnlab PR is ready for review

**Comment by datapythonista** [comment]
@dchigarev can you merge master and update this PR please? We've got the CI working now, including the omnisci tests. If this is still green it should be ready to get merged.

**Comment by dchigarev** [comment]
@datapythonista and the CI is still green

**Comment by xmnlab** [comment]
@datapythonista thanks for pointing me here! as it is adding new operations it needs a release note.

@dchigarev thanks for working on that.

identical_to implementation was started on https://github.com/ibis-project/ibis/pull/2112 by @semelianova ... but probably it is not a problem to move it forward here.

I will check the tests .. but I think they are triggered on `all` tests .. so it should be fine.

**Comment by xmnlab** [comment]
@dchigarev it seems it is missing just the test for hash. could you add a test for that? I think it should be inside`ibis/tests/all/test_generic.py` 

let me know if you need any extra information. thanks for working on that.

**Comment by jreback** [comment]
does this need a release note?

**Comment by xmnlab** [comment]
in the other PRs that we added support for operations in a backend we added release note ... maybe from an user perspective it would be good to have this information ... but no objection if is not necessary

**Comment by dchigarev** [comment]
It seems that new tests helped to find the bug in Impala hash implementation.
As we see in CI tests output:
```
expr = Hash[int64]
  Literal[int64]
    0
  how:
    fnv
expected = -2611523532599129963

>       assert con.execute(expr) == expected
E       assert 2062021750465500607 == -2611523532599129963
```
test fails in one particular case, when we're trying to hash int 0, but getting hash value of `False`.
Other test cases seems to pass right.

**Comment by datapythonista** [comment]
Can you move the test to a new PR please? I think we can merge the rest, and have a look at that separetly

**Comment by xmnlab** [comment]
maybe would be good to just skip the test for impala and keep the test here

**Comment by dchigarev** [comment]
> maybe would be good to just mark it as xfail the test for impala and keep the test here

... and create an issue about it

**Comment by dchigarev** [comment]
created issue for that bug #2220

**Comment by datapythonista** [comment]
@dchigarev CI is red, and you've got conflicts. Can you have a look please?

**Comment by datapythonista** [comment]
Closing as stale. @dchigarev if you want to continue working on this, please let me know, happy to reopen the PR.

**Pull request closed without merging**
