### PR TITLE
feat: allow construction of decimal literals

### PR DESCRIPTION
**Pull request by cpcloud**
This PR allows the construction of decimal literals from strings, integers and decimal.Decimal objects. It will correctly adjust scale of the input depending the passed datatype

### CODE REVIEW

**Comment by kszucs** [comment]
@cpcloud there is a failing impala test.

**Comment by cpcloud** [comment]
@kszucs Yep, I'm probably going to delay the string -> decimal support for now, until we can remove the impala UDF support.

**Comment by cpcloud** [comment]
@jreback Mind reviewing this?

**Review by jreback — APPROVED** [review]
lgtm

**Pull request merged**
