### PR TITLE
docs: how-to bfill and ffill

### PR DESCRIPTION
**Pull request by p-a-a-a-trick**
- docs: added how to bfill and ffill
- docs: updated how to guide
- docs: blog addition how to trim

### CODE REVIEW

**Comment by gforsyth** [comment]
Hey @p-a-a-a-trick -- I think this will work for excluding the `duckdb://:memory:` from being picked up by the link checker:

```patch
From 0e296f022ee4cd865fc84dc5db2c04af5b2c3e25 Mon Sep 17 00:00:00 2001
From: Gil Forsyth <gil@forsyth.dev>
Date: Wed, 31 Aug 2022 12:07:07 -0400
Subject: [PATCH] chore: add exclude rule for duckdb connect string

---
 justfile | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/justfile b/justfile
index 1acf9821..1f8e7c09 100644
--- a/justfile
+++ b/justfile
@@ -83,4 +83,4 @@ checklinks *args:
                         -or -wholename 'site/user_guide/design/index.html' \
                         -or -wholename 'site/overrides/main.html' \
                         -or -wholename 'site/blog/Ibis-version-3.1.0-release/index.html' \) \))
-    lychee "${files[@]}" --base site --require-https {{ args }}
+    lychee "${files[@]}" --base site --require-https {{ args }} --exclude "duckdb:/:memory"
-- 
2.37.1
```

**Comment by jcrist** [comment]
Instead of excluding specific urls (which we'll probably have more of going forward as `ibis.connect` makes its way into the docs), can we instead only check links starting with `https://`?

**Comment by gforsyth** [comment]
> Instead of excluding specific urls (which we'll probably have more of going forward as `ibis.connect` makes its way into the docs), can we instead only check links starting with `https://`?

`lychee` dumps out a bunch of `file://` links from all of the generated html -- I don't know how important or useful it is to check all of those, though.

**Comment by jcrist** [comment]
I don't have lychee installed locally to try it, but `-s file -s http -s https` might work? Presumably `file` links are internal relative links?

**Comment by gforsyth** [comment]
> Presumably `file` links are internal relative links?

they are, but the offending link here is a `file://` link:
```xonsh
🐚  lychee 'site/blog/ffill-and-bfill-using-ibis/' --dump | grep ":/:"
file:///home/gil/github.com/ibis-project/ibis/site/blog/ffill-and-bfill-using-ibis/duckdb:/:memory
```

if we're comfortable just checking external links, I think `-s http -s https` would do the trick

**Comment by gforsyth** [comment]
Yeah, `prettier` wants to reformat your markdown file.  The output in CI is distinctly unhelpful but if you run `pre-commit run --all-files` (or `prettier --check docs`) you'll get an output where the files that would be changed are highlighted.
Then you can run `prettier path/to/that/file` to update it (in this case, it's the `ffill-and-bfill-using-ibis.md` file)

**Comment by cpcloud** [comment]
I fixed this up and rebased it, should be good to merge once CI is green.

**Review by cpcloud — APPROVED** [review]

**Comment by p-a-a-a-trick** [comment]
> Yeah, `prettier` wants to reformat your markdown file. The output in CI is distinctly unhelpful but if you run `pre-commit run --all-files` (or `prettier --check docs`) you'll get an output where the files that would be changed are highlighted.
> 
> ```shell
> prettier -c docs
> Checking formatting...
> [warn] docs/blog/ffill-and-bfill-using-ibis.md
> [warn] Code style issues found in the above file. Forgot to run Prettier?
> ```
> 
> Then you can run `prettier -w path/to/that/file` to update it (in this case, it's the `ffill-and-bfill-using-ibis.md` file)
> 
> Also, be careful with that `-w` flag since it writes changes in place

Definitely missed this comment.  Thanks Gil!

> I fixed this up and rebased it, should be good to merge once CI is green.

Thanks Phillip!

**Pull request merged**
