### PR TITLE
ci: make the test reporter fork friendly

### PR DESCRIPTION
**Pull request by cpcloud**
The current CI test reporter doesn't allow publishing test failures on runs from forks.

This PR attempts to address that.

### CODE REVIEW

**Comment by jreback** [comment]
looks ok to me

**Comment by cpcloud** [comment]
Alright let's give it a shot. The test report needs to be tested against the main repo since that's where's it's required to run.

**Comment by cpcloud** [comment]
@jreback can you approve so we can give this a try?

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
done

**Comment by cpcloud** [comment]
thanks

**Comment by cpcloud** [comment]
Sweet, looks like it's working.

**Pull request merged**
