### PR TITLE
docs(backends): include docs for inherited members

### LINKED ISSUE #7715: docs: inherited backend functionality isn't documented
### Please describe the issue

For example, I wanted to read the API reference of `create_view` for the DuckDB backend. However, I assume because it's inherited from `BaseAlchemyBackend`, it's nowhere in the doc. (I can go back to the code implementation on GitHub to read it, but that's only because I know where to find it.)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by deepyaman**
Closes #7715

### CODE REVIEW

**Comment by deepyaman** [comment]
> Docs preview: https://pr-7727-6a8568a5192c350208732835adc0359812d569ed--ibis-quarto.netlify.app

Inherited methods are rendering now! They don't all have docstrings, but at least you can see the signatures.

**Review by cpcloud — APPROVED** [review]

**Comment by cpcloud** [comment]
There are a few methods we need to remove in 8.x.x, like `database`. For now they'll show up.

**Pull request merged**
