### PR TITLE
SUPP: Disable Postgres Windows CI

### PR DESCRIPTION
**Pull request by icexelloss**

### CODE REVIEW

**Comment by icexelloss** [comment]
cc @scottcode Postgres SQL tests are failing on Windows and blocking all merges now. I am attempting to disable it temporarily on Windows to get the CI to green. 

I don't have experience debugging postgres SQL, have you done that before maybe shed some light what might be going wrong?

**Comment by xmnlab** [comment]
@icexelloss have you tried with `and not postgresql` ? may you can use `and not postgresql and not postgis`

**Comment by xmnlab** [comment]
here you can find all the ibis pytest markers https://github.com/ibis-project/ibis/blob/master/setup.cfg#L48

**Comment by icexelloss** [comment]
Thanks let me give that a shot

**Comment by xmnlab** [comment]
@icexelloss could you add a release note pls?

**Comment by icexelloss** [comment]
Sure, give me a sec

**Comment by icexelloss** [comment]
Created issue #2076

**Comment by xmnlab** [comment]
@jreback as the previous workflow didn't request a release note, it was been generated automatically by a script, for all types of PR (support, bug, feature), so documentation for contributing doesn't specify details about when add or don't add a release note (https://docs.ibis-project.org/contributing.html#commit-pr-messages).

could you provide a text about that?

**Comment by jreback** [comment]
@xmnlab release notes are meant for end users
excluding
things that are CI relegated is common

**Pull request merged**
