### PR TITLE
BUG: Don't use SET LOCAL to allow redshift to work

### LINKED ISSUE #1158: 'SET LOCAL TIMEZONE = UTC') causes crash on Redshift with postgres driver
Hi everyone,

quick comment.  Using IBIS to interface with redshift with a postgres driver works very well (especially considering it's not explicitly supported!) - but in one of the last few versions, there was a change that broke all queries.

Specifically, I had to comment out:

     @contextlib.contextmanager
     def begin(self):
         with super(PostgreSQLClient, self).begin() as bind:
-            bind.execute('SET LOCAL TIMEZONE = UTC')
+            #bind.execute('SET LOCAL TIMEZONE = UTC')
             yield bind

in

diff --git a/ibis/sql/postgres/client.py b/ibis/sql/postgres/client.py

To get queries to continue working.  What's a slightly more principled way of doing this - should I catch an exception and ignore it?

### PR DESCRIPTION
**Pull request by cpcloud**
Closes #1158

### CODE REVIEW

**Comment by cpcloud** [comment]
@FedericoV Can you give this a try and let me know if it fixes #1158?

**Comment by FedericoV** [comment]
Hi Philip,

Thanks for all the work!  I tried executing a few different queries and all worked without any exceptions.  Any specific commands you want me to check?

**Comment by cpcloud** [comment]
@FedericoV Nothing specific. Builds are passing, so I'm going to merge.

**Comment by cpcloud** [comment]
@FedericoV Thanks for reporting and testing!

**Comment by FedericoV** [comment]
Thank you for all the work on Ibis :)

**Pull request closed without merging**
