### PR TITLE
Enabled mysql CI on azure pipelines

### LINKED ISSUE #1672: MySQL testing on Azure Pipelines has been disabled temporarily
Because chocolatey was failing to install MariaDB

### PR DESCRIPTION
**Pull request by xmnlab**
Fixes #1672

### CODE REVIEW

**Comment by xmnlab** [comment]
it seems there is some problem with azure and conda. I will wait to see if this error will persist on the future.

**Comment by xmnlab** [comment]
@cpcloud @kszucs it seems it is done for review :)

**Comment by xmnlab** [comment]
@cpcloud @kszucs could this be merged?

**Comment by kszucs** [comment]
@cpcloud github says that I'm not authorized to merge this PR, master is protected.

**Comment by cpcloud** [comment]
Hm strange. Will take a look a bit later

**Comment by xmnlab** [comment]
I merged the master into this branch. so maybe the merge is available.

**Comment by cpcloud** [comment]
Thanks @xmnlab!

**Pull request closed without merging**
