### PR TITLE
refactor(ir): track missing relation references

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by cpcloud** [comment]
@kszucs This PR seems a bit stale. Should we close it out?

**Comment by kszucs** [comment]
I'm planning to continue this, just need to fix a couple of IR abstractions first. Please keep it open for now, soon enough I will reach this PR again.

**Comment by cpcloud** [comment]
Is this still viable?

**Comment by kszucs** [comment]
Yes, this is still an issue which we should resolve.

**Comment by cpcloud** [comment]
@kszucs Is this a blocker for 9.0?

**Comment by kszucs** [comment]
No, this aims to fix an issue which have been present in earlier releases.

**Comment by kszucs** [comment]
I won't have time to keep working on this in the near future, so closing it.

**Pull request closed without merging**
