### PR TITLE
Pin google-api-core=1.17.0

### LINKED ISSUE #2241: AttributeError: module 'google.api_core' has no attribute 'gapic_v1'
`ERROR  - AttributeError: module 'google.api_core' has no attribute 'gapic_v1'`

ref: https://github.com/googleapis/python-api-core/issues/47

### PR DESCRIPTION
**Pull request by xmnlab**
Resolve #2241

### CODE REVIEW

**Comment by xmnlab** [comment]
LinuxBuildConda job depends on https://github.com/conda-forge/ibis-framework-feedstock/pull/44

**Comment by jreback** [comment]
once the packages are built you can rebase this

**Comment by xmnlab** [comment]
this PR is ready for review.

**Comment by xmnlab** [comment]
thanks!

**Comment by jreback** [comment]
thanks

**Pull request merged**
