### PR TITLE
TST: split up pandas test functions

### PR DESCRIPTION
**Pull request by jreback**

### CODE REVIEW

**Comment by jreback** [comment]
rebased

**Comment by cpcloud** [comment]
Cool will merge when I get in

**Comment by jreback** [comment]
green

**Comment by cpcloud** [comment]
Let's wait to merge this until the bound parameters and window PRs are merged. There's a lot of changes in those (including moving some files) and I'd rather this PR rebase on those since that's only one rebase vs two that need to happen for each of those PRs.

**Comment by jreback** [comment]
sgtm. ping when you need me to rebase.

**Comment by jreback** [comment]
rebased

**Comment by cpcloud** [comment]
merging.

**Comment by cpcloud** [comment]
thanks!

**Comment by jreback** [comment]
thanks @cpcloud

**Pull request closed without merging**
