### PR TITLE
feat(api): upcast pandas DataFrames to memtables in `rlz.table` rule

### PR DESCRIPTION
**Pull request by cpcloud**
This PR allows using a DataFrame wherever an operation accepts a table via `ibis.expr.rules.table`.

### CODE REVIEW

**Review by kszucs — APPROVED** [review]
Nice!

**Comment by cpcloud** [comment]
There's a segfault in duckdb that appears to be related to arrow/duckdb interaction. It's unrelated to this PR in that the PR isn't causing it, but the problem is reproducible enough that we should avoid merging this PR until we can get some idea about what's happening.

**Comment by cpcloud** [comment]
I'm pretty sure I've worked around the duckdb issue, but there's no 100% solution without a fix upstream.

Filed https://github.com/duckdb/duckdb/issues/6682 to address it.

**Comment by cpcloud** [comment]
I think this feature is valuable enough, and has a low enough blast radius that we can ship this in 5.0.

I will xfail the duckdb test and add some documentation about `null` typed columns.

**Review by kszucs — APPROVED** [review]
Nice!

**Pull request merged**
