### PR TITLE
CI: Files changed using pre-commit run --all-files

### PR DESCRIPTION
**Pull request by xmnlab**

### CODE REVIEW

**Comment by xmnlab** [comment]
one alternative would be changing `posixpath` by `os.path`

https://github.com/timothycrosley/isort/issues/1216

**Comment by datapythonista** [comment]
@xmnlab not sure what's the goal of this PR (would be good to add descriptions and link to issues). But for what I see it's just resorting imports, and pinning the pre-commit version. And it's got few conflicts, so I guess it'll be easier to start from zero than to update this. Closing, if this is something that you'll still like to see merged, feel free to open a new PR or reopen this one.

**Comment by xmnlab** [comment]
the current import position for posixpath is not correct as I commented in some PR that changed that because some isort issue, for example: https://github.com/ibis-project/ibis/blob/master/ibis/impala/client.py#L13

it is a minor issue ... I didn't move this PR because the problem was related to isort .. I was waiting some feedback .. and some days ago I was reported that the problem was fixed in isort master branch ... but maybe it will take some time until the next release (v5).

It is ok to close this PR .. it will be fixed when we update isort here.

**Comment by datapythonista** [comment]
Ah, I understand the PR now. Thought it was isort messing with the imports in the PR. Yes, probably worth closing, and we'll fix the imports when a new version of isort is released. And as I said, better to have descriptions in the PRs, otherwise it's difficult to know what's the goal.

**Pull request closed without merging**
