### PR TITLE
feat(api): allow single argument set operations

### LINKED ISSUE #5715: feat: Allow single table inputs to ibis.union()
### Is your feature request related to a problem?

I am loading a variable number of .csvs and merging them into one table. If I only have one .csv, then `ibis.union(*chunks)` errors. I would like it to not, it just returns the single table unchanged. The len==0 case should still error.

### Describe the solution you'd like

Some examples of other libraries that follow this behavior (no-op on a single iterable):

- np.concatenate
- pandas.concat
- polars.concat
- dask.dataframe.concat

I didn't think of any libs that use our current behavior, but they very well might exist.

### What version of ibis are you running?

Target 5.0?

### What backend(s) are you using, if any?

all

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by cpcloud**
Add support for single argument set operations. Closes #5715.

### CODE REVIEW

**Review by gforsyth — APPROVED** [review]
Looks good -- should we update the docstrings to indicate that users _can_ pass in 0 tables to set ops or is that just confusing?

**Comment by cpcloud** [comment]
I can update the docstrings.

**Comment by cpcloud** [comment]
@gforsyth Docstrings updated!

**Review by gforsyth — APPROVED** [review]
:shipit:

**Pull request merged**
