### PR TITLE
fix(bigquery): ensure that generated names are used when compiling columns

### PR DESCRIPTION
**Pull request by cpcloud**
This PR fixes failing BigQuery builds upstream, which also fixed a known bug in the BigQuery backend when calling `value_counts` on a complex expression. BigQuery only allows certain characters in column names, and ibis generates names that nearly always invalid.

We work around this by generating a new, valid name based on the ibis-operation-generated name.

Previously we didn't use those new valid names when referencing columns, but now we do, and that addresses the issue.

### CODE REVIEW

**Comment by cpcloud** [comment]
BigQuery test suite looks good:

```
cloud in 🌐 falcon in …/ibis on  fix-bigquery-ci is 📦 v5.1.0 via 🐍 v3.10.12 via ❄️  impure (ibis-3.10.12-env) took 1m39s
❯ pytest -m bigquery -n auto --dist loadgroup --snapshot-update -q
bringing up nodes...
.xx........xx.xxxx.....x.x..x....x.......x.xx.....xxx........x.x.....................x..x.xx.x.......xx.x..... [  8%]
.....x.....x..x...xxx.x.x.....x.......x.......x.x...x..x...x...x.x...x.....x.......x....x..xx................. [ 17%]
..........................................................................................................x... [ 26%]
.x.xxxx....xxx..x...x.....x.......x.xxx...x.x.x..x.x.xx...x...x.x....x....x.x..xx.....x.....x..x.............x [ 35%]
..............x........x.x..........................x...........x..x...x.x..x...............x...xx..x..x...... [ 43%]
..x...x...x.....xxx........x..........x..x....x.....x................x..x.x....x.........x...........xxx...... [ 52%]
......x...x.....................x......x...............s...sx..x...x.....x..x.....x..x....x..x....x..........x [ 61%]
x..x...x..x.x..xx........x...x....x..x...x..x.xxx......x...xxxx..x.....xx..x...x...xx..xx.x.xxxx.xxxx.xxx..xx. [ 70%]
x.x.xx.xx..x.x.xxxx.x..xxx........x..................x..................................x..................x... [ 79%]
............................x.......x..x........x..........x.......................x..x................xx.x..x [ 88%]
.x.....x.....xxx.xx..xx...x..xx..x.....................................x.xxxx.s....x.......................... [ 96%]
...........xx.....xx.x..xxx.x.x.xx.x..                                                                         [100%]
1005 passed, 3 skipped, 241 xfailed in 92.25s (0:01:32)
```

**Review by jcrist — APPROVED** [review]

**Comment by tswast** [comment]
Well maybe not any unicode character. It seems some punctuation is still not valid: https://cloud.google.com/bigquery/docs/schemas#flexible-column-names

**Comment by cpcloud** [comment]
Darn, it looks like many of the characters that aren't supported are pretty common in our generated names, like `()` and `.`.

**Comment by cpcloud** [comment]
I suppose we could replace the unsupported characters with their names spelled out.

**Comment by cpcloud** [comment]
Is there any particular reason why those additional characters are not supported? For example, `:` (colon) is allowed but `;` (semicolon) isn't.

**Review by tswast — COMMENTED** [review]
LGTM, assuming we change `_NAME_REGEX` to include all valid characters:

https://github.com/ibis-project/ibis/blob/5e4d16b3338fa22f13ff06503c0dfadbe6c03abb/ibis/backends/bigquery/compiler.py#L66

From the documentation, at https://cloud.google.com/bigquery/docs/schemas#flexible-column-names it might be easiest just to exclude the not-allowed characters:

```
[^!"$()*,./;?@[\\\]^`{}~\n]*
```

**Comment by tswast** [comment]
> Is there any particular reason why those additional characters are not supported? For example, : (colon) is allowed but ; (semicolon) isn't.

I'm not 100% sure. It's pretty clear why backtick isn't allowed since that's what BigQuery uses to identify column names and there doesn't appear to be a way to escape those.

The others must resolve before column names in the SQL parser sometimes and cause trouble.

**Comment by cpcloud** [comment]
With the new changes, BigQuery tests are passing:

```
cloud in 🌐 falcon in …/ibis on  fix-bigquery-ci is 📦 v5.1.0 via 🐍 v3.10.12 via ❄️  impure (ibis-3.10.12-env) took 2s
❯ pytest -m bigquery -n auto --dist loadgroup --snapshot-update -q
bringing up nodes...
..........xx........xx.......................x.....x.....x..xx....................x.x..xxx.....x.x.....x....x. [  8%]
x......x......x...xxx...x...xxx...xx.........x.xx..x......x..x.xxx.x.x..x..xxx...x...xx.....xx....x..x.xx.x.x. [ 17%]
.x.......x.x.x..x.xx.........xxx....xx.x....x.....x....xx...xx.x...xx.x....xx...x..........x.....x.x...x.x.... [ 26%]
x.....x...xx.........x......x.....xx...x....x.......x......x..xxx........x..x.....x.......................x... [ 35%]
.......................x.......................x..x.........x..x.x...........x....xx.x...x.x.xx.x...xxxx.x.x.x [ 44%]
....x.xx..xx.xx....x.xxxx..xx..x.x.xsx.x....x.x......s...........x......x..x....x..x..x.xx..x..x..x.x..x...... [ 52%]
.x....xx.xxxxxxx.xxxxxxx.xxx.....xxx.....xx.x....xx....x...x.xx.........xx......xx.........x.x....x.x.......xx [ 61%]
..x........x..........x..x...xx........x...x.x.......x...........x.......xx.......................x.x..x...... [ 70%]
.x..........x............xxx...........................................x.....................x.............x.. [ 79%]
.....................x.........................................................x........x..........x.......... [ 88%]
.x...................x....................x......x............x..............x....................x........... [ 96%]
........................s......x......x                                                                        [100%]
1005 passed, 3 skipped, 241 xfailed in 104.90s (0:01:44)
```

**Review by tswast — APPROVED** [review]

**Comment by cpcloud** [comment]
Thanks for the regex @tswast!

**Pull request merged**
