### PR TITLE
refactor(bigquery): remove unnecessary and misspelled bigquery string find implementation

### PR DESCRIPTION
**Pull request by tswast**
Typo `visti` -> `visit`

### CODE REVIEW

**Review by gforsyth — COMMENTED** [review]
wait, what?  hmm, I have to take a look at our tests

**Comment by gforsyth** [comment]
Thanks for flagging (and fixing) this @tswast !  I'm going to add `find` to the updated string tests and see what shakes out.

**Comment by cpcloud** [comment]
I think this means:

1. We're not testing all the error modes
2. The base implementation works fine (since that's what'll be called) and we can probably remove the BigQuery-specific implementation?

**Comment by cpcloud** [comment]
I think we can just delete the bigquery implementation since it's actually more limited than the base implementation and the base implementation has been successfully passing for many many CI runs now.

**Review by cpcloud — APPROVED** [review]

**Pull request merged**
