### PR TITLE
test(bench): reduce big union join threshold

### PR DESCRIPTION
**Pull request by cpcloud**
This PR gets benchmarks passing again. Nesting levels were increased by https://github.com/ibis-project/ibis/pull/8414.

Unfortunately, SQLGlot's SQL generation algorithm (but not its parsing algorithm) is recursive.

This means that it cannot handle large nesting levels of select statements.

Pre-SQLGlot, Ibis used to handle much larger nesting levels. This functionality was lost in the sqlglot refactor.

Ultimately, someone needs to address this upstream in sqlglot by converting the generation algorithm to an iterative
one.

I believe we should gain a little bit back after #8572 is merged, since fewer select statements will be generated.

### CODE REVIEW

**Review by gforsyth — APPROVED** [review]
Do we consider this a 9.0 blocker (the generation algorithm work)?

**Comment by cpcloud** [comment]
My 2c is that no we shouldn't consider this a blocker for 9.0. Curious to hear others opinions.

**Comment by gforsyth** [comment]
> My 2c is that no we shouldn't consider this a blocker for 9.0. Curious to hear others opinions.

It would be an interesting scream test, if nothing else, for users who have very big unions.

**Comment by cpcloud** [comment]
We should figure out why this isn't failing in PR CI, and only failing when we push. I suspect I screwed up the GHA events when I moved benchmarks into a separate workflow.

**Pull request merged**
