### PR TITLE
OmnisciDB ops.IdenticalTo, ops.NTile are working via impala implementation

### PR DESCRIPTION
**Pull request by semelianova**

### CODE REVIEW

**Comment by xmnlab** [comment]
related to NTile .. there are 2 problems:

1) there is no way to test NTILE output currently ... I have some work related to that.
2) omniscidb NTILE seems to be inconsistent with PostgreSQL NTile (see: https://gist.github.com/xmnlab/8488e7b0b7988407521ce4cdc273fc4c)

related to `IdenticalTo`, do you have any documentation about this operation on OmniSciDB?

**Comment by semelianova** [comment]
I checked `ops.IdenticalTo` by `test_generic.py::test_identical_to`, test passes.

I try to check `ops.NTile` by `test_window.py::test_window[OmniSciDB-ntile]`, but get an exception from pandas `ValueError: Length of values does not match length of index`. I guess the exception is occurred due to `df['string_col']` has a `None` value.

**Comment by xmnlab** [comment]
@semelianova as you can see ntile test was not fully implemented https://github.com/ibis-project/ibis/blob/master/ibis/tests/all/test_window.py#L57

probably that is why it is raising this error.

as (pure) pandas doesn't have a ntile method we cannot just compare that to the pandas result.

you can check a previous discussion about this here: https://github.com/ibis-project/ibis/pull/1976#issuecomment-579904298

**Comment by xmnlab** [comment]
@semelianova I am adding NTIle here https://github.com/ibis-project/ibis/pull/2146

**Comment by datapythonista** [comment]
Closing this for now. For what I understand `NTile` is implemented in #2146, so this is duplicated. And there are problems to make `IdenticalTo` work that require more work. Feel free to open a new PR for that once you figure out what's the issue @semelianova.

**Pull request closed without merging**
