### PR TITLE
Batch 3 impala operation registry move

### PR DESCRIPTION
**Pull request by matthewmturner**
Next batch of operation registry moves from impala.

### CODE REVIEW

**Comment by matthewmturner** [comment]
@datapythonista any idea what those azp errors are? related to the issues you previously mentioned?

**Comment by datapythonista** [comment]
The Windows error seems to be a new genuine error. Unrelated to this PR, but we'll have to fix it before merging. If you want to open an issue, that would be great.

The Impala error seems to be the error we've experienced several times, I guess it'll go away after a rerun or two.

**Review by datapythonista — APPROVED** [review]
Thanks @matthewmturner, looks great. If you can rebase and see if the CI is green now, that would be great.

**Comment by matthewmturner** [comment]
looks like were good :)

**Comment by jreback** [comment]
thanks @matthewmturner

**Pull request merged**
