### PR TITLE
WIP: Remove Ibis dialect concept, and simplify the whole compiler

### PR DESCRIPTION
**Pull request by datapythonista**
The concept of Ibis dialect was a hack that made the compiler architecture extremely cumbersome and fragile. It was in a very weird way linking a translator and a query context, and use extensively in the compiler. Instead of using the dialect, this refactoring makes the client and the query builder know which are the right translator and query context for each backend, and the helper classes (`SelectBuilder`, `Select`...) get this information when instantiated.

There are few side clean ups, whether required to make this work, or for me to understand the code better and not become crazy.

There is still a test failure I need to investigate.

### CODE REVIEW

**Comment by kszucs** [comment]
I'm definitely in favor of this change. Let me know if you need help with reviewing it.

**Comment by datapythonista** [comment]
Thanks @kszucs. This should be quite ready, except for a test failure that I think should be gone (or easier to understand) once #2789 is merged.

**Comment by jreback** [comment]
@datapythonista status of this one?

**Comment by datapythonista** [comment]
> @datapythonista status of this one?

It was too challenging to get green. With the work  in the last PRs, should be easier to get this done. I'm working in this direction, not sure if I'll work on this PR, or start a new branch.

You can ignore this one and the other one removing `build_ast` for now, will let you know once I've got something that can be reviewed.

**Comment by jreback** [comment]
kk sounds good

**Comment by datapythonista** [comment]
Superseded by #2818.

**Pull request closed without merging**
