### PR TITLE
DOC: Moving doc pages to the website

### PR DESCRIPTION
**Pull request by datapythonista**
Removing contributing page from docs (now duplicated in the website), and moving the roadmap and the license to the website. This is consistent with pandas, and makes it easier to find the main sections of the docs.

### CODE REVIEW

**Comment by jreback** [comment]
thanks @datapythonista ping on green.

**Comment by jreback** [comment]
added you as a committer, pls merge on green.

**Comment by datapythonista** [comment]
Thanks @jreback. Apparently there is something missing to be able to merge this. Not sure what, I attach screenshot of the messages I see:

ibis_merge

**Comment by jreback** [comment]
thanks @datapythonista 

maybe because I just changed it? anyhow can try on next one.

**Pull request merged**
