### PR TITLE
fix(clickhouse): use named rather than positional group by

### PR DESCRIPTION
**Pull request by JackFielding**
Closes: https://github.com/ibis-project/ibis/issues/6101

### CODE REVIEW

**Comment by JackFielding** [comment]
I'll stop work on this for now because it's clear that in the tests using positional arguments was intentional. It would probably benefit from a look over from someone more familiar with `ibis`.

**Review by gforsyth — CHANGES_REQUESTED** [review]
Hey @JackFielding -- thanks for putting this in!  This looks like a reasonable change to me -- the failing tests are SQL snapshot tests and this change is (understandably) changing that output to something semantically equivalent but not explicitly equal.

You can update the snapshot files by running `pytest --snapshot-update`

**Review by cpcloud — APPROVED** [review]
Fixed up the snapshots, LGTM!

**Comment by cpcloud** [comment]
Thanks for the PR @JackFielding!

**Comment by JackFielding** [comment]
Thank you both for your help!

**Pull request merged**
