### PR TITLE
BUG/TST: Fix skipping for new auth flow

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by cpcloud** [comment]
Per #1739 I'm going to disable the window 3.7 build for now.

**Comment by cpcloud** [comment]
First trying one more thing before disabling..

**Comment by xmnlab** [comment]
hey @cpcloud maybe for azure configuration would be good to update the structure. `createCustomEnvironment` is deprecated now. I changed that in this PR: https://github.com/ibis-project/ibis/pull/1710/files#diff-fec826feae04e51c0d94076385408bdcR13

**Comment by cpcloud** [comment]
Ok, I will take a look at bit later. Thanks @xmnlab!

**Comment by xmnlab** [comment]
great! let me know if I can help in any way :+1:

**Comment by cpcloud** [comment]
@xmnlab It looks like this may have worked! I'll check back later today and merge on green so we can close out some of the remaining PRs for 1.0.0.

**Comment by cpcloud** [comment]
@xmnlab I cherry picked most of your changes from #1710, hope you don't mind!

**Comment by xmnlab** [comment]
@cpcloud awesome!

**Pull request closed without merging**
