### PR TITLE
FEAT: Add auth_local_webserver, auth_external_data, and auth_cache to BigQuery connect

### PR DESCRIPTION
**Pull request by tswast**
Towards #2179 

In order to verify the application, I need to submit a video demonstrating the need for the requested scopes. I realized that we don't make it easy to query data in Google Drive, so this PR remedies that.

### CODE REVIEW

**Comment by tswast** [comment]
Here's a video demonstrating this new feature https://www.youtube.com/watch?v=UMWMnlA54Ys The Google verification team requested it.

**Comment by tswast** [comment]
Since these features require a user to open a browser window, testing them in CI isn't really feasible. I can add some mocked unit tests if desired.

**Comment by jreback** [comment]
> Since these features require a user to open a browser window, testing them in CI isn't really feasible. I can add some mocked unit tests if desired.

that would be good to at least ensure the paths are exercised

**Comment by tswast** [comment]
@jreback I've added unit tests. CI is green.

**Comment by jreback** [comment]
thanks @tswast very nice!

**Pull request merged**
