### PR TITLE
DOC: Add to release notes related to Postgres UDFs

### PR DESCRIPTION
**Pull request by scottcode**
Add feature and bug fix to release notes related to Postgres UDFs

Inspired by conversation in #2015 and #2021

### CODE REVIEW

**Comment by scottcode** [comment]
I think `LinuxBiuldDocs` failure may be related to mismatching versions of sphinx-related packages. See [this similar issue](https://github.com/pypa/twine/issues/492) in another project.

**Comment by jreback** [comment]
can u pin sphinx to last good version and open an issue about this

**Comment by scottcode** [comment]
I rebased and re-pushed

**Comment by xmnlab** [comment]
thanks @scottcode for adding this notes.
could you rebase your branch again? thanks!

**Comment by xmnlab** [comment]
@scottcode these notes are already on release page (https://docs.ibis-project.org/release.html) thanks!

**Pull request closed without merging**
