### PR TITLE
WIP: Simplifying CI

### PR DESCRIPTION
**Pull request by datapythonista**
We have two things breaking the CI, so we'll have to merge this and #2302 in red (unless we merge both PRs).

Windows builds are reaching the azure timeout of one hour, failing the builds. This PR should speed up the conda solver by pinning some dependencies and reducing the conda solver search space.

### CODE REVIEW

**Comment by jreback** [comment]
can u leave the yaml files? it's much more obvious what we r installing that way
and for 3.6 and 3.7 just pin what is needed 
for 3.8 ok to relax 
but do that in the yaml itself

**Comment by datapythonista** [comment]
I'm thinking on having separate yaml files for the backends. Will do some tests first, and see how things work, but pinning with the current setup was still not enough (even if I was pinning half of the packages). And it's like the third or fourth time I need to do it, so want to experiment and see if I can leave things simpler so at least it's easier to find what to pin, and changes don't need to be repeated few times.

But as said, will do some tests first and try to see how things work before proposing these changes.

**Comment by jreback** [comment]
kk sounds good (yeah not averse to separate for backends as well)

**Pull request closed without merging**
