### PR TITLE
SUPP: Fix pre commit hooks configuration

### PR DESCRIPTION
**Pull request by icexelloss**
This is broken after #2068

### CODE REVIEW

**Comment by icexelloss** [comment]
cc @anmyachev

**Comment by anmyachev** [comment]
@icexelloss good catch!

@xmnlab hook is working now

**Comment by xmnlab** [comment]
thanks for fixing that @icexelloss !
could you add a release note for that?

we just need to figure out how to fix the windows ci issue

**Comment by icexelloss** [comment]
This is fixed in #2075

**Pull request closed without merging**
