### PR TITLE
Adds proper binary column translation for BigQuery compiler

### LINKED ISSUE #2354: BigQuery: cast to `dt.binary` results in invalid datatype in compiled SQL
It appears that casting to `ibis.expr.datatypes.binary` results in `BINARY` as the data type. The correct [name for this data type in BigQuery is `BYTES`](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#bytes_type)

**Code example**

```python
import ibis.bigquery
import ibis.expr.datatypes as dt

bigquery_client = ibis.bigquery.connect()
tbl = bigquery_client.table(
    "citibike_trips",
    database="bigquery-public-data.new_york_citibike"
)
expr = tbl[
    tbl["start_station_name"]
    .cast(dt.binary)
    .name("station_hash")
]
sql = expr.compile()
print(sql)
```

**Output**

```sql
SELECT CAST(`start_station_name` AS BINARY) AS `station_hash`
FROM `bigquery-public-data.new_york_citibike.citibike_trips`
```

This results in a `Type not found: BINARY at [1:48]` error when you paste this query in the BigQuery UI.

### PR DESCRIPTION
**Pull request by renato2099**
Fixes #2354

Added a unit test for verifying that the expected generated SQL string is generated.

### CODE REVIEW

**Comment by renato2099** [comment]
hey @datapythonista , maybe you could review this PR please? thanks!

**Comment by datapythonista** [comment]
@tswast do you want to have a look?

**Review by tswast — APPROVED** [review]
Beautiful. Thank you!

**Comment by renato2099** [comment]
If there is anything else, then I'd be happy if you guys could merge it :)

**Review by jreback — CHANGES_REQUESTED** [review]
can you add a release note, change looks good otherwise, ping on green.

`docs/source/release/index.rst` is the place

**Comment by renato2099** [comment]
Added to the release note, and green build @jreback

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
thanks @renato2099

**Pull request merged**
