### PR TITLE
DOC: Added autosummary of ClickHouse API

### PR DESCRIPTION
**Pull request by EdAbati**
As discussed with @datapythonista in https://github.com/ibis-project/ibis/pull/2437#issuecomment-702856451, I am adding in the docs the autosummary for the ClickHouse API that was missing.

I have tried to keep it consistent with the rest of the backends, and I have added for now only the client methods with docstrings. Should I add others?

Unfortunately I was not able to generate the docs locally to check if it looks ok visually, which command should I use to build the documentation?

Please let me know if there is anything else I should improve, thank you very much!

### CODE REVIEW

**Review by datapythonista — APPROVED** [review]
lgtm, thanks @EdAbati 

Can you have a look at the CI and try to get it green please?

**Comment by EdAbati** [comment]
Hi @datapythonista , 

I can only see a warning in the CI logs: https://dev.azure.com/ibis-project/ibis/_build/results?buildId=3555&view=logs&j=8f09edc2-e3b7-52de-126a-0225c4f3efa1&t=e3ba5a33-21a6-5484-d0be-59baf122f79c&l=439

`WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://pydata-google-auth.readthedocs.io/en/latest/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 502 Server Error: Bad Gateway for url: https://pydata-google-auth.readthedocs.io/en/latest/objects.inv`

Can a warning make the pipeline fail? Should we maybe try rerunning it?

**Comment by datapythonista** [comment]
> Can a warning make the pipeline fail? Should we maybe try rerunning it?

Yes, we force that in sphinx. The error seems to be caused by the documentation of that google module to be down. I rerun the CI, let's see if we're lucky now.

**Comment by jreback** [comment]
thanks @EdAbati

**Pull request merged**
