### PR TITLE
refactor(impala): remove kudu-python usage

### PR DESCRIPTION
**Pull request by cpcloud**
This PR removes use of kudu-python in ibis. Kudu is still supported through impala. See https://kudu.apache.org/docs/kudu_impala_integration.html for details.

### CODE REVIEW

**Comment by jreback** [comment]
lgtm but @kszucs is prob a better reviewer

**Comment by kszucs** [comment]
@cpcloud  how can we mark it as a breaking change?

**Review by kszucs — APPROVED** [review]
LGTM

**Comment by cpcloud** [comment]
@kszucs The breaking is marked as such in the commit message:

image

The release notes will look similar to this when we cut the next release:

image

**Pull request merged**
