### PR TITLE
CI: Add linting to GitHub actions

### PR DESCRIPTION
**Pull request by datapythonista**
First step to simplify the CI (see #2305).

This doesn't add much value by itself yet, but will help me cleaning the CI and making it more robust.

I'll follow up with moving the docs here, and just leaving the tests in azure. Then I will simplify the CI for the tests and fix the current problems.

### CODE REVIEW

**Comment by datapythonista** [comment]
@jreback when you have a chance, can you have a look at this? The CI in azure will be red, since it's currently broken, and I'm not yet fixing it here.

I'm implementing the CI for the linting, the conda forge package and the benchmark in a much simpler way than what we have now. Once this is merged I'll continue with the docs and the tests. I've been doing tests, and I think in GitHub actions things will be much simpler (besides having the double of workers).

**Comment by jreback** [comment]
looks fine, though hard to tell if its wokring yet?

**Comment by jreback** [comment]
oh sorry this is the main check,ok  then.

**Comment by datapythonista** [comment]
There are few of the steps (e.g. mypy) that are not working, and they don't make the CI fail here. But I'm adding them anyway (we don't have them now), so it's easier to see that they need to be fixed. But benchmarks, linting and the conda package are correctly tested here. Will follow up with the builds that require the docker containers running (docs and tests), which will be a bit trickier, but I think it can be implemented much simpler than until now with GitHub Actions.

Thanks!

**Comment by jreback** [comment]
> There are few of the steps (e.g. mypy) that are not working, and they don't make the CI fail here. But I'm adding them anyway (we don't have them now), so it's easier to see that they need to be fixed. But benchmarks, linting and the conda package are correctly tested here. Will follow up with the builds that require the docker containers running (docs and tests), which will be a bit trickier, but I think it can be implemented much simpler than until now with GitHub Actions.
> 
> Thanks!

sounds great, and thanks again for fixing!

**Pull request merged**
