### PR TITLE
[MapD] Fixed where operator - Fixes #1623

### LINKED ISSUE #1623: MapD where() : No match found for function signature if(<BOOLEAN>, <NUMERIC>, <NUMERIC>)')
`expr = ibis.where(table.num > 1, table.num + 10, table.num)`
`expr.execute()`
return error :
mapd.ttypes.TMapDException: TMapDException(error_msg='Exception: Exception occurred: org.apache.calcite.runtime.CalciteContextException: From line 1, column 8 to line 1, column 41: No match found for function signature if(<BOOLEAN>, <NUMERIC>, <NUMERIC>)')

Backend=MapD MapD=4.1.1 ibis=0.14 Python=3.6
Ubuntu=18.04 Anaconda=5.1

### PR DESCRIPTION
**Pull request by xmnlab**
This PR fixes #1623

### CODE REVIEW

**Comment by xmnlab** [comment]
@cpcloud @kszucs  

the conda build is failing for windows. do you have any idea about this error?

**Comment by cpcloud** [comment]
@xmnlab Yep, I've got #1660 up to address this.

**Comment by cpcloud** [comment]
@xmnlab Can you add a test here?

**Comment by xmnlab** [comment]
@cpcloud sure! I am working on that!

**Comment by xmnlab** [comment]
it is ready for review!

**Comment by cpcloud** [comment]
LGTM. Thanks @xmnlab

**Pull request closed without merging**
