### PR TITLE
docs(sql-tutorial): fix minor typo in union section of SQL user tutorial

### PR DESCRIPTION
**Pull request by chris-park**

### CODE REVIEW

**Comment by cpcloud** [comment]
@chris-park Thanks for the PR!

Can you alter the commit message to 

```
docs(sql-tutorial): fix minor typo in union section of SQL user tutorial
```

That way your contribution will show up in our automatically generated release notes!

**Comment by chris-park** [comment]
Done - thanks Philip.

**Comment by cpcloud** [comment]
@chris-park Sorry, I think was unclear!

It looks like you adjusted the pull request title, but the git commit message needs to be adjusted (the PR title can be whatever you want).

**Comment by chris-park** [comment]
Woops sorry my bad. Does it look ok now? Otherwise I'll just re-fork and re-raise the PR....sorry about this.

**Comment by cpcloud** [comment]
No problem! I can help out here.

**Review by cpcloud — APPROVED** [review]

**Comment by chris-park** [comment]
Thanks!

**Pull request merged**
