### PR TITLE
perf(pandas): remove reexecution of alias children

### LINKED ISSUE #4261: perf(pandas): `Alias` executes its children twice
On the Pandas backend, `Alias` executes the expression it is renaming (and the tree under it) twice

See [this notebook](https://gist.github.com/timothydijamco/b3d6e1cceb1e6f3fb9cf7ddb8d1db7eb)

### PR DESCRIPTION
**Pull request by timothydijamco**
Fixes #4261

### CODE REVIEW

**Comment by cpcloud** [comment]
@timothydijamco Can you change the commit prefix to be `perf(pandas):`? That way it'll show up in the release notes under performance improvements!

**Comment by timothydijamco** [comment]
> @timothydijamco Can you change the commit prefix to be `perf(pandas):`? That way it'll show up in the release notes under performance improvements!

ah yes, done

**Review by cpcloud — APPROVED** [review]
LGTM. I'll fix up the style lints.

**Review by kszucs — APPROVED** [review]

**Comment by timothydijamco** [comment]
thanks! ran black so style is hopefully OK now

**Comment by cpcloud** [comment]
Merging! Thanks again @timothydijamco @jreback!

**Pull request merged**
