### PR TITLE
TST: Parameterize pandas datatype tests

### PR DESCRIPTION
**Pull request by gerrymanoim**

### CODE REVIEW

**Comment by gerrymanoim** [comment]
Failing tests are `test_import_time`

**Comment by jreback** [comment]
> Failing tests are `test_import_time`

can bump that for now, but can you also create an issue about this (*maybe* something is going on).

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
thanks @gerrymanoim

**Comment by gerrymanoim** [comment]
https://github.com/ibis-project/ibis/issues/2544

**Pull request merged**
