### PR TITLE
fix(datatypes): convert UUIDs to strings

### LINKED ISSUE #8261: bug: can't preview table containing UUIDs
### What happened?

```python
import ibis
ibis.options.interactive = True

t = ibis.memtable(
    {
        "x": [1, 2, 3],
    }
)
con = ibis.duckdb.connect()
t = con.create_table("t", t, overwrite=True)
t = t.sql("SELECT *, uuid() as id FROM t")
t
```
After the .sql() call, there is to interactive preview showing up. If I remove the .sql() line, it does show up

image

image

### What version of ibis are you using?

8.0.0

### What backend(s) are you using, if any?

duckdb

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by cpcloud**
Fixes #8261.

### CODE REVIEW

**Comment by cpcloud** [comment]
Confirming this fixes the repr:

```
In [3]: from ibis.interactive import *

In [4]: con = ibis.duckdb.connect()

In [5]: con.sql("select uuid()")
Out[5]:
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ uuid()                               ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ uuid                                 │
├──────────────────────────────────────┤
│ 46bdc7b4-152c-43b7-8f8a-8d136a8cc7dd │
└──────────────────────────────────────┘
```

**Comment by NickCrews** [comment]
This looks good, thanks @cpcloud !

Assuming that we don't want to actually ship a [pyarrow extension type](https://arrow.apache.org/docs/python/extending_types.html) (they have a uuid example there)?

**Comment by cpcloud** [comment]
> This looks good, thanks @cpcloud !
> 
> Assuming that we don't want to actually ship a [pyarrow extension type](https://arrow.apache.org/docs/python/extending_types.html) (they have a uuid example there)?

Eventually maybe, but not in this PR :)

**Comment by cpcloud** [comment]
Extension types run the risk of creating type fiefdoms, and that's not good for ibis because we have to interact with downstream systems. Placing a burden on them to understand our PyArrow extension types is asking quite a lot.

**Pull request merged**
