### PR TITLE
docs(blog): add tags to blog posts

### PR DESCRIPTION
**Pull request by cpcloud**
This PR adds tags to our quarto blog posts.

### CODE REVIEW

**Comment by cpcloud** [comment]
Should we remove the `blog` tag? Seems like it's used in every post which makes it useless for differentiating anything.

**Comment by lostmygithubaccount** [comment]
I was initially thinking we might have like "tips and tricks" that aren't blogs? but super easy to change later, feel free to remove from my perspective

**Comment by cpcloud** [comment]
I'll leave it for now.

**Comment by cpcloud** [comment]
@lostmygithubaccount Any other feedback?

**Review by lostmygithubaccount — APPROVED** [review]
LGTM, we can play around with more/different categories later, this looks like a great start

**Pull request merged**
