### PR TITLE
fix(snowflake): handle schema when getting table

### PR DESCRIPTION
**Pull request by frsann**
The current implementation of `_get_sqla_table` does not  handle different schemas properly. This PR fixes  this.

This should fix issue https://github.com/ibis-project/ibis/issues/4801

### CODE REVIEW

**Review by cpcloud — APPROVED** [review]
LGTM!

**Comment by cpcloud** [comment]
@frsann Are you able to test this locally and confirm it works?

**Comment by frsann** [comment]
@cpcloud I tested it this way:
```python
ibis.options.verbose = True

conn = ibis.snowflake.connect(
    user=user, password=password, database="MY_DATABASE/public", account=account
)

venues = conn.table("venues")  # using default/current schema
purchases = conn.table("purchases", schema="staging")

print(purchases["ID", "VENUE_NAME"].limit(3).execute())
# SELECT t0."ID", t0."VENUE_NAME" 
# FROM staging.purchases AS t0
# LIMIT %(param_1)s

#     ID   VENUE_NAME
# 0  id1  venue1
# 1  id2  venue2
# 2  id3  venue3

print(venues["ID", "NAME"].limit(3).execute())

# SELECT t0."MERCHANT_ID", t0."PUBLIC_VISIBLE" 
# FROM venues AS t0
# LIMIT %(param_1)s

#      ID           NAME        
# 0  id1           name1
# 1  id2           name2
# 2  id3           name3

```

Can you think of any other scenarios that would be good to test?

**Comment by cpcloud** [comment]
@frsann Thanks again!

**Pull request merged**
