### PR TITLE
[DO NOT MERGE] WIP: Add code for read and write Arrow RecordBatchStream file

### PR DESCRIPTION
**Pull request by icexelloss**
Some example code to add read and write node for Arrow record batch stream files.

(This is meant to be used with ibis-substrait to pass to Arrow C++ engine)

### CODE REVIEW

**Comment by icexelloss** [comment]
@cpcloud @kszucs first time using the new dev workflow - How do I automatically fix code style? I tried to run `pre-commit` but it didn't fix it.

(Didn't see it under https://ibis-project.org/contribute/style/)

**Comment by icexelloss** [comment]
Btw - I haven't used nix-shell before - does it serve the same purpose as python virtual env?

**Comment by cpcloud** [comment]
@icexelloss What's the plan with this PR? Should we convert this to a draft or close it out?

**Comment by gforsyth** [comment]
Hey @icexelloss -- I'm going to close this out for now so we can keep the PR queue clean.  Please ping if you'd like it reopened!

**Pull request closed without merging**
