### PR TITLE
refactor(datatypes): make DataType and friends immutable and remove __slots__usage

### PR DESCRIPTION
**Pull request by cpcloud**
This PR moves `DataType` and its subclasses away from `__slots__` and replaces the current
property caching with `cached_property`s.

### CODE REVIEW

**Comment by cpcloud** [comment]
This actually results in a 20-30% performance regression.

**Comment by cpcloud** [comment]
Stacking #3619 -> #3621 -> #3613 results in these benchmark numbers which look like an overall nice improvement:

```
-------------------------------------------------- benchmark 'test_builtins[hash-large]': 2 tests --------------------------------------------------
Name (time in us)                              Mean            OPS (Kops/s)            Median               Min                Max            Rounds
----------------------------------------------------------------------------------------------------------------------------------------------------
test_builtins[hash-large] (0001_1767205)     2.9511 (1.20)         338.8578 (0.83)     2.9450 (1.20)     2.8650 (1.21)     15.1280 (1.08)      47347
test_builtins[hash-large] (NOW)              2.4639 (1.0)          405.8604 (1.0)      2.4540 (1.0)      2.3640 (1.0)      14.0460 (1.0)       57166
----------------------------------------------------------------------------------------------------------------------------------------------------

-------------------------------------------------- benchmark 'test_builtins[hash-medium]': 2 tests --------------------------------------------------
Name (time in us)                               Mean            OPS (Kops/s)            Median               Min                Max            Rounds
-----------------------------------------------------------------------------------------------------------------------------------------------------
test_builtins[hash-medium] (0001_1767205)     2.9613 (5.41)         337.6950 (0.18)     2.8350 (5.16)     2.5950 (5.06)     15.0490 (8.72)     113418
test_builtins[hash-medium] (NOW)              0.5474 (1.0)        1,826.8508 (1.0)      0.5491 (1.0)      0.5130 (1.0)       1.7263 (1.0)      168891
-----------------------------------------------------------------------------------------------------------------------------------------------------

-------------------------------------------------- benchmark 'test_builtins[hash-small]': 2 tests --------------------------------------------------
Name (time in us)                              Mean            OPS (Kops/s)            Median               Min                Max            Rounds
----------------------------------------------------------------------------------------------------------------------------------------------------
test_builtins[hash-small] (0001_1767205)     2.7880 (1.14)         358.6750 (0.88)     2.7750 (1.14)     2.6750 (1.14)     20.9590 (1.50)     150784
test_builtins[hash-small] (NOW)              2.4538 (1.0)          407.5370 (1.0)      2.4350 (1.0)      2.3440 (1.0)      13.9860 (1.0)      193799
----------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------- benchmark 'test_builtins[str-large]': 2 tests ------------------------------------------------
Name (time in ms)                             Mean                 OPS            Median               Min               Max            Rounds
----------------------------------------------------------------------------------------------------------------------------------------------
test_builtins[str-large] (0001_1767205)     9.3577 (1.09)     106.8634 (0.91)     9.3495 (1.09)     9.2225 (1.09)     9.8753 (1.14)        104
test_builtins[str-large] (NOW)              8.5538 (1.0)      116.9069 (1.0)      8.5501 (1.0)      8.4771 (1.0)      8.6542 (1.0)         115
----------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------ benchmark 'test_builtins[str-medium]': 2 tests -----------------------------------------------
Name (time in ms)                              Mean                 OPS            Median               Min               Max            Rounds
-----------------------------------------------------------------------------------------------------------------------------------------------
test_builtins[str-medium] (0001_1767205)     3.2096 (1.45)     311.5637 (0.69)     3.2044 (1.45)     3.1385 (1.45)     3.3647 (1.34)        303
test_builtins[str-medium] (NOW)              2.2070 (1.0)      453.1077 (1.0)      2.2054 (1.0)      2.1597 (1.0)      2.5161 (1.0)         377
-----------------------------------------------------------------------------------------------------------------------------------------------

---------------------------------------------------- benchmark 'test_builtins[str-small]': 2 tests ----------------------------------------------------
Name (time in us)                              Mean            OPS (Kops/s)             Median                Min                 Max            Rounds
-------------------------------------------------------------------------------------------------------------------------------------------------------
test_builtins[str-small] (0001_1767205)     82.7878 (1.12)          12.0791 (0.89)     82.4360 (1.13)     78.4390 (1.09)     102.6840 (1.0)         486
test_builtins[str-small] (NOW)              73.6848 (1.0)           13.5713 (1.0)      73.2590 (1.0)      71.9660 (1.0)      155.1040 (1.51)       8685
-------------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------ benchmark 'test_compile[large-impala]': 2 tests ------------------------------------------------
Name (time in ms)                               Mean                 OPS            Median               Min                Max            Rounds
-------------------------------------------------------------------------------------------------------------------------------------------------
test_compile[large-impala] (0001_1767205)     4.7925 (1.0)      208.6597 (1.0)      4.7846 (1.0)      4.7121 (1.0)       4.9698 (1.0)         192
test_compile[large-impala] (NOW)              5.2765 (1.10)     189.5199 (0.91)     5.0704 (1.06)     4.9767 (1.06)     32.4689 (6.53)        144
-------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------ benchmark 'test_compile[large-sqlite]': 2 tests ------------------------------------------------
Name (time in ms)                               Mean                 OPS            Median               Min                Max            Rounds
-------------------------------------------------------------------------------------------------------------------------------------------------
test_compile[large-sqlite] (0001_1767205)     8.0241 (1.0)      124.6249 (1.0)      7.8416 (1.0)      7.7502 (1.0)      11.7168 (1.25)        118
test_compile[large-sqlite] (NOW)              8.3756 (1.04)     119.3946 (0.96)     8.2618 (1.05)     8.1582 (1.05)      9.3739 (1.0)          17
-------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------ benchmark 'test_compile[medium-impala]': 2 tests -----------------------------------------------
Name (time in ms)                                Mean                 OPS            Median               Min               Max            Rounds
-------------------------------------------------------------------------------------------------------------------------------------------------
test_compile[medium-impala] (0001_1767205)     3.3443 (1.01)     299.0124 (0.99)     3.3229 (1.01)     3.2488 (1.01)     3.6004 (1.0)         254
test_compile[medium-impala] (NOW)              3.2958 (1.0)      303.4189 (1.0)      3.2985 (1.0)      3.2128 (1.0)      3.6565 (1.02)        254
-------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------ benchmark 'test_compile[medium-sqlite]': 2 tests ------------------------------------------------
Name (time in ms)                                Mean                 OPS            Median               Min                Max            Rounds
--------------------------------------------------------------------------------------------------------------------------------------------------
test_compile[medium-sqlite] (0001_1767205)     4.7389 (1.07)     211.0189 (0.93)     4.4485 (1.01)     4.3383 (1.01)     41.0949 (7.14)        128
test_compile[medium-sqlite] (NOW)              4.4172 (1.0)      226.3898 (1.0)      4.3908 (1.0)      4.3060 (1.0)       5.7585 (1.0)         215
--------------------------------------------------------------------------------------------------------------------------------------------------

---------------------------------------------------- benchmark 'test_compile[small-impala]': 2 tests ----------------------------------------------------
Name (time in us)                                Mean            OPS (Kops/s)             Median                Min                 Max            Rounds
---------------------------------------------------------------------------------------------------------------------------------------------------------
test_compile[small-impala] (0001_1767205)     41.8846 (1.01)          23.8751 (0.99)     40.4260 (1.00)     38.0820 (1.00)     147.1890 (1.00)       9850
test_compile[small-impala] (NOW)              41.4482 (1.0)           24.1265 (1.0)      40.2770 (1.0)      38.0320 (1.0)      146.6680 (1.0)        8764
---------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------- benchmark 'test_compile[small-sqlite]': 2 tests ------------------------------------------------------
Name (time in us)                                 Mean            OPS (Kops/s)              Median                 Min                 Max            Rounds
------------------------------------------------------------------------------------------------------------------------------------------------------------
test_compile[small-sqlite] (0001_1767205)     126.4679 (1.02)           7.9071 (0.98)     116.8920 (1.02)     107.5940 (1.0)      362.2370 (1.0)        4091
test_compile[small-sqlite] (NOW)              123.5511 (1.0)            8.0938 (1.0)      114.2470 (1.0)      111.5710 (1.04)     576.4930 (1.59)        237
------------------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------ benchmark 'test_complex_datatype_builtins[hash]': 2 tests -------------------------------------------------------
Name (time in ns)                                           Mean            OPS (Mops/s)              Median                 Min                   Max            Rounds
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_complex_datatype_builtins[hash] (0001_1767205)     320.1995 (1.0)            3.1231 (1.0)      320.0257 (1.0)      300.9918 (1.00)     2,825.9819 (1.0)       39219
test_complex_datatype_builtins[hash] (NOW)              326.7038 (1.02)           3.0609 (0.98)     321.0152 (1.00)     299.9732 (1.0)      4,447.9966 (1.57)      24506
------------------------------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------- benchmark 'test_complex_datatype_builtins[str]': 2 tests ------------------------------------------------------
Name (time in ns)                                          Mean            OPS (Mops/s)              Median                 Min                   Max            Rounds
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_complex_datatype_builtins[str] (0001_1767205)     280.2179 (1.0)            3.5687 (1.0)      277.0000 (1.0)      262.8230 (1.0)      2,184.1757 (1.0)      194970
test_complex_datatype_builtins[str] (NOW)              361.5560 (1.29)           2.7658 (0.78)     361.0039 (1.30)     339.9909 (1.29)     4,489.0039 (2.06)      28038
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------ benchmark 'test_complex_datatype_parse': 2 tests -----------------------------------------------------
Name (time in ns)                                  Mean            OPS (Mops/s)              Median                 Min                 Max            Rounds
-------------------------------------------------------------------------------------------------------------------------------------------------------------
test_complex_datatype_parse (0001_1767205)     211.7841 (2.71)           4.7218 (0.37)     210.0132 (2.72)     199.9724 (2.68)     480.9990 (2.16)        263
test_complex_datatype_parse (NOW)               78.1701 (1.0)           12.7926 (1.0)       77.3498 (1.0)       74.6400 (1.0)      222.2203 (1.0)      120541
-------------------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------- benchmark 'test_construction[large]': 2 tests -------------------------------------------------
Name (time in ms)                              Mean                OPS             Median                Min                Max            Rounds
-------------------------------------------------------------------------------------------------------------------------------------------------
test_construction[large] (0001_1767205)     12.0541 (1.08)     82.9597 (0.92)     12.0392 (1.08)     11.8476 (1.08)     12.3908 (1.08)         79
test_construction[large] (NOW)              11.1465 (1.0)      89.7140 (1.0)      11.1402 (1.0)      10.9469 (1.0)      11.4374 (1.0)          87
-------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------ benchmark 'test_construction[medium]': 2 tests ------------------------------------------------
Name (time in ms)                              Mean                 OPS            Median               Min                Max            Rounds
------------------------------------------------------------------------------------------------------------------------------------------------
test_construction[medium] (0001_1767205)     3.4197 (1.0)      292.4218 (1.0)      3.4113 (1.0)      3.3162 (1.0)       3.8114 (1.0)         211
test_construction[medium] (NOW)              4.4145 (1.29)     226.5270 (0.77)     4.2228 (1.24)     4.0087 (1.21)     45.9911 (12.07)       235
------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------- benchmark 'test_construction[small]': 2 tests ------------------------------------------------------
Name (time in us)                              Mean            OPS (Kops/s)             Median                Min                    Max            Rounds
----------------------------------------------------------------------------------------------------------------------------------------------------------
test_construction[small] (0001_1767205)     28.4667 (1.0)           35.1288 (1.0)      25.8790 (1.0)      24.8270 (1.0)      40,906.5860 (46.64)     26398
test_construction[small] (NOW)              35.2488 (1.24)          28.3698 (0.81)     34.0240 (1.31)     32.0200 (1.29)        877.0740 (1.0)       19800
----------------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------ benchmark 'test_execute[cast_to_dates]': 2 tests -----------------------------------------------------
Name (time in us)                                  Mean            OPS (Kops/s)              Median                 Min                 Max            Rounds
-------------------------------------------------------------------------------------------------------------------------------------------------------------
test_execute[cast_to_dates] (0001_1767205)     716.8095 (1.0)            1.3951 (1.0)      715.3870 (1.0)      706.8300 (1.01)     752.8980 (1.0)         131
test_execute[cast_to_dates] (NOW)              722.7204 (1.01)           1.3837 (0.99)     719.9350 (1.01)     697.7030 (1.0)      779.7090 (1.04)        539
-------------------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------- benchmark 'test_execute[cast_to_dates_from_strings]': 2 tests -------------------------------------------------
Name (time in ms)                                              Mean                OPS             Median                Min                Max            Rounds
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
test_execute[cast_to_dates_from_strings] (0001_1767205)     11.1532 (1.02)     89.6602 (0.98)     11.0492 (1.01)     10.8079 (1.03)     11.7695 (1.04)         44
test_execute[cast_to_dates_from_strings] (NOW)              10.9279 (1.0)      91.5089 (1.0)      10.9313 (1.0)      10.4906 (1.0)      11.2860 (1.0)          75
-----------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------- benchmark 'test_execute[high_card_group_by]': 2 tests ------------------------------------------------
Name (time in ms)                                     Mean                 OPS            Median               Min               Max            Rounds
------------------------------------------------------------------------------------------------------------------------------------------------------
test_execute[high_card_group_by] (0001_1767205)     4.0698 (1.0)      245.7108 (1.0)      4.0569 (1.0)      4.0198 (1.0)      5.5907 (1.34)        216
test_execute[high_card_group_by] (NOW)              4.1037 (1.01)     243.6831 (0.99)     4.1008 (1.01)     4.0604 (1.01)     4.1569 (1.0)         143
------------------------------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------- benchmark 'test_execute[high_card_grouped_rolling]': 2 tests --------------------------------------------------
Name (time in ms)                                              Mean               OPS              Median                 Min                 Max            Rounds
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_execute[high_card_grouped_rolling] (0001_1767205)     306.0074 (1.0)      3.2679 (1.0)      307.9083 (1.0)      299.7480 (1.0)      309.9615 (1.0)           5
test_execute[high_card_grouped_rolling] (NOW)              308.4888 (1.01)     3.2416 (0.99)     308.1797 (1.00)     304.5889 (1.02)     314.7687 (1.02)          5
-------------------------------------------------------------------------------------------------------------------------------------------------------------------

-------------------------------------------------- benchmark 'test_execute[high_card_grouped_rolling_udf_mean]': 2 tests ---------------------------------------------------
Name (time in ms)                                                       Mean               OPS              Median                 Min                 Max            Rounds
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_execute[high_card_grouped_rolling_udf_mean] (0001_1767205)     667.9235 (1.0)      1.4972 (1.0)      668.1975 (1.0)      661.6521 (1.0)      673.7776 (1.0)           5
test_execute[high_card_grouped_rolling_udf_mean] (NOW)              694.9095 (1.04)     1.4390 (0.96)     693.8664 (1.04)     691.0528 (1.04)     702.6791 (1.04)          5
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-------------------------------------------------- benchmark 'test_execute[high_card_grouped_rolling_udf_wm]': 2 tests ---------------------------------------------------
Name (time in ms)                                                     Mean               OPS              Median                 Min                 Max            Rounds
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_execute[high_card_grouped_rolling_udf_wm] (0001_1767205)     959.4514 (1.0)      1.0423 (1.0)      965.4468 (1.0)      944.7507 (1.0)      968.9484 (1.0)           5
test_execute[high_card_grouped_rolling_udf_wm] (NOW)              995.8587 (1.04)     1.0042 (0.96)     995.9132 (1.03)     992.4376 (1.05)     998.2770 (1.03)          5
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------

---------------------------------------------- benchmark 'test_execute[high_card_window_analytics_udf]': 2 tests -----------------------------------------------
Name (time in s)                                                  Mean               OPS            Median               Min               Max            Rounds
----------------------------------------------------------------------------------------------------------------------------------------------------------------
test_execute[high_card_window_analytics_udf] (0001_1767205)     5.2112 (1.00)     0.1919 (1.00)     5.2282 (1.01)     5.1611 (1.01)     5.2489 (1.0)           5
test_execute[high_card_window_analytics_udf] (NOW)              5.2032 (1.0)      0.1922 (1.0)      5.1913 (1.0)      5.1311 (1.0)      5.2981 (1.01)          5
----------------------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------- benchmark 'test_execute[low_card_grouped_rolling]': 2 tests -------------------------------------------------
Name (time in ms)                                            Mean                OPS             Median                Min                Max            Rounds
---------------------------------------------------------------------------------------------------------------------------------------------------------------
test_execute[low_card_grouped_rolling] (0001_1767205)     23.0196 (1.0)      43.4412 (1.0)      22.9772 (1.0)      22.8426 (1.0)      23.6287 (1.0)          19
test_execute[low_card_grouped_rolling] (NOW)              23.1554 (1.01)     43.1865 (0.99)     23.0906 (1.00)     22.9259 (1.00)     24.0911 (1.02)         16
---------------------------------------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------- benchmark 'test_execute[low_card_grouped_rolling_udf_mean]': 2 tests --------------------------------------------------
Name (time in ms)                                                      Mean               OPS              Median                 Min                 Max            Rounds
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_execute[low_card_grouped_rolling_udf_mean] (0001_1767205)     396.7834 (1.0)      2.5203 (1.0)      396.5497 (1.0)      396.3714 (1.0)      397.8298 (1.0)           5
test_execute[low_card_grouped_rolling_udf_mean] (NOW)              412.5315 (1.04)     2.4241 (0.96)     412.6421 (1.04)     408.5424 (1.03)     418.8362 (1.05)          5
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------ benchmark 'test_execute[low_card_grouped_rolling_udf_wm]': 2 tests -----------------------------------------------------
Name (time in ms)                                                      Mean               OPS                Median                 Min                   Max            Rounds
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_execute[low_card_grouped_rolling_udf_wm] (0001_1767205)       981.5894 (1.0)      1.0188 (1.0)        981.7944 (1.0)      971.6563 (1.0)        992.9947 (1.0)           5
test_execute[low_card_grouped_rolling_udf_wm] (NOW)              1,011.1251 (1.03)     0.9890 (0.97)     1,007.8039 (1.03)     984.8895 (1.01)     1,037.8424 (1.05)          5
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------- benchmark 'test_execute[low_card_window_analytics_udf]': 2 tests -------------------------------------------------
Name (time in ms)                                                 Mean                OPS             Median                Min                Max            Rounds
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_execute[low_card_window_analytics_udf] (0001_1767205)     14.4416 (1.0)      69.2446 (1.0)      14.3829 (1.0)      14.2050 (1.0)      14.8941 (1.0)          68
test_execute[low_card_window_analytics_udf] (NOW)              14.6908 (1.02)     68.0699 (0.98)     14.6496 (1.02)     14.5591 (1.02)     15.3610 (1.03)         66
--------------------------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------ benchmark 'test_execute[multikey_group_by_with_mutate]': 2 tests -----------------------------------------------
Name (time in ms)                                                Mean                 OPS            Median               Min               Max            Rounds
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
test_execute[multikey_group_by_with_mutate] (0001_1767205)     6.5738 (1.0)      152.1197 (1.0)      6.5564 (1.0)      6.3346 (1.0)      6.9156 (1.0)          26
test_execute[multikey_group_by_with_mutate] (NOW)              6.6082 (1.01)     151.3277 (0.99)     6.5899 (1.01)     6.5011 (1.03)     6.9855 (1.01)        116
-----------------------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------- benchmark 'test_execute[multikey_sort]': 2 tests -------------------------------------------------
Name (time in ms)                                 Mean                OPS             Median                Min                Max            Rounds
----------------------------------------------------------------------------------------------------------------------------------------------------
test_execute[multikey_sort] (0001_1767205)     14.7262 (1.01)     67.9061 (0.99)     14.6643 (1.01)     14.3122 (1.0)      16.9947 (1.11)         68
test_execute[multikey_sort] (NOW)              14.5828 (1.0)      68.5737 (1.0)      14.5219 (1.0)      14.3346 (1.00)     15.2814 (1.0)          63
----------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------- benchmark 'test_execute[multikey_sort_projection]': 2 tests -------------------------------------------------
Name (time in ms)                                            Mean                OPS             Median                Min                Max            Rounds
---------------------------------------------------------------------------------------------------------------------------------------------------------------
test_execute[multikey_sort_projection] (0001_1767205)     16.6719 (1.02)     59.9811 (0.98)     16.5828 (1.03)     16.1205 (1.02)     17.3984 (1.0)          12
test_execute[multikey_sort_projection] (NOW)              16.2968 (1.0)      61.3619 (1.0)      16.1096 (1.0)      15.7497 (1.0)      18.7601 (1.08)         62
---------------------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------ benchmark 'test_execute[simple_sort]': 2 tests ------------------------------------------------
Name (time in ms)                              Mean                 OPS            Median               Min                Max            Rounds
------------------------------------------------------------------------------------------------------------------------------------------------
test_execute[simple_sort] (0001_1767205)     9.5880 (1.00)     104.2975 (1.00)     9.4588 (1.0)      9.2956 (1.0)      11.5606 (1.15)        100
test_execute[simple_sort] (NOW)              9.5547 (1.0)      104.6604 (1.0)      9.5262 (1.01)     9.4400 (1.02)     10.0517 (1.0)         100
------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------ benchmark 'test_execute[simple_sort_projection]': 2 tests ------------------------------------------------
Name (time in ms)                                         Mean                 OPS            Median               Min                Max            Rounds
-----------------------------------------------------------------------------------------------------------------------------------------------------------
test_execute[simple_sort_projection] (0001_1767205)     9.4848 (1.02)     105.4319 (0.98)     9.4199 (1.01)     9.2038 (1.01)     10.7051 (1.09)         97
test_execute[simple_sort_projection] (NOW)              9.3020 (1.0)      107.5032 (1.0)      9.3398 (1.0)      9.1088 (1.0)       9.8635 (1.0)          86
-----------------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------- benchmark 'test_large_expr_equals': 2 tests --------------------------------------------------------
Name (time in us)                               Mean                   OPS                Median                 Min                   Max            Rounds
------------------------------------------------------------------------------------------------------------------------------------------------------------
test_large_expr_equals (0001_1767205)     1,027.8201 (2.13)       972.9329 (0.47)     1,028.1650 (2.13)     997.7320 (2.13)     1,098.9540 (2.01)        580
test_large_expr_equals (NOW)                483.5667 (1.0)      2,067.9669 (1.0)        482.1350 (1.0)      468.8190 (1.0)        546.2460 (1.0)        1827
------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------- benchmark 'test_op_argnames': 2 tests ------------------------------------------------------
Name (time in ns)                       Mean            OPS (Mops/s)              Median                 Min                 Max            Rounds
--------------------------------------------------------------------------------------------------------------------------------------------------
test_op_argnames (0001_1767205)     145.7089 (1.01)           6.8630 (0.99)     144.5701 (1.01)     133.6500 (1.0)      483.4199 (1.69)      63654
test_op_argnames (NOW)              144.0390 (1.0)            6.9426 (1.0)      143.6699 (1.0)      135.4498 (1.01)     286.6398 (1.0)       70637
--------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------ benchmark 'test_op_args': 2 tests -------------------------------------------------------
Name (time in ns)                   Mean            OPS (Mops/s)              Median                 Min                   Max            Rounds
------------------------------------------------------------------------------------------------------------------------------------------------
test_op_args (0001_1767205)     239.0201 (2.15)           4.1837 (0.46)     236.1429 (2.13)     220.8565 (2.10)     2,025.2857 (7.92)     191571
test_op_args (NOW)              111.1200 (1.0)            8.9993 (1.0)      110.7098 (1.0)      105.2898 (1.0)        255.6900 (1.0)       69171
------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------- benchmark 'test_repr_huge_union': 2 tests ------------------------------------------------
Name (time in ms)                         Mean                 OPS            Median               Min               Max            Rounds
------------------------------------------------------------------------------------------------------------------------------------------
test_repr_huge_union (0001_1767205)     7.0058 (1.73)     142.7398 (0.58)     7.0054 (1.73)     6.8747 (1.72)     7.1193 (1.71)        131
test_repr_huge_union (NOW)              4.0583 (1.0)      246.4087 (1.0)      4.0588 (1.0)      4.0067 (1.0)      4.1538 (1.0)         238
------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------ benchmark 'test_repr_tpc_h02': 2 tests -----------------------------------------------
Name (time in ms)                      Mean                 OPS            Median               Min               Max            Rounds
---------------------------------------------------------------------------------------------------------------------------------------
test_repr_tpc_h02 (0001_1767205)     8.4282 (1.10)     118.6491 (0.91)     8.4272 (1.10)     8.3702 (1.10)     8.4992 (1.09)        115
test_repr_tpc_h02 (NOW)              7.6612 (1.0)      130.5270 (1.0)      7.6580 (1.0)      7.5756 (1.0)      7.8323 (1.0)         108
---------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by jreback** [comment]
@cpcloud which is the first PR that i should look?

**Comment by cpcloud** [comment]
@jreback The order I would like to merge these PRs is:

1. #3619 
2. #3613 
3. #3621 
4. #3594

**Review by jreback — APPROVED** [review]
seems fine

**Comment by jreback** [comment]
needs a rebase & if you can do that helpfer function

**Comment by cpcloud** [comment]
Yep, will wait until #3621 is landed to rebase.

**Pull request merged**
