### PR TITLE
refactor(risingwave): port to sqlglot

### PR DESCRIPTION
**Pull request by gforsyth**
xref #7909 

a lot of new passing tests -- some flakiness in `groupconcat` when it's used in a window.

failing tests are all assertion errors in `test_array`.

### CODE REVIEW

**Comment by cpcloud** [comment]
Looking into the rebase now...

**Comment by gforsyth** [comment]
ugh, I'll port over the hexdigest op stuff

**Comment by gforsyth** [comment]
> I have a fix for the Trino backend incoming.

oops, I don't think I stomped on this.  We definitely just fixed a bunch of the same stuff.  That'll teach me to ignore my email

**Comment by cpcloud** [comment]
Nah, you're good. I had already pushed the fix in a previous commit!

**Review by cpcloud — APPROVED** [review]
LGTM, great work!

**Pull request merged**
