### PR TITLE
Pushing the docs to GitHub pages from the CI

### PR DESCRIPTION
**Pull request by datapythonista**
Follow up of #2590. Pushes the docs to github pages, as it was done before from azure.

**Note** it requires #2637 for this to work.

### CODE REVIEW

**Comment by datapythonista** [comment]
This can be merged now, got the keys in place.

**Comment by jreback** [comment]
excellent!

**Comment by jreback** [comment]
hmm docs seem broken

**Comment by datapythonista** [comment]
Seems like GitHub pages has some cache, and things were broken. I recreated the repo, I think/hope when merging #2640 and the docs are pushed again, all should be working.

**Comment by jreback** [comment]
interesting getting
`Under maintainance, coming back in some minutes.` now :-<

**Comment by jreback** [comment]
@datapythonista any thoughts here?

**Comment by datapythonista** [comment]
Yes, sorry. I had to go out a bit. The message is a placeholder I added quickly to make sure the setup was working. It should just need to re-run the docs build, so the docs are pushed to the new repo. I did that, but I forgot to add again the deployment key after recreating the repo. The docs job is running again, I think when it finishes (in like 30 minutes), it should be working again.

Sorry for breaking the website, I'm on it, will leave it working.

**Pull request merged**
