### PR TITLE
refactor: remove the `timezone` argument from `to_timestamp`

### PR DESCRIPTION
**Pull request by cpcloud**
- refactor(timestamps): remove `timezone` argument to `to_timestamp` API
- chore: enable longer footers
- feat(duckdb): implement `to_timestamp`

### CODE REVIEW

**Review by kszucs — APPROVED** [review]
LGTM

**Comment by krzysztof-kwitt** [comment]
I wonder how this change will affect the `test_timestamp_comparison_filter` test for BigQuery. From what I can see, tests for BigQuery are not run on CI.

**Comment by cpcloud** [comment]
@krzysztof-kwitt Good question! We run the tests for BigQuery when a PR is merged to `master` and then fix anything broken in a follow-up. Any ibis contributor with the commit bit can run the those tests.

**Comment by cpcloud** [comment]
It looks like this _does_ break some tests, so thanks for the reminder and I'll fix them here.

**Pull request merged**
