### PR TITLE
refactor(analysis): remove `ScalarAggregate`, `reduction_to_aggregation` and `has_multiple_bases`

### PR DESCRIPTION
**Pull request by kszucs**
Most of the test suites do work, haven't checked impala yet. 

Apparently we no longer need the cross join, possibly due to recent changes.

### CODE REVIEW

**Comment by cpcloud** [comment]
This seems doable in 6.1, is it not?

**Comment by kszucs** [comment]
I would be a bit more defensive in this case, so my preference is to ship it with 7.0.

**Review by cpcloud — APPROVED** [review]
LGTM, nice work!

**Comment by cpcloud** [comment]
Note that I am removing the `result_handler` things in #6569.

**Comment by kszucs** [comment]
> Note that I am removing the `result_handler` things in #6569.

Even better, that annoyed me too.

**Pull request merged**
