### PR TITLE
chore(dev-tools): remove unused dependencies in conda environment files

### PR DESCRIPTION
**Pull request by cpcloud**
Remove some unused dependencies in our conda env files.

### CODE REVIEW

**Comment by ncclementi** [comment]
Thanks @cpcloud . I'll give these ones a try in the m2 and I'll get back to you.

**Review by ncclementi — COMMENTED** [review]
The arm64 environment works, only few requests: 
- Would you remove the same packages from the `environment-arm64-flink.yml` too? 
- Would you modify the name of the env to be just `ibis-dev` in both  environment-arm64.yml and `environment-arm64-flink.yml` ? (I forgot to clean this up on the previous PR) - unless we think the names are fine and it's safer to not override an existing dev environment.

**Comment by cpcloud** [comment]
@ncclementi The flink environment doesn't have any of these dependencies.

**Comment by ncclementi** [comment]
> The flink environment doesn't have any of these dependencies.

weird, I thought I started from a copy of the arm64 one.

Well it's good to go then. 🚀

**Review by ncclementi — APPROVED** [review]

**Comment by cpcloud** [comment]
Thanks for the review!

**Pull request merged**
