### PR TITLE
ENH: Allow execution of just bound parameters in the pandas backend

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by jreback** [comment]
was this not caching?

**Comment by cpcloud** [comment]
It's not a caching issue. It was erroring out before looking at anything beyond leaf data sources.

**Comment by cpcloud** [comment]
Anything beyond == results of data_preload + unbound parameters

**Comment by cpcloud** [comment]
Merging on green.

**Comment by cpcloud** [comment]
passing appveyor build here: https://ci.appveyor.com/project/cpcloud/ibis/build/1.0.1350

**Pull request closed without merging**
