### PR TITLE
OmniSciDB: add check in close method

### PR DESCRIPTION
**Pull request by anmyachev**

### CODE REVIEW

**Comment by anmyachev** [comment]
@xmnlab plz review :)

**Comment by xmnlab** [comment]
@anmyachev LGTM.

maybe with your new changes we can remove `hasattr(self, 'con') and ` from:

```python
    def __del__(self):
        """Close the connection when instance is deleted."""
        if hasattr(self, 'con') and self.con:
            self.close()
```

or maybe the entire `if` ...
what do you think?

**Comment by anmyachev** [comment]
> @anmyachev LGTM.
> 
> maybe with your new changes we can remove `hasattr(self, 'con') and ` from:
> 
> ```python
>     def __del__(self):
>         """Close the connection when instance is deleted."""
>         if hasattr(self, 'con') and self.con:
>             self.close()
> ```
> 
> or maybe the entire `if` ...
> what do you think?

I think this should work correctly. Let's look at CI.

**Comment by xmnlab** [comment]
it seems there is an indentation issue. you also can run `make develop` to install the project for development. it will install some pre-commit hooks to help to catch this kind of issues before do the commit.

**Comment by anmyachev** [comment]
> can you add a test which breaks on current master and this fixes.

I can’t, this change does not fix the error, but simply adds a property from `pymapd` public api.

**Comment by jreback** [comment]
> > can you add a test which breaks on current master and this fixes.
> 
> I can’t, this change does not fix the error, but simply adds a property from `pymapd` public api.

i am not sure what this means. if we don't have a test, how is this correct (and the prior is not)? sure you can't test everything, but it seems this is something that could be.

**Comment by datapythonista** [comment]
@anmyachev are you interested in continuing working with this?

As said, this should have a unit test. I assume if you're making these changes, is because this is fixing a problem (I guess the connection to omnisci is not being closed at some point). So, it would be good to have a test that checks that the connection is now being closed. Otherwise we can't know that this is working as expected. And if there are changes to this code in the future, that they are not breaking what you implemented here.

Also, please add a release note.

Thanks!

**Comment by datapythonista** [comment]
Closing as stale. @anmyachev please let me know if you want to continue working on this, and I'll reopen.

**Pull request closed without merging**
