### PR TITLE
DOC: Moving tutorial 6 to Impala docs

### PR DESCRIPTION
**Pull request by datapythonista**
Last tutorial. In this case, seems like `topk` is not working in SQLAlchemy backends (see #2612), so instead of porting the examples to the SQLite backend, I move that explanation to Impala. We can move it back in the future if `topk` becomes more widely supported. Same for self-joins.

There is one more small PR needed for an example in the user guide, and then we should be able to build the docs without the docker stuff, just with `make html`.

### CODE REVIEW

**Comment by jreback** [comment]
`/ibis/docs/source/backends/impala.rst:1445: WARNING: Explicit markup ends without a blank line; unexpected unindent.`

**Comment by datapythonista** [comment]
Fixed, thanks for the heads up!

**Review by jreback — CHANGES_REQUESTED** [review]
maybe i am reading this wrong but there seems to be a lot of docs on impala - sure it's non executable code

but would much rather move this to sqlite as u have been doing

**Comment by jreback** [comment]
ahh i see your comment

we should de-emphasize impala 
self join can be done in sql and topk could be in big query

**Comment by datapythonista** [comment]
What do you think if I move this to the user guide then, instead of the tutorial? I don't think having things not well supported in the tutorial is ideal. Thr user guide probably is better than the Impala docs if this works in few. I'll leave the examples not running, so Impala is not needed to build the docs.

**Comment by jreback** [comment]
yeah user guide would be +1

**Comment by jreback** [comment]
hmm i put the failures in this issue: https://github.com/ibis-project/ibis/issues/2629

seem unrleated (maybe graph viz update)?

**Comment by datapythonista** [comment]
> seem unrleated (maybe graph viz update)?

Yes, clearly unrelated. I'm having a look, strange that only fails in Windows.

**Comment by jreback** [comment]
@datapythonista if you can rebase

**Comment by datapythonista** [comment]
All green now. Thanks!

**Comment by jreback** [comment]
thanks @datapythonista

**Pull request merged**
