### PR TITLE
feat(clickhouse): add ability to pass arbitrary kwargs to Clickhouse do_connect

### PR DESCRIPTION
**Pull request by mharrisb1**
From my experience using [clickhouse-driver](https://github.com/mymarilyn/clickhouse-driver), the user needs a decent bit of flexibility when configuring the client. For example, this is a common Client constructor used for our Clickhouse deployment:

```python
import os

from clickhouse_driver import Client

client = Client(
    host=os.getenv("CH_HOST"),
    user=os.getenv("CH_USER"),
    password=os.getenv("CH_PASSWORD"),
    port=9440,
    secure=True,
    verify=False,
    database="default",
    compression=True,
    settings={"use_numpy": True},
)
```

Currently, I cannot get the Ibis Clickhouse connection to work because I can't pass in these kwargs.

I would like the ability to do:

```python
import os

import ibis

connection = ibis.clickhouse.connect(
    host=os.getenv("CH_HOST"),
    user=os.getenv("CH_USER"),
    password=os.getenv("CH_PASSWORD"),
    port=9440,
    secure=True,
    verify=False,
    compression=True,
    settings={"use_numpy": True},
    send_receive_timeout = 86400,
    connect_timeout = 86400
)
```

References for setting clickhouse-driver settings:

- https://clickhouse-driver.readthedocs.io/en/latest/features.html#settings
- https://github.com/mymarilyn/clickhouse-driver/issues/196
- https://github.com/mymarilyn/clickhouse-driver/blob/4bbdef9a5a47a62843181f37554d1dc96e709e51/clickhouse_driver/client.py#L20

### CODE REVIEW

**Comment by cpcloud** [comment]
This looks good, I will fix up the commit messages and merge.

**Comment by cpcloud** [comment]
@mharrisb1 It seems like I can't push to your fork. Can you enable that? Alternatively can you change the commit message to be:

```
feat(clickhouse): add ability to pass arbitrary kwargs to Clickhouse do_connect
```

You also need to run `black .` to conform to the formatting we use.

**Comment by mharrisb1** [comment]
Thankss @cpcloud I added you as a collaborator on the forked repo. Let me know if that solves the problem. I also just commited the formatting changes from black with the commit message you suggested. Let me know if that does the trick

**Comment by cpcloud** [comment]
Whoops, I have no idea what happened there. I just force pushed after an interactive rebase.

**Comment by cpcloud** [comment]
@mharrisb1 Can you open a PR with `HEAD` from your fork's `master` branch?

**Comment by mharrisb1** [comment]
@cpcloud https://github.com/ibis-project/ibis/pull/4263

**Pull request closed without merging**
