### PR TITLE
fix: implement count on tables for pyspark

### LINKED ISSUE #2879: test: fix pyspark ddl tests inherited from the old spark backend
The PySpark backend used to subclass the legacy Spark backend. Including the DDL functionality. When the old Spark backend was deleted in #2869, the functionality that PySpark used to inherit, was moved to the PySpark test. In the case of DDL, when the tests were moved from the Spark backend to the PySpark one, looks like some of the functionality inherited by the PySpark backend was not working. Since the DDL functionality was tested only for the Spark backend, it wasn't known until tests were moved that some things were broken in the PySpark backend.

The tests that are failing are (all them in `ibis/backends/pyspark/tests/test_ddl.py`):
- `test_truncate_table`
- `test_truncate_table_expression`
- `test_insert_table`
- `test_create_table_reserved_identifier`
- `test_create_table_or_temp_view_from_csv`

All them have been xfailed for now, but should be eventually fixed (or the functionality should be removed if it doesn't make sense to have it in the PySpark backend).

### PR DESCRIPTION
**Pull request by cpcloud**
Closes #2879. We really need to avoid xfailing without understanding the reason for the failure.

### CODE REVIEW

**Comment by cpcloud** [comment]
@icexelloss Any chance you can give a quick review here?

**Comment by cpcloud** [comment]
@jreback @icexelloss Thoughts? Would like to merge this.

**Comment by cpcloud** [comment]
Going to merge this in the interest of fixing the associated bug.

**Review by icexelloss — APPROVED** [review]
lGTM

**Pull request merged**
