### PR TITLE
Fix multiple CI issues

### LINKED ISSUE #1695: test: investigate clickhouse test_insert fail
#1696  adds skip decorator on  clickhouse test_insert temporarily

### PR DESCRIPTION
**Pull request by xmnlab**
The test_insert fail should be investigated #1695

### CODE REVIEW

**Comment by xmnlab** [comment]
@cpcloud @kszucs 

it seems now it is raising some errors related to #1689

maybe we should add this skip on #1689? what do you think about that?

**Comment by xmnlab** [comment]
I am adding commits from #1689

**Comment by kszucs** [comment]
Had to disable conda build steps until We update the recipe in the conda forge feedstock. There were a lot of changes around conda-forge lately, compiler migration, dropped python3.5 support and ibis also dropped python2.7 support.

**Comment by kszucs** [comment]
Right after this PR We should update our builds to test against python 3.7 #1544

**Comment by xmnlab** [comment]
awesome! thank you so much @kszucs !

**Comment by kszucs** [comment]
Not done yet, there must be a strange dependency problem in the `docs` build. Investigating...

**Comment by xmnlab** [comment]
@kszucs I changed the version of pyarrow and pymapd on requrirements-docs-3.6.yml

**Comment by kszucs** [comment]
@cpcloud @xmnlab please review
I'm merging a little later.

**Comment by kszucs** [comment]
Sadly I had to disable multiple tests, but not critical ones - We'll fix them later.

**Comment by kszucs** [comment]
Ahh flake8 was just updated, causing build errors on master. The fix is in #1659

**Comment by xmnlab** [comment]
thanks for the update @kszucs the others PR I am working.

**Pull request closed without merging**
