### PR TITLE
chore: check builds for the-epic-split after rebase

### PR DESCRIPTION
**Pull request by kszucs**
- feat(duckdb-geospatial): enable use of literals
- test(duckdb-geospatial): add test for literals support
- chore: fix commit hash for git-blame-ignore-rev
- feat(flink): add new temporal operators
- feat(flink): implement struct field, clean up literal, and adjust timecontext test markers (#7997)
- ci: wire up new cache via setup-python
- ci: use new ci-doctest to run doctests in the poetry environment
- ci: properly install sqlalchemy2 deps; avoid relocking as a dependency
- test(duckdb-geospatial): fix incomplete skipping
- fix(api): deferred values are not truthy
- docs(meta): add goatcounter to header of all quarto pages
- docs(blog): redux array blog with equivalent duckdb and bq expressions
- fix(mutate/select): ensure that unsplatted dictionaries work in `mutate`and`select` APIs (#8014)
- fix(docs): surround executable code blocks with interactive mode on/off
- chore(flake/nixpkgs): `cc3ab0e4` -> `0799f514`
- chore(flake/nixpkgs): `0799f514` -> `b4ee3c3c`
- test(flink): deep dive on the tests marked for Flink in test_json.py (#7908)
- fix(deps): update dependency pyarrow to v15
- chore: bump requirements-dev.txt
- fix(duckdb): ensure that casting to floating point values produces valid types in generated sql
- fix(datatypes): ensure that array construction supports literals and infers their shape from its inputs (#8049)
- feat(examples): add `zones` geojson example (#8040)
- docs: fix rolling date on bigquery/duckdb array blog (#8059)
- docs: blog for the 1 billion row challenge (#8004)
- docs: add quotes around install in 1brc post (#8065)
- chore(deps): update bitnami/minio docker tag to v2024.1.18
- docs(pandas): fix format for kwarg warning callout
- docs(blog): show how to install geospatial dependencies
- chore(flake/nixpkgs): `b4ee3c3c` -> `15ff1758`
- docs: ibis-analytics blog post (#7990)
- chore(deps): update flink docker tag to v1.18.1 (#8084)
- docs(blog): update geospatial - no need to_array()
- fix(pandas): support non-string categorical columns
- ci(docker): yes -> "yes" to avoid yaml parsing weirdness
- fix(examples): use anonymous access when reading example data from GCS
- docs: document possible range of seed values to `Table.sample`
- chore(deps): update peter-evans/create-issue-from-file action to v5
- chore(deps): update peter-evans/create-or-update-comment action to v4
- refactor(flink): expose `raw_sql` over `_exec_sql`
- chore(deps): update peter-evans/find-comment action to v3
- docs(style): add style guide to contributing (#8092)
- chore(deps): update trinodb/trino docker tag to v437
- chore(flake/nixpkgs): `15ff1758` -> `7ac72b3e`
- chore: escape "\." in re_split() docstring
- fix(deps): update dependency black to v24
- chore(deps): relock
- fix(polars): avoid using unnecessary subquery for schema inference
- build(docker): clean up minio setup
- build(docker): remove extraneous druid docker volumes
- chore(deps): update dependency pytest to v8
- test(postgres): remove usefixtures mark from fixture
- test(tpch): remove `_fixtureinfo.argnames` hack
- test: fix and enable hypothesis profiles
- ci: run setuptools check tests in parallel
- ci: cache based on requirements-dev.txt for setuptools ci check
- chore(deps): remove undefined `exasol` extra from `sqlalchemy-exasol` dependency
- feat(flink): export result to pyarrow
- chore: handle the no-batches case in `to_pyarrow()`
- feat(risingwave): init impl for Risingwave (#7954)
- build(docker): simplify risingwave docker setup (#8126)
- docs(random): document behavior of repeated use of ibis.random() instance
- test(doctest): add range builtin to doctest namespace
- feat(mssql): add hashbytes and test for binary output hash fns (#8107)
- chore: disable renovate dependency dashboard (#8139)
- test(risingwave): add notimpl markers for new hexdigest tests (#8140)
- fix(sqlglot): stop using removed singletons for true, false, null
- chore(flake/nixpkgs): `7ac72b3e` -> `d3c09ae0`
- chore(deps): update clickhouse/clickhouse-server docker tag to v24
- build(deps): bump aiohttp from 3.9.1 to 3.9.2
- chore(deps): relock
- chore(deps): update bitnami/minio docker tag to v2024.1.29
- revert: chore(deps): update clickhouse/clickhouse-server docker tag to v24
- docs: kedro blog post link (#8150)
- fix(repr): force exception message to console in IPython in interactive mode
- docs(geospatial): add examples for duckdb supported  methods (#8128)
- feat(flink): implement array operators (#7951)
- test(ir): reorganize ibis/tests/expr to enable running the tests without a functional backend
- test(sql): move sql tests requiring a functional backend from `ibis/tests/sql` to `ibis/backends/tests/sql`
- test(backends): move backends dependent benchmarks to ibis/backends/tests/
- test(ir): ensure that no backends are required to run the core tests
- chore(ci): skip running backend tests on the-epic-split branch
- chore(ci): change the core testing command since the core marker is completely broken without the backend tests
- chore(ci): temporarily disable test_doctests job
- chore(ci): add todo note about restoring the previous ci-check command
- test(ir): ensure that no backends are required to run the core tests
- refactor(ir): split the relational operations
- refactor(ir): wrap `JoinChain.first` in `ops.SelfReference` similar to the rest of the join tables
- test(ir): cover constructing reductions in the core test suite
- refactor(ir): add `JoinTable` operation unique to `JoinChain` instead of using the globally unique `SelfReference`
- fix(decompile): ensure that `SelfReference` is decompiled with a call to `.view()`
- refactor(ir): support join of joins while avoiding nesting
- feat(sql): lower expressions to SQL-like relational operations
- refactor(duckdb): initial cut of sqlglot DuckDB compiler
- refactor(duckdb/clickhouse): implement sqlglot backends and re-enable ci
- feat(datafusion): port to new sqlglot backend
- refactor(compilers): conslidate StringJoin impl
- feat(common): add `Dispatched` base class for convenient visitor pattern implementation
- refactor(duckdb): remove the need for a specialized `_to_geodataframe` method
- fix(duckdb): ensure that create_schema and create_database are actually tested
- refactor(ir): stricter scalar subquery integrity checks
- feat(common): add a memory efficient `Node.map()` implementation
- fix(common): intermediate result removal fails if there are duplicated dependencies
- refactor(api): revamp `asof` join predicates
- fix(ir): self reference fields were incorrectly dereferenced to the parent relation
- fix(rewrites): add missing filter arguments for `node.replace()` calls
- refactor(snowflake): use sqlglot for the snowflake backend
- refactor(common): support union types as well as forward references in the dispatch utilities
- ci(snowflake): enable for `the-epic-split` branch
- fir(ir): `asof` join `tolerance` parameter should post-filter and post-join instead of adding a predicate
- feat(duckdb): support `asof` joins including `tolerance` parameter
- ci: remove `merge_group` (#7899)
- refactor(pandas): port the pandas backend with an improved execution model (#7797)
- chore(deps): relock
- ci: comment out sys-deps step
- chore: remove duplicate `distinct` decompile rule
- ci: install decompiler as extra not as its own dependency (#7901)
- fix(conversion): convert decimals to the exact precision and scale requested by the input type
- test(snowflake): fix expected decimal results
- test(duckdb): relax exact type check in decimal literal assertion
- refactor(sqlglot): various sqlglot compiler and backend clean ups (#7904)
- refactor(polars): update the polars backend to use the new relational abstractions (#7868)
- feat(trino): port to sqlglot
- fix(polars): force null sorting to match the rest of ibis
- test(pandas): ignore array size warning
- refactor(postgres): port to sqlglot (#7877)
- refactor(mysql): port to sqlglot (#7926)
- refactor(sqlglot): remove duplicated simple compilation rules and sort
- chore(deps): bump sqlglot and regen sql
- fix(duckdb): add `flip_coordinates` translation to sqlglot duckdb backend
- fix(snowflake): use `_safe_raw_sql` for `insert` implementation
- fix(mysql): remove not-allowed frame clause from rank window function
- test(postgres): use DBAPI instead of sqlalchemy apis in timezone test
- test(postgres): remove test that no longer works
- test(pandas): use the correct error type when xfailing for compound-sort-key rank
- refactor(ir): give unbound tables namespaces
- chore(duckdb/mysql): remove dead code and comment
- refactor(sqlglot): remove duplicate `StringAscii` definitions
- chore(sqlglot): deduplicate pad functions
- refactor(sqlglot): make anonymous functions easier to use and remove `array_func` hack
- test(backends): make null results try_cast test agnostic to nan vs None
- refactor(sqlglot): use a more backend-agnostic expression for non-finite constants
- refactor(sqlglot): clean up `explode` usage
- refactor(pyspark): reimplement the backend using the new relational operations an spark SQL
- feat(pyspark): add support for PySpark 3.5
- refactor(pyspark): remove sqlalchemy dependency from pyspark
- chore(deps): bump pyspark to 3.5 in poetry lock file
- fix(ir): only dereference comparisons not generic binary operations
- chore: rename to `dereference_comparison`
- chore(deps): relock
- test(generic): clean up try_cast to null test
- fix(polars): user newer `drop` API to avoid deprecation warning
- fix(polars): user newer `drop` API in asof join implementation
- refactor(druid): port to sqlglot
- refactor(impala): port to sqlglot
- refactor(pandas): simplify pandas helpers
- chore(impala): remove unused imports
- refactor(bigquery): port to sqlglot
- chore: add docstring for null ordering transform
- chore(bigquery-datatypes): fix type annotations and raise uniform error types for datatype conversion
- ci(bigquery): install geospatial extra
- test: remove unused `spread_type` function
- test: account for new error type
- test(bigquery): skip geospatial execution test when geopandas not installed
- fix(snowflake): handle udf function naming
- refactor(exasol): port to sqlglot (#8032)
- ci(exasol): run ci serially (#8042)
- feat(sql): extract common table expressions
- chore(sql): regenerate snapshots for clickhouse, duckdb and postgres
- chore(sql): regenerate snapshots for snowflake
- chore(sql): regenerate snapshots for bigquery
- chore(sql): regenerate snapshots for pyspark
- chore(sql): regenerate snapshots for trino
- chore(impala): regen snapshots
- fix(trino): compile property literal values directly instead of going throughh the pipeline
- ci(impala): run tests in series
- chore(exasol): avoid complex websocket callback for inserting memtables
- test(exasol): account for unordered results in window function tests
- test(duckdb): test that column name case is preserved when inserting
- refactor(oracle): port to sqlglot (#8020)
- chore(deps): remove sqlalchemy dependencies from oracle extra
- refactor(mssql): port to sqlglot
- fix(sql): don't generate table aliases for `ops.JoinLink`
- chore(impala): regen snapshots
- test(markers): add tests for custom markers
- fix(duckdb): allow passing both overwrite and temp to create_table
- refactor(polars): allow passing temp=False to polars create_table
- refactor(exasol): add temp kwarg to create_table for api consistency
- test(backends): add test for overwrite and temp intersection in create_table
- fix(oracle): enable dropping temporary tables
- fix(oracle): clean up memtables at exit
- fix(oracle): allow passing both overwrite and temp to create_table
- refactor(oracle): simplify oracle timestamp overrides
- fix(api): forbid using `asc`/`desc` in selections
- fix(api): support passing literal booleans to `filter`
- test(api): add union aliasing test
- fix(polars): reference the correct field in the `ops.SelfReference` rule
- test(polars): enable xpassing test
- test(duckdb): move tests to specific backend test suites
- test(duckdb): run test in subprocess to avoid setting the default backend
- refactor(sqlite): port to SQLGlot (#8154)
- refactor(sql): remove temporary table creation when using inline sql (#8149)
- refactor(sql): reorganize sqlglot rewrites

### CODE REVIEW

**Comment by cpcloud** [comment]
The failing nix builds will not pass until the RisingWave sqlglot port (#8171) is merged.

**Comment by cpcloud** [comment]
This should be good to go to force push to `the-epic-split`.

**Comment by kszucs** [comment]
Need to cherry-pick #8171

**Comment by kszucs** [comment]
Need to cherry-pick https://github.com/ibis-project/ibis/pull/8005

**Comment by kszucs** [comment]
Need to cherry-pick https://github.com/ibis-project/ibis/pull/8124

**Pull request closed without merging**
