### PR TITLE
feat(trino): support temporal operations

### LINKED ISSUE #7353: feat(trino): support temporal arithmetic operations
### Discussed in https://github.com/ibis-project/ibis/discussions/7351

<div type='discussions-op-text'>

<sup>Originally posted by **stereoF** October 13, 2023</sup>
**The codes:**

```python
# Add 3 days to the register_time
adjusted_time = filtered_df_user.register_time + ibis.interval(days=3)

# Extract year, month, and day from the adjusted timestamp
year = adjusted_time.year().cast('string')
month = adjusted_time.month().cast('string').lpad(2, '0')
day = adjusted_time.day().cast('string').lpad(2, '0')

# Concatenate the components 
date_str = year + month + day

# Convert the concatenated string to int32
formatted_date = date_str.cast('int32')

# Add the new column to df_user
filtered_df_user = filtered_df_user.mutate(formatted_date=formatted_date)

filtered_df_user.head(5).execute()
```

Error message：

```
---------------------------------------------------------------------------
OperationNotDefinedError                  Traceback (most recent call last)
/home/zhongminhu/code/ltv_pred/construct_dataset_ibis.ipynb Cell 20 line 1
----> [1](vscode-notebook-cell://wsl%2Bubuntu/home/zhongminhu/code/ltv_pred/construct_dataset_ibis.ipynb#X43sdnNjb2RlLXJlbW90ZQ%3D%3D?line=0) filtered_df_user.head(5).execute()

File [~/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ibis/expr/types/core.py:300](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/zhongminhu/code/ltv_pred/~/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ibis/expr/types/core.py:300), in Expr.execute(self, limit, timecontext, params, **kwargs)
    273 def execute(
    274     self,
    275     limit: int | str | None = 'default',
   (...)
    278     **kwargs: Any,
    279 ):
    280     """Execute an expression against its backend if one exists.
    281 
    282     Parameters
   (...)
    298         Keyword arguments
    299     """
--> 300     return self._find_backend(use_default=True).execute(
    301         self, limit=limit, timecontext=timecontext, params=params, **kwargs
    302     )

File [~/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ibis/backends/base/sql/__init__.py:234](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/zhongminhu/code/ltv_pred/~/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ibis/backends/base/sql/__init__.py:234), in BaseSQLBackend.execute(self, expr, params, limit, **kwargs)
    232 kwargs.pop('timecontext', None)
    233 query_ast = self.compiler.to_ast_ensure_limit(expr, limit, params=params)
...
    243     return formatter(self, op)
    244 else:
--> 245     raise com.OperationNotDefinedError(f'No translation rule for {type(op)}')

OperationNotDefinedError: No translation rule for <class 'ibis.expr.operations.temporal.TimestampAdd'>

```

</div>

### PR DESCRIPTION
**Pull request by cpcloud**
This PR adds support for the various temporal arithmetic operations: 

- `TimestampAdd`: `timestamp + interval`
- `TimestampSub`: `timestamp - interval`
- `TimestampDiff`: `timestamp - timestamp`
- `DateAdd`: `date + interval`
- `DateSub`: `date - interval`
- `DateDiff`: `date - date`
- `IntervalAdd`: `interval + interval`
- `IntervalSubtract`: `interval - interval`
- `IntervalFromInteger`: convert an integer to an interval

Closes #7353.

### CODE REVIEW

**Comment by cpcloud** [comment]
Ah, looks like I need to regenerate the TPC-H code for Trino.

**Review by jcrist — APPROVED** [review]

**Comment by stereoF** [comment]
How can I upgrade to the new version that includes this update and use it?

**Comment by stereoF** [comment]
It works well after upgrading to 8.0.0.dev110

**Comment by cpcloud** [comment]
Sweet!

**Pull request merged**
