### PR TITLE
Remove impala compile dependency in tests/sql/test_compiler

### PR DESCRIPTION
**Pull request by matthewmturner**
First step of fixing #2478 .

### CODE REVIEW

**Comment by matthewmturner** [comment]
should I move the tests that use `impala.compile` to `backends/impala/tests` for now and we can make a new issue to test for the same test cases in `tests/sql` once refactoring is done?

**Comment by datapythonista** [comment]
> should I move the tests that use `impala.compile` to `backends/impala/tests` for now and we can make a new issue to test for the same test cases in `tests/sql` once refactoring is done?

I guess if `impala.compile` is being called, those are specific to impala, and will still be after any refactoring. But if you can have a quick look and understand what's being tested, and guess why they seem to be in the wrong place, that would be useful.

The general idea is that the tests should be in the backend they are testing, or in the code if they are not specific to a backend. If we for whatever reason wanted to delete the impala backend, our tests would be failing now after deleting the `backends/impala` directory. That shouldn't be true, for impala or any other backend. for the base backends, should be the same case, except that the backends they depend on should of course be deleted too.

I don't think I know more about that code than you do, so you can use your common sense, I'm sure it'll be all right. :)

Thanks for working on this!

**Comment by matthewmturner** [comment]
One interesting thing that i found is:

https://github.com/ibis-project/ibis/blob/46b8cefef1d645368373f628eec52c291a04f3c5/ibis/tests/expr/mocks.py#L385

The `MockConnection` that is used for testing has a TODO for being renamed to `MockImpalaConnection`.  Plus the next TODO is `Should some tests using MockImpalaConnection really use MockAlchemyConnection instead?`

It seems there has been some thought to this already.  I have a question on this though.  From my understanding, impala is a backend and sqlalchemy is a ORM that is used as middle layer between ibis and given backends.  wouldnt it be hard to replace a backend test with sqlalchemy? unless the default is to apply it to something like sqlite?

Can you clarify what you meant by "or in the code if they are not specific to a backend"?  From what i see of the expected SQL results is that they look pretty standard - so unless im missing something it wouldnt appear that the test cases are specific to impala.

Also interestingly sometimes `ibis.impala.compile` is used to generate the `result_sql` and sometimes `to_sql` from `ibis.impala.compiler`.  So im not sure why one is used sometimes over the other.  `to_sql` is used much more. from the failed tests though i need to look deeper why none of those are failing if they are leveraging similar backend.

i see that `ibis/sql/compiler.py` has a `_to_sql` function but it is not implemented, so im not sure if thats what would have been used if the impala compiler was to be replaced by a generic one if the tests were deemed generic.

my inclination to start would be to move the tests using `impala.compile` to the `impala/tests` and use the loose assumption for now that `to_sql` is meant for generic sql tests.  unless you say otherwise ill move forward with that.

**Comment by datapythonista** [comment]
Thanks for researching this @matthewmturner.

Let me start by the intended scenario:
- Ibis is generic, doesn't know about any backend, but knows the concept of backend, and backends need to implement certain functions that when called will be generating SQL in a particular dialect
- Impala is just one of those backends, could be a separate project, and if the impala backend is not installed, Ibis doesn't know anything at all about Impala
- Backends need to implement a compile function, which generates the SQL. There are two possible compilers to use, a custom one implemented by Ibis, or the SQLAlchemy one (I think ideally we would just have the SQLAlchemy one, and not reinvent the wheel, but let's forget about this for now). Every backend (except pandas which is special and doesn't compile to SQL) use one of the two compilers. SQLite, Postgres and MySQL use the SQLAlchemy compliler, and the rest use the custom compiler

Now, we have the not so ideal scenario, where we have some technical debt because of historical reasons:
- Ibis was built for Impala
- There was no generic compiler, only the Ibis compiler
- When new backends were implemented (e.g. Bigquery), instead of implementing their own compiler, they used the Impala one, because most of the compiler is common to any SQL flavor
- Backends have weird dependencies, because if you only want bigquery, you need to load the Impala backend, and to load it, you need impyla, the impala backend dependency, which doesn't make any sense, since you want bigquery, not impala
- Even if there are many weird dependencies, most of the functionality is quite well decoupled, so just moving to new directories/files is fixing the problem
- Few files, like `test_compiler.py` seem to be mixing things too much. No file should be depending on impala and sqlalchemy at the same time, since those are independent and mutually exclusive base backends. Anything generic in impala should be moved to the new generic base backend `backends/base_sql`. Anything related to the base sqlalchemy backend should be moved to `backends/base_sqlalchemy`.

So, to summarize, backends should be based in one of `base_sql` or `base_sqlalchemy`. In my opinion, in the long term we would prefer that all them are based in sqlalchemy, since `base_sql` is just repeating what sqlalchemy provides. That would of course mean that to implement an Ibis backend you should first implement an sqlalchemy engine if it doesn't exist. Whether that happens or not, we would like to have things structured in a way that things are correctly decoupled:
- Backends directories only have what is specific to that backend (Impala has many generic things reused by others)
- The base backends have the common code share among the same type of backend (sqlalchemy, custom compiler, and we also have file based backends, that depend on pandas, that's a different category)
- If eventually one of those directories is not needed (a backend is moved out or deprecated, a base backend is obsolete because all backends depend on another base...), we should be able to remove its directory, and nothing else, and things should just continue working for the rest

Let me know if you have any further question. Thanks a lot for helping with all this.

**Comment by matthewmturner** [comment]
Dont think i ever thanked you for that explanation - much appreciated.  Certainly helped provide context on current state and gives me an idea of the vision.  

I tried to move the tests that use impalas `compile` method to `impala/tests/test_sql.py`.  test results so far are green (still waiting on impala tests though to ensure i moved them correctly) - but im not sure if this aligns to your vision primarily because its not obvious to me that these tests are specific to impala - they seem generic (but im not familiar with impala sql so any third party opinion is welcome).  i guess i see it as a tactical fix to enable the broader backend refactoring until a `base_sql  ` or `base_sqlalchemy` compiler could be used on those tests if they are in fact generic.

What do you think?

**Comment by datapythonista** [comment]
I don't know the details of that code either, but I think you're right.

I agree those tests aren't testing impala specific stuff. I think the solution is not to move the tests into Impala, but to move the impala compiler stuff to `base_sql`. I think the impala compiler, and `ImpalaSelect`... are all generic. I think we need to move that to `base_sql` first, and then the move here will make sense. Does this sound reasonable to you?

**Comment by jreback** [comment]
@matthewmturner can you merge master and then ping on green.

**Comment by matthewmturner** [comment]
@datapythonista sounds reasonable to me.  ill create another PR to move generic Impala functionality to `base_sql` and then come back to this and update the tests to use the new `base_sql` functionality.

@jreback we're going to come back to this and use a different approach (above).  let us know if you have any additional thoughts.

**Comment by jreback** [comment]
can u merge master

**Comment by matthewmturner** [comment]
@datapythonista @jreback ill merge master on this next. Let me know if anything else needed on impala side before next release.

**Comment by datapythonista** [comment]
> @datapythonista @jreback ill merge master on this next. Let me know if anything else needed on impala side before next release.

Is this still needed? I don't see anything from impala being imported outside the impala backend.

The only thing that we'll have to check, based on a grep is:
```
base_sql/ddl.py:        tokens.append(self._impala_signature())
```
But doesn't seem very important.

**Comment by matthewmturner** [comment]
> 
> 
> > @datapythonista @jreback ill merge master on this next. Let me know if anything else needed on impala side before next release.
> 
> Is this still needed? I don't see anything from impala being imported outside the impala backend.
> 
> The only thing that we'll have to check, based on a grep is:
> 
> ```
> base_sql/ddl.py:        tokens.append(self._impala_signature())
> ```
> 
> But doesn't seem very important.

i think youre right on both fronts.  the tests seem generic so dont need to move to impala.

How do you want to handle that `_impala_signature()` call?  I can just update this PR for that if you want? Or we can incorporate into one of the other `base_sql` refactorings (i.e. removing duplicate functionality from `base_sqlalchemy`

**Comment by datapythonista** [comment]
> How do you want to handle that `_impala_signature()` call? I can just update this PR for that if you want? Or we can incorporate into one of the other `base_sql` refactorings (i.e. removing duplicate functionality from `base_sqlalchemy`

Not so concerned about `_impala_signature()`. There is clearly something not right there, but it's probably not causing any bug or any problem. Feel free to have a look, but I'd close this, and maybe create an issue for that for now.

**Pull request closed without merging**
