### PR TITLE
BUG: Fix impala pandas interop temporary csv file writing issue on Windows platforms (#2267)

### LINKED ISSUE #2267: Impala pandas_interop.py DataFrameWriter.write_csv() fails with PermissionError on Windows Platforms
pandas_interop.py DataFrameWriter.write_csv() fails with PermissionError on Windows Platforms due to how Pythons [tempfile.NamedTemporaryFile()](https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile) works. 

Specifically, if the OS is Windows and the NamedTemporaryFile delete parameter is True, the IO operation will fail, because Python will open the file and then Pandas will attempt to open the file again. See [this SO answer ](https://stackoverflow.com/a/23212515/3744998)for more information. 

I have replicated the issue manually and verified that setting the delete parameter to False resolves the issue. Perhaps we can add a platform check and explicitly set the delete parameter based on the platform? Then after we [exit the context statements scope](https://github.com/ibis-project/ibis/blob/master/ibis/impala/pandas_interop.py#L80), explicitly delete the temporary file. I imagine it could look something like the following.

``` python

    import os

    def write_csv(self, path):
        if os.name == 'nt':
            # Should probably think of a better name for this boolean
            delete = False
        else:
            delete = True

        with tempfile.NamedTemporaryFile(delete=delete) as f:
            tmp_name = f.name
            # Write the DataFrame to the temporary file path
            if options.verbose:
                util.log(
                    'Writing DataFrame to temporary file {}'.format(f.name)
                )

            self.df.to_csv(
                f.name,
                header=False,
                index=False,
                sep=',',
                quoting=csv.QUOTE_NONE,
                escapechar='\\',
                na_rep='#NULL',
            )
            f.seek(0)

            if options.verbose:
                util.log('Writing CSV to: {0}'.format(path))

            self.hdfs.put(path, f.name)

        if not delete:
            os.remove(tmp_name)

        return path
```

I don't know that much about the Ibis code base, so this is just a first pass. I hope it's helpful.

### PR DESCRIPTION
**Pull request by ZeroCool2u**
This is a continuation of #2268. I made a mess with my original PR and just started from scratch. This new PR ensures that pre-commit hooks have run successfully and my commit signature is now verified. 

Resolve #2267 and provide a small fix for writing temporary files on Windows platforms where pandas attempts to open the file for a second time, which raises a PermissionDenied exception.

@datapythonista The change is complete and I did the method that @jreback originally described with the temporary directory. 
However, when I started to look into writing the test, I realized that it looks like this code already has pretty good coverage. There's no explicit asserts to check that the file is written to local disk of course, because unless we check in the context statement the file should never exist, but unless I'm misunderstanding something, shouldn't we already have seen some of these tests fail due to this bug? Is there maybe something different about the Azure pipelines Windows images than a typical Windows desktop image? 

Anyways, I'm happy to add a new test, but I'm not sure what we could add at this point that would go beyond what is already in the [existing tests](https://github.com/ibis-project/ibis/blob/master/ibis/impala/tests/test_pandas_interop.py#L183).

### CODE REVIEW

**Comment by ZeroCool2u** [comment]
Alright, so it looks like most of the tests on Windows are actually just skipped due to missing modules that we try to import. `hdfs` module [looks like the main problem for the panda_interop tests specifically](https://dev.azure.com/ibis-project/ibis/_build/results?buildId=2901&view=logs&j=a729dcb5-12ec-5e84-56cf-ed9028c16680&t=01bf3f77-bc94-5d91-05c1-58d17e42c42d&l=211). 

Not sure what the issue is with the rest of the builds. I know the pre-commit hooks worked locally, because the commits failed until I fixed them. Any ideas there?

**Comment by datapythonista** [comment]
Thanks @ZeroCool2u. What was the problem in leaving `delete=False` for all backends, and then manually delete the file in all OS's? I thought that was the proposed solution, which would be much simpler. I guess I misunderstood.

The CI is currently broken. I'm working on making things simpler in the CI, since it's breaking too often. But it'll take a while until it's working again.

**Comment by ZeroCool2u** [comment]
@datapythonista Gotcha, just saw your CI PR, very exciting! When I originally created my local dev environment I had to let the conda SAT solver run overnight 😬 so speed improvements are very welcome. 

I went with the temporary directory solution, because from what I understand the issue is opening the same file twice. If you set delete to false, you still have to close the file after it's instantiated, otherwise I think Python will technically still have it open and thus the OS will still have it locked and prevent pandas from opening it again when we actually try and write our data to disk. 

We can definitely do that, open the temp file with delete set to false, close it, write to it with pandas, then delete it, but looking at that seemed more confusing. Dumping it into temp directory, writing our data normally, and letting the context manager clean up for us felt a bit simpler, but that's super subjective.

No big deal either way, I'm happy to make the change if you prefer.

**Comment by ZeroCool2u** [comment]
@datapythonista @jreback Would it be possible to get this fix included in the next (bug) release? Honestly, this is totally self-serving, would just be very convenient for me. If not, I can build master myself with the fix, but would be nice to stick with stable.

**Comment by datapythonista** [comment]
It will, but we need to get the CI working again before we can merge any PR.

**Comment by ZeroCool2u** [comment]
Of course, looks like that's going very well. Thank you!

**Comment by datapythonista** [comment]
@ZeroCool2u CI is working again. Can you merge master please?

Also, can you add a test that fails before the fix and works after it please? Thanks!

**Comment by ZeroCool2u** [comment]
Sure! Thanks for all your hard work on the CI!

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
thanks @ZeroCool2u

**Comment by ZeroCool2u** [comment]
Np! Thanks for all the help!

**Pull request merged**
