### PR TITLE
Add geospatial tutorial notebook.

### PR DESCRIPTION
**Pull request by ian-r-rose**
This adds a demo/tutorial notebook for some of the geospatial stuff that @xmnlab and I have worked on in #1666, #1958, #1786, #1925, #1987

### CODE REVIEW

**Comment by xmnlab** [comment]
@ian-r-rose sorry for the delay .. I start to review this. thanks for working on that.

**Comment by xmnlab** [comment]
@ian-r-rose sorry for the delay. 

it looks nice! 

it uses a non public database connection for this, right?

@jreback @scottcode any thought about this?

**Comment by scottcode** [comment]
Cool-looking tutorial, @ian-r-rose! 

It looks like the data is downloadable from the geofabrik link in the notebook. But from the notebook's comments alone, it's still a little unclear to me how to load the data. @ian-r-rose, could you add more instructions in the notebook about how to download, transform (if necessary) and load the data in order to go through the tutorial? 

The data set seems rather large (~600MB). That might make testing or trying it out a little harder. Is there an even smaller extract that could be used?

**Comment by ian-r-rose** [comment]
Thanks for the review @scottcode. Yes, the data is large-ish, certainly too big to be included in the repo. I could add some content for how to load it. If memory serves, it takes a few minutes with `ogr2ogr`).

Another option for this would be to include a link to something like [this](https://github.com/ian-r-rose/binder-postgis) demo, which is packaged as a live binder. It uses smaller data, but is a bit less focused on ibis.

**Comment by ian-r-rose** [comment]
I've updated this to include instructions for setting up a demonstration database and loading the OSM extract into it.

It does take some time, as the dataset is not small, but I don't think it's *too* outlandish.

**Comment by ian-r-rose** [comment]
Rebased

**Comment by jreback** [comment]
thanks @ian-r-rose

**Pull request merged**
