### PR TITLE
fix(parsy): remove unexpected keyword argument to `optional`

### PR DESCRIPTION
**Pull request by gforsyth**
The `default={}` is throwing errors with `parsy==1.3.0` and removing it
doesn't seem to cause problems with parsy 2.0

### CODE REVIEW

**Comment by gforsyth** [comment]
wow, that broke everything.
shall we just bump up the minimum version of parsy?

**Comment by cpcloud** [comment]
> shall we just bump up the minimum version of parsy?

Definitely

**Comment by gforsyth** [comment]
> Definitely

Hmm, do we consider this a breaking change?

**Comment by cpcloud** [comment]
Yeah, but since we're targeting 5.0 I think that's fine!

**Review by cpcloud — APPROVED** [review]

**Pull request merged**
