### PR TITLE
fix(rewrites): change `TableColumn` -> `Field` in rewrites

### PR DESCRIPTION
**Pull request by gforsyth**
-------

## Description of changes

I don't know if just aren't using these rewrites or aren't testing them. 

Anyway, quick PR to remove the now renamed `ops.TableColumn` -- if it makes more sense to rip out the rewrites, I can do that instead.

### CODE REVIEW

**Comment by kszucs** [comment]
Apparently we don't use `rewrite_dropna` and `rewrite_fillna` anymore. We should check whether there are backends not supporting `FillNa` and `DropNa` and if there are, we can keep these rewrites.

**Comment by jcrist** [comment]
Yeah, these got dropped in the refactor. I _think_ we might want to bring them back though instead of implementing in the compiler (see https://github.com/ibis-project/ibis/blob/e4edc785a2e4324143c51c566458cf44af3be973/ibis/backends/sql/compiler.py#L1319-L1336) since doing this via a rewrite may allow fusing selects to generate nicer SQL. Doing this during compilation doesn't allow for that.

That said, happy to merge the fix as is (or delete the rewrites fully until/if we want them back).

**Comment by gforsyth** [comment]
I can look at restoring the expr-level rewrites

**Comment by gforsyth** [comment]
> SGTM, could you create a ticket to track this? I think we can merge it as is.

will do

**Review by kszucs — APPROVED** [review]

**Pull request merged**
