### PR TITLE
docs: move the support matrix to static quarto dashboard

### LINKED ISSUE #8078: docs: switch backend support matrix to Quarto dashboard or similar
### Please describe the issue

after some time, the backend support matrix Streamlit app tends to go down and needs to be rebooted: https://ibis-project.org/support_matrix

I'm not sure the original reason or benefit of keeping this as a Streamlit app

Quarto dashboards are released as of v1.4 and from my initial experimentation work well and are easy to port from Streamlit. this would allow us to use our existing Quarto publishing for the app, assuming we could replicate the functionality

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by cpcloud**
Replace the streamlit backend operation matrix with a simper, static quarto dashboard.

closes #8078

### CODE REVIEW

**Comment by lostmygithubaccount** [comment]
the numberes on the right don't look good on 100% zoom on my macbook (I use MS Edge):

image

also not having the %s feels bad

**Review by lostmygithubaccount — APPROVED** [review]
definitely some issues but a major improvement over the current state, thanks for this!

**Comment by cpcloud** [comment]
Gonna add the download buttons back, then merge it!

**Comment by cpcloud** [comment]
Converting to draft to see if I can work around the font colors before merging.

**Comment by lostmygithubaccount** [comment]
would switching to two columns of metrics in the top right also help w/ the thing I see in the screenshot above?

**Comment by cpcloud** [comment]
@lostmygithubaccount Mayhaps

**Review by lostmygithubaccount — APPROVED** [review]
🚀

**Pull request merged**
