### PR TITLE
CI: Make GitHub Actions builds compatible with Windows

### LINKED ISSUE #2389: CI: Make GitHub Actions builds compatible with Windows
GitHub actions support executing bash script in Windows. But currently, our bash script to setup the environment doesn't work, because the path to conda is not set correctly for Windows (only for Linux): https://github.com/ibis-project/ibis/blob/master/ci/setup_env.sh#L10 (the conda location is defined in GitHub actions with the env variable `$CONDA` if I'm not wrong).

We should fix the script so it works on Windows, and then we should add `windows-latest` to the build of backends that don't require a docker container: https://github.com/ibis-project/ibis/blob/master/.github/workflows/main.yml#L18

### PR DESCRIPTION
**Pull request by EdAbati**
closes #2389

I have changed `setup_env.sh` to set the CONDA_PATH based on which OS is running the script.
At the moment, I am passing the OS name using the value in `runner.os` as an argument as seen [here](https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#runner-context), but as suggested by @datapythonista I will try something else like `uname`.

I am still working on it , but please let me know if you have any suggestions.

### CODE REVIEW

**Comment by EdAbati** [comment]
Hi @datapythonista , I think it is working now. Please let me know if it is what you had in mind.
At the moment I am still passing `runner.os` as argument. I tried with `uname` and it returns `MSYS_NT-10.0-17763` for Windows. It seems a variable name to me (I may be wrong), instead `runner.os` returns something readable for each of the 2 OS.

**Comment by datapythonista** [comment]
Wow, this is amazing. Really cool to have it working, I'm so looking forward to get rid of azure and have the CI working properly.

`uname` has different parameters that adjust the result. `uname -s` may return something shorter. In any case, the vanilla `uname` value in Windows doesn't bother me. You can use the `=~` operator when comparing with the value, or probably better to use the bash `case`, which allows you wildcards and you can do `MSYS*)`.

What would also be nice is to instead of hardcoding the path to conda, to see if GitHub actions is giving it to us in an environment variable. I think it does, in `$CONDA`. It would be good to use it, in case they change it in the future.

**Comment by EdAbati** [comment]
I just found that `RUNNER_OS` is actually an environment variable in the GitHub action environments.
Would you still prefer `uname`?

Regarding to `$CONDA`, in linux it returns `/usr/share/miniconda` and in windows `C:\Miniconda`. I am using `cygpath` to convert to POSIX when using windows (found it here: https://stackoverflow.com/a/63912204/9486880 ) . I think the subfolder still need to hardcoded though

**Comment by datapythonista** [comment]
The conda paths look good. For the OS, using uname will make the script to work locally. Also, if run on windows but not in MSYS (not sure of that's possible with the wsl), the script will fail for not finding conda, instead of reporting that the OS is not supported, which seems better. Using uname should fix that.

Maybe it's also a good idea to have an if and skip all the path stuff if the CONDA variable is not present. The script may still work if conda is already in the path, as it's likely to be locally. But this way we don't incorrect paths to PATH.

But in any case, amazing job with this, very cool.

**Comment by EdAbati** [comment]
Also, I am adding a commit to solve the GitHub Action warning:
```The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/```
Using this instead: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
Let me know if you prefer to have another PR for this instead, I think it is only used in the `setup_env.sh` script though.

**Review by datapythonista — APPROVED** [review]
Really nice @EdAbati, looks great.

**Comment by EdAbati** [comment]
Great :) I guess I can safely delete the `ci/azure/windows.yml` file now, right? It seems that all the tests there will be covered by the GitHub actions, or am I missing something?

**Comment by datapythonista** [comment]
> Great :) I guess I can safely delete the `ci/azure/windows.yml` file now, right? It seems that all the tests there will be covered by the GitHub actions, or am I missing something?

That would be great in a follow up PR. But in Azure we are testing the MySQL backend in Windows (and PostgreSQL is not working, but looks like it also was expected to be tested), so we need to see what to do with that.

@jreback is it ok for you to only test in Windows the backends that don't require a container? Afaik containers in GitHub actions don't work in Windows with the `services` yaml key we are using for Linux. Seems a bit arbitrary to test MySQL and Postgres and not Impala, Clickhouse, Spark... So I guess it's probably ok if we just test on Windows SQLite, pandas, and the stuff not backend-specific.

**Comment by jreback** [comment]
> > Great :) I guess I can safely delete the `ci/azure/windows.yml` file now, right? It seems that all the tests there will be covered by the GitHub actions, or am I missing something?
> 
> 
> 
> That would be great in a follow up PR. But in Azure we are testing the MySQL backend in Windows (and PostgreSQL is not working, but looks like it also was expected to be tested), so we need to see what to do with that.
> 
> 
> 
> @jreback is it ok for you to only test in Windows the backends that don't require a container? Afaik containers in GitHub actions don't work in Windows with the `services` yaml key we are using for Linux. Seems a bit arbitrary to test MySQL and Postgres and not Impala, Clickhouse, Spark... So I guess it's probably ok if we just test on Windows SQLite, pandas, and the stuff not backend-specific.

sure some testing is better than none!

i think we comprehensively test these in other envs and wouldn't worry too much about specific windows behavior (as likely the underlying libraries handle this)

**Review by jreback — APPROVED** [review]
merge when ready @datapythonista

**Comment by datapythonista** [comment]
Thanks @EdAbati really nice. Feel free to remove the Windows build in azure then. That will be great, they keep failing quite often.

**Pull request merged**
