### PR TITLE
CLN: Removing bigquery backend from the Ibis repo

### PR DESCRIPTION
**Pull request by datapythonista**
xref #2665

Bigquery is being moved to a separate repo. Removing the backend from Ibis here.

CC: @tswast

### CODE REVIEW

**Comment by tswast** [comment]
Can we create a https://github.com/ibis-project/ibis-bigquery repo? Alternatively, I could probably make one in http://github.com/googleapis, but will need to go through some red tape to make that happen.

**Comment by datapythonista** [comment]
I created the repo, and granted you admin access to it (@jreback let me know if any concern about it).

Moving a repo of organization is trivial I think, so we can start with this repo, and reconsider in the future if needed.

**Review by jreback — CHANGES_REQUESTED** [review]
yep let's actually get the new package up before we merge this (certainly doesn't have to be released), but the actual code & at least CI turned on

**Comment by datapythonista** [comment]
Got an initial version in https://github.com/ibis-project/ibis-bigquery

The main thing missing is setting up and running the tests in the CI. I'm not familiar with BigQuery, and I don't have the environment set up locally to run tests. But should be as easy moving the code removed here in `ci/datamgr.py` to the new repo `ci/setup_tests.py`. And then setting up the build in actions (no idea how to allow secret access after a PR is reviewed, but that sounds awesome for this case).

@tswast can you take care of it from here?

**Comment by tswast** [comment]
Sweet, thanks!

Yeah, I'll start getting CI setup now.

**Comment by datapythonista** [comment]
@tswast I think you've already got the tests working in the new repo. Do you think it's ok to merge this already, or do you think it's better to wait?

**Comment by tswast** [comment]
I think it's OK. We'll just want to make sure to keep an eye on the scheduled builds at https://github.com/ibis-project/ibis-bigquery/actions to make sure any changes to the core library don't break the BigQuery backend (or a PR is sent out to clean it up after making any breaking changes)

**Comment by datapythonista** [comment]
Great, thanks @tswast 

@jreback just rebased this, I think it should be ready to get merged.

**Comment by jreback** [comment]
looks good. can you add a release note and point to the new repo? ideally `ibis-bigquery` can do a release about the same time as ibis

**Comment by datapythonista** [comment]
Good point, thanks Jeff. Added the release note.

And sure, will coordinate withe the backends (omniscidb, mssql and bigquery) for the release, so 2.0 comes with all them working at around the same time.

**Comment by jreback** [comment]
> Good point, thanks Jeff. Added the release note.
> 
> And sure, will coordinate withe the backends (omniscidb, mssql and bigquery) for the release, so 2.0 comes with all them working at around the same time.

great, yeah we can release first fine as well.

also let's create an issue for eco-system in the docs? e.g. pointers to the other backends.

**Review by jreback — APPROVED** [review]

**Comment by datapythonista** [comment]
> also let's create an issue for eco-system in the docs? e.g. pointers to the other backends.

I created #2735 with what I would do regarding docs. Open for discussion.

**Pull request merged**
