### PR TITLE
docs: fix release notes

### LINKED ISSUE #3103: docs: missing release notes for version 2.0.0
I can't see the list at https://ibis-project.org/docs/release/index.html

### PR DESCRIPTION
**Pull request by cpcloud**
Closes #3103

### CODE REVIEW

**Comment by cpcloud** [comment]
Tested locally, things look good

image

**Comment by jreback** [comment]
cool,

OT: could consider splitting the notes by major version to separate files for easier navigating....

**Comment by cpcloud** [comment]
The plan is to move to an automatically generated `CHANGELOG.md`, so probably not gonna split those any time soon :)

**Comment by cpcloud** [comment]
Those release notes will be split up in GitHub Releases for easier navigation of specific releases, which I think is a good middle ground between a file-per-release (annoying to automate) and glomming everything together

**Comment by cpcloud** [comment]
@jreback Can you approve?

**Review by jreback — APPROVED** [review]

**Pull request merged**
