### PR TITLE
ci: tighten up the docker-compose setup

### PR DESCRIPTION
**Pull request by cpcloud**
- ci: use official postgis image and add plpythonu extension
- chore(dev): bump impala's postgres to 13.3
- chore: remove the need for 5433 since impala only needs to address the postgres container inside the docker network
- chore(dev): run the impala postgres container as the postgres user

### CODE REVIEW

**Comment by cpcloud** [comment]
@jreback Thoughts? I'd like to merge this

**Review by jreback — APPROVED** [review]
looks fine. is using docker explained in docs sufficiently? or is this for CI only? (this can be a followup)

**Comment by cpcloud** [comment]
@jreback Check the docs! https://ibis-project.org/contribute/backend_test_suite

**Comment by cpcloud** [comment]
It's for both CI and local backend testing, that's the whole point :)

**Comment by jreback** [comment]
docs look great.

**Pull request merged**
