### PR TITLE
docs: port existing post-1.0 release notes to markdown, remove sphinx-releases, remove cryptography pin

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by cpcloud** [comment]
Screenshot:
image

**Comment by cpcloud** [comment]
I'm going to try converting the pre-1.0 release notes as well, so we can get rid of the indirection

**Review by kszucs — APPROVED** [review]

**Comment by kszucs** [comment]
> I'm going to try converting the pre-1.0 release notes as well, so we can get rid of the indirection

In a separate PR or in this one?

**Comment by cpcloud** [comment]
> > I'm going to try converting the pre-1.0 release notes as well, so we can get rid of the indirection
> 
> In a separate PR or in this one?

It's in this one

**Comment by cpcloud** [comment]
https://github.com/ibis-project/ibis/pull/3281/files#diff-db2fa5fb472b8dd8c8c1bfb887185bffdbcf97f014baee9be2a511004cd8f92c

**Pull request merged**
