### PR TITLE
fix(impala): add date column dtype to impala to ibis type dict

### LINKED ISSUE #4449: bug (Impala): "date" type not recognized when trying to read Hive table
A Hive table I'm trying to read has columns with the "DATE" type (valid type as per [the Impala docs](https://impala.apache.org/docs/build/html/topics/impala_date.html)).

When trying to run a simple expression (`table = connection.table('my_db.my_table'`), I get the following traceback:

```Exception                                 Traceback (most recent call last)
Input In [9], in <cell line: 1>()
----> 1 hive_conn.table('tableau_di_tables.ds_consumer_travel_orders')

File ~/miniconda3/envs/ds-hotel-ranking/lib/python3.10/site-packages/ibis/backends/base/sql/__init__.py:44, in BaseSQLBackend.table(self, name, database)
     29 """Construct a table expression.
     30 
     31 Parameters
   (...)
     41     Table expression
     42 """
     43 qualified_name = self._fully_qualified_name(name, database)
---> 44 schema = self.get_schema(qualified_name)
     45 node = self.table_class(qualified_name, schema, self)
     46 return self.table_expr_class(node)

File ~/miniconda3/envs/ds-hotel-ranking/lib/python3.10/site-packages/ibis/backends/impala/__init__.py:482, in Backend.get_schema(self, table_name, database)
    479 pairs = [row[:2] for row in self.con.fetchall(query)]
    481 names, types = zip(*pairs)
--> 482 ibis_types = [udf.parse_type(type.lower()) for type in types]
    483 return sch.Schema(names, ibis_types)

File ~/miniconda3/envs/ds-hotel-ranking/lib/python3.10/site-packages/ibis/backends/impala/__init__.py:482, in <listcomp>(.0)
    479 pairs = [row[:2] for row in self.con.fetchall(query)]
    481 names, types = zip(*pairs)
--> 482 ibis_types = [udf.parse_type(type.lower()) for type in types]
    483 return sch.Schema(names, ibis_types)

File ~/miniconda3/envs/ds-hotel-ranking/lib/python3.10/site-packages/ibis/backends/impala/udf.py:310, in parse_type(t)
    308         return ValueError(t)
    309 else:
--> 310     raise Exception(t)

Exception: date
```

Looking at the source code it seems that "date" type is not in the `_impala_to_ibis_type` dict in `udf.py`.

Is it possible to include the date type here? It seems like a one-to-one equivalency with the ibis type.

 I can try and submit a pull request for this although I don't have much experience with contributing!

### PR DESCRIPTION
**Pull request by indylec**
fixes #4449

### CODE REVIEW

**Review by cpcloud — CHANGES_REQUESTED** [review]
Please delete `.DS_Store`. I'll add an entry to `.gitignore` for it to the PR.

**Comment by cpcloud** [comment]
@indylec I deleted `.DS_Store` so no need to do that.

**Review by cpcloud — APPROVED** [review]

**Comment by cpcloud** [comment]
@indylec Thanks for the quick turnaround 🚀! I've set this to automerge, should be in master shortly

**Comment by indylec** [comment]
@cpcloud great! Thanks, glad it was fairly straightforward in the end.

**Pull request merged**
