### PR TITLE
FEAT: [BQ] Implemented covariance in bigquery

### PR DESCRIPTION
**Pull request by wabu**

### CODE REVIEW

**Comment by icexelloss** [comment]
Hi can you please update [FEAT] to FEAT: in the title?

**Comment by wabu** [comment]
There's no issue for this, used the implementation right away and later did a PR for it.

**Comment by wabu** [comment]
Should I create an issue for this or is it fine for merge like this?

**Comment by xmnlab** [comment]
could you please resolve the release note conflict?

**Comment by jreback** [comment]
thanks @wabu

**Pull request merged**
