### PR TITLE
Getting started mapd mysql pandas

### LINKED ISSUE #1663: How to use pandas as a backend?
How can I use Ibis with pandas as the backend? I searched the documentation but couldn't find how.

### PR DESCRIPTION
**Pull request by xmnlab**
Fixes #1663

### CODE REVIEW

**Comment by xmnlab** [comment]
@cpcloud @kszucs it seems it is done for review :)

**Comment by xmnlab** [comment]
@cpcloud @kszucs any feedback about this PR?

**Comment by xmnlab** [comment]
could this be merged?

**Comment by cpcloud** [comment]
Thanks @xmnlab !

**Pull request closed without merging**
