### PR TITLE
CI: Enabling Impala build in actions

### LINKED ISSUE #2568: GHA Impala build is failing to connect to Kudu
That's great @matthewmturner, good to see some progress.

I think we can create an issue for the kudu problem, and get your improvements here merged, since the problem with kudu seems unrelated to the original issue.

Do you want to clean the diff here so we can merge this, keeping the build still skipped, and open the issue?

I don't know much about kudu, but I can have a look too after this is merged.

_Originally posted by @datapythonista in https://github.com/ibis-project/ibis/pull/2562#issuecomment-742118533_

### PR DESCRIPTION
**Pull request by datapythonista**
Closes #2568

Working on making the Impala build work on actions

### CODE REVIEW

**Comment by datapythonista** [comment]
@jreback looks like the (old) Impala build in azure is not testing the generic backend tests (what used to be named `all` that now is `backends/tests/`). I'm testing them in all builds in Actions, since my understanding is that we do want to test them for all backends.

I guess the azure build is not testing them because a typo (the CI config is quite tricky and counter-intuitive imho).

So, two questions:
- Am I assuming this right?
- Is it ok to create an issue and xfail the clickhouse test [test_substr_with_null_values](https://github.com/ibis-project/ibis/pull/2624/checks?check_run_id=1962513048#step:6:223), so this can be merged and we can get rid of azure?

This is the summary of the tests, with this PR we'll be running like 600 more tests for the Impala/Kudu/Clickhouse build when moving to Actions:

Actions:
```
= 1 failed, 3945 passed, 145 skipped, 220 xfailed, 1 xpassed, 20 warnings in 342.03s (0:05:42) =
```
Azure:
```
= 3346 passed, 7 skipped, 107 deselected, 89 xfailed, 1 xpassed, 2 warnings in 215.31s (0:03:35) =
```

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
ready? looks all passing.

**Comment by datapythonista** [comment]
Yes, ready from my side. This is finally working, and I'm removing the azure build that this replaces in #2645

**Comment by jreback** [comment]
very nice!

**Pull request merged**
