### PR TITLE
CI: Remove pipelines jobs moved to actions, and use new dependencies

### PR DESCRIPTION
**Pull request by datapythonista**
In #2314, several CI jobs have been moved to GitHub actions. Removing them here from pipelines, and for the remaining job, making them use the new dependencies files, which make conda solve the environment much faster.

### CODE REVIEW

**Comment by datapythonista** [comment]
@jreback if you have time, it would be quite useful to have edit permissions in pipelines. It would speed up things if I could cancel the builds I don't need, so I don't need to wait for the queued ones I'm debugging. I know you already tried, but I still don't have them.

**Comment by jreback** [comment]
> @jreback if you have time, it would be quite useful to have edit permissions in pipelines. It would speed up things if I could cancel the builds I don't need, so I don't need to wait for the queued ones I'm debugging. I know you already tried, but I still don't have them.

sure np, do you have any idea where you need to change this?

**Comment by jreback** [comment]
> > @jreback if you have time, it would be quite useful to have edit permissions in pipelines. It would speed up things if I could cancel the builds I don't need, so I don't need to wait for the queued ones I'm debugging. I know you already tried, but I still don't have them.
> 
> sure np, do you have any idea where you need to change this?

I made you admin on the repo, try now

**Comment by datapythonista** [comment]
> I made you admin on the repo, try now

Doesn't work yet :(

I'm not sure if it's because I'm not a member of the `ibis-project` organization and just got permissions to this repo. Or if permissions need to be given in pipelines directly.

**Comment by jreback** [comment]
sent invite to the org itself

**Comment by datapythonista** [comment]
> sent invite to the org itself

Thanks. I was having a look and seems like the permissions can be given in pipelines directly. I thought they were taken from GitHub, but can't remember how we did it in pandas. For what I've seen in a pipelines instead where I'm admin, there should be an `Invite` button in the top-right of this page: https://dev.azure.com/ibis-project/ibis I guess that should work.

**Comment by datapythonista** [comment]
@jreback, all green here, finally.

The impala test in actions is skipped, it usually shows as it when the rest are done, not sure if this time is taking longer or something in actions wasn't triggered.

Work is pending on cleaning the CI and moving all builds to actions, but this fixes the CI, so other PRs can be merged while all that is done.

**Comment by jreback** [comment]
thanks @datapythonista 

pls push followups as needed

**Comment by datapythonista** [comment]
I'll continue next week, for now CI should be stable. Thanks!

**Pull request merged**
