### PR TITLE
DEPS: Dropping support for Python 3.6

### LINKED ISSUE #2288: DEPS: drop 3.6
its time.

### PR DESCRIPTION
**Pull request by datapythonista**
Closes #2288

### CODE REVIEW

**Comment by datapythonista** [comment]
@jreback let me know when you're ready to get this merged and I'll resolve the conflicts.

**Comment by jreback** [comment]
@datapythonista can you rebase and let's get this in.

**Comment by datapythonista** [comment]
Rebased

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
thanks @datapythonista very nice!

**Pull request merged**
