### PR TITLE
ENH/BLD/CI: Add linux-64 temporary package artifacts

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by cpcloud** [comment]
This only affects linux builds, so no need to wait for appveyor.

You can actually install the bleeding-edge package directly from the CircleCI link:

```sh
conda install ibis-framework \
  --channel 'https://9617-41739288-gh.circle-artifacts.com/0/tmp/ibis/packages'
```
We may want to make it easy to get that URL, or publish these to some nightly channel.

**Comment by kszucs** [comment]
That sounds great! BTW Can we do that with travis / appveyor (related to arrow)?

**Comment by cpcloud** [comment]
@kszucs Looks like appveyor has a similar feature: https://www.appveyor.com/docs/packaging-artifacts/ that allows one to upload to appveyor's cloud storage. As long as the link is valid and the channel is indexed then you should be able to `conda install` a package.

**Comment by cpcloud** [comment]
Looks like travis has a more limited version of this feature: https://docs.travis-ci.com/user/uploading-artifacts/ requiring you to use S3 instead of providing an abstraction over the storage. This is kind of unfortunate, but for arrow we could try to procure a bucket for this. Eventually we'd probably want to shove *all* of the artifacts into that bucket so that we could have them available at release time.

**Pull request closed without merging**
