### PR TITLE
refactor(everything): port sql backends to sqlglot; split relations; fix a large number of bugs

### PR DESCRIPTION
**Pull request by cpcloud**
This PR is the rebase of `the-epic-split` onto `main`.

### CODE REVIEW

**Comment by cpcloud** [comment]
Docs PR appears to be hitting the rate limit of clickhouse's playground.

**Comment by cpcloud** [comment]
docs PR job issue should be fixed by #8312

**Comment by cpcloud** [comment]
The `docs_pr` and `benchmarks` jobs will not run because they have been replace with `Docs PR` in `the-epic-split`, and `benchmarks` only runs against `main`.

**Comment by cpcloud** [comment]
I'm going to disable those jobs in required checks now.

**Comment by cpcloud** [comment]
@jcrist @kszucs @gforsyth Can I get an explicit +1 here before merging?

**Review by kszucs — APPROVED** [review]

**Review by gforsyth — APPROVED** [review]
:shipit:

**Comment by kszucs** [comment]
Ran the cloud builds:

```
❯ just test bigquery snowflake
bringing up nodes...
..........xssssssssssssssssssssss....x.x...x..x....x...........x.xxx.xxx...x.....xx............x........x.x..........x........xx..........x..x....x.xx...x............xx...............x.x......x.............xx........xx..........x..x.....x.. [  7%]
x.........x..........x..x............x....x.....x.x...x................................s.......x.s.......x....s.x.......xx.xx.........x......xx.x.x....x....xxx...xxx.x.x..x..xx.xx.xx..x..xxxxxxx.xxxx.xxx.xxxxxxx.xxxxxxxxxxxxx.xx............ [ 14%]
x.....xx...........x.....xxx....x...x........x..x..x........xx..xx.x........x........xxx.....x.......x.x..................x....x.......xxx...x.......x........xx............x..................x..................................x......x...... [ 21%]
..x........x..x..........x.........x...x..x.x.....x...x..................x.........x.sx.s.s.x...............s....................................................................x.........x................x.x.x...............xx.x......x..... [ 29%]
.x.........x.............xx.....x................xx......x..xx........x........x.xxx....xx....x.........x...x................x..xxxxxxxxxxxxxxxxx......x....x.x......x........x..............................x....xx.x..sxx.xxxx..xx...x.x....x. [ 36%]
x.x...xx.......x....x......................x..........................................x........x.......................................x........................................................xx........x.x..........x............x.......x... [ 43%]
........................x.x.......x............x..................x.x..........x......x...........x........x................xx.......................xx......................................................................................x.. [ 51%]
..............x..x........................x..........x.....x......x...............xx...............x..............................x..x....xx.x......x..xx..x.............x......xxx...........x.x..x......x.....x.x..................x.x......xx [ 58%]
x..x.x..x..x......x..............x.x......x...x.................x.x..........x..x....x......x.....x.........xxx..x.x..x.........x.............x..x........x.............x..x....x......xx.x.............x.x...x.ss.......s...................... [ 65%]
..........s................................................s.......................x.................x..................xx.x......x...x..x..x......x..x....x..x........x.....x.................................x.x...x.......x.xx..xx.x......... [ 73%]
.x........x.x.xx...xx.xxxxxxxxxxxxx..x.......x........x......................x.......x.....s.....xx..xx..xxx.xx..xxxxx...x.x..xx.x.......x...x......x................................x.......x....xx..x...x..xx.................x......x......x. [ 80%]
....x..x......x.x............x.................................................................................................................................................................................................................. [ 87%]
...................s.......................................................................s.................................................................................................................................................... [ 95%]
..x..................................................................................................xx...................................................x.....                                                                                 [100%]
2819 passed, 38 skipped, 423 xfailed in 638.38s (0:10:38)
```

**Pull request merged**
