### PR TITLE
docs: bring back backend API documentation

### LINKED ISSUE #6999: bug: Error: cannot start a transaction within a transaction when using raw_sql against duckdb
### What happened?

I ran this code:

```
import ibis

con = ibis.duckdb.connect() 
con.raw_sql("SET memory_limit='1GB';")
con.raw_sql("SELECT current_setting('memory_limit');")
```

and got this error:

> sqlalchemy.exc.OperationalError: (duckdb.TransactionException) TransactionContext Error: cannot start a transaction within a transaction

<details>
<summary>Full output</summary>

```
Traceback (most recent call last):
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1095, in _begin_impl
    self.engine.dialect.do_begin(self.connection)
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/duckdb_engine/__init__.py", line 246, in do_begin
    connection.execute("begin")
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/duckdb_engine/__init__.py", line 142, in execute
    self.__c.execute(statement)
duckdb.TransactionException: TransactionContext Error: cannot start a transaction within a transaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bryce/tmp/ibis-duckdb.py", line 5, in <module>
    con.raw_sql("SELECT current_setting('memory_limit');")
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/ibis/backends/base/sql/alchemy/__init__.py", line 574, in raw_sql
    return self.con.connect().execute(
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1834, in _execute_context
    self._autobegin()
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 781, in _autobegin
    self.begin()
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 849, in begin
    self._transaction = RootTransaction(self)
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2667, in __init__
    self._connection_begin_impl()
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2685, in _connection_begin_impl
    self.connection._begin_impl(self)
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1097, in _begin_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1095, in _begin_impl
    self.engine.dialect.do_begin(self.connection)
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/duckdb_engine/__init__.py", line 246, in do_begin
    connection.execute("begin")
  File "/Users/bryce/.pyenv/versions/3.10.11/lib/python3.10/site-packages/duckdb_engine/__init__.py", line 142, in execute
    self.__c.execute(statement)
sqlalchemy.exc.OperationalError: (duckdb.TransactionException) TransactionContext Error: cannot start a transaction within a transaction
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```
</details>

I then ran what I felt like was analogous code directly in DuckDB and it worked as expected:

```
❯ duckdb
v0.6.1 919cad22e8
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D SET memory_limit='1GB';
D SELECT current_setting('memory_limit');
┌─────────────────────────────────┐
│ current_setting('memory_limit') │
│             varchar             │
├─────────────────────────────────┤
│ 1.0GB                           │
└─────────────────────────────────┘
```

### What version of ibis are you using?

6.2.0

### What backend(s) are you using, if any?

DuckDB

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #7076: bug: docs: BackendBase API isn't public on website
### What happened?

APIs like Backend.list_tables() aren't anywhere

### What version of ibis are you using?

main

### What backend(s) are you using, if any?

NA

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by cpcloud**
This PR brings back generated backend API documentation that was lost in the quarto-ization.

Closes #6999.
Closes #7076.

### CODE REVIEW

**Comment by gforsyth** [comment]
The rendered API docs look good, but the attributes and methods aren't showing up in the page contents list on the RHS:



Does quarto have an equivalent to toc levels?

**Comment by cpcloud** [comment]
It looks like if I decrease the header level they show up in the TOC. I can do that for now if that's okay.

**Comment by gforsyth** [comment]
> It looks like if I decrease the header level they show up in the TOC. I can do that for now if that's okay.

That seems like a good tradeoff

**Comment by cpcloud** [comment]
Longer term I'd like to avoid writing so much code to produce API documentation in a specific place inside of another qmd.

@machow Any thoughts on being able to embed `quartodoc` output without having to call into the API? Perhaps I am also doing it in a bone-headed way too, maybe there's a more official API for embedding docstrings into another qmd.

**Comment by jcrist** [comment]
Another option might be to add the backend api docs to hidden pages in the generated API docs (e.g. include them in `sections` but don't add them to the sidebar/index anywhere), then use the `include` directive ([docs](https://quarto.org/docs/authoring/includes.html)) to manually include those hidden generated pages in the backend pages? That's a different house of cards though, not necessarily cleaner.

**Review by gforsyth — APPROVED** [review]
Agreed that it would be nicer to have to write less code, but for the moment, this looks good and restores info we need to have in the docs.

**Pull request merged**
