### PR TITLE
API/BUG: Remove support for async query execution

### LINKED ISSUE #1548: Remove async keyword from execute
This is now a syntax error in Python 3.7.

Let's change this to be a method `execute_async`.

### PR DESCRIPTION
**Pull request by kszucs**
Updated changelog.

Closes #1548

### CODE REVIEW

**Comment by cpcloud** [comment]
Failed because the shiny new automated docker build is not finished building the impala image. I'll restart the build when it's ready.

**Comment by cpcloud** [comment]
@kszucs Actually, of course I don't have permissions on your fork. Can you kick off the build again?

**Comment by kszucs** [comment]
Sure

**Comment by cpcloud** [comment]
Merging! Thanks @kszucs

**Pull request closed without merging**
