### PR TITLE
BUG: Ensure parent_df is actually a frame in udf

### PR DESCRIPTION
**Pull request by gerrymanoim**

### CODE REVIEW

**Review by datapythonista — COMMENTED** [review]
Thanks @gerrymanoim, do you mind adding a test, and if the bug was introduced before the previous release, a release note please.

**Comment by gerrymanoim** [comment]
Still in draft, I'll come back to this later with some other UDF changes. 

Will add tests.

**Comment by datapythonista** [comment]
@gerrymanoim is this something you're still working on?

**Comment by jreback** [comment]
can you rebase

**Comment by gerrymanoim** [comment]
Closing until I get back to debugging this.

**Pull request closed without merging**
