### PR TITLE
CI: Pin jinja2 to restore CI

### LINKED ISSUE #2782: DOC: pin jinja to avoid failing doc build
I think we might need similar to this: https://github.com/pandas-dev/pandas/pull/41452

### PR DESCRIPTION
**Pull request by datapythonista**
Closes #2782

xref #2783

### CODE REVIEW

**Comment by jreback** [comment]
great this fixes the doc-build, in combo with #2781 should be good

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
can you rebase (as merged the other one), to have all green.

**Comment by datapythonista** [comment]
Yep, seems like with the other PR and this one, the CI is fixed.

**Comment by jreback** [comment]
thanks @datapythonista

**Pull request merged**
