### PR TITLE
fix(deps): support python 3.12

### PR DESCRIPTION
**Pull request by cpcloud**
Add 3.12 job and support in our nix builds and environment; fixes warnings about utcfromtimestamp from ibis code and ignores them in testing due to their use at the top level of dateutil.

### CODE REVIEW

**Comment by cpcloud** [comment]
Looks like only DuckDB >=0.10 supports Python 3.12 :(

**Comment by cpcloud** [comment]
I realize we have a 3-Python-version policy (I think we wrote that down somewhere), so I didn't add a 3.12 job anywhere that would significantly increase CI job count. For example, all backend workflows (except PySpark because in the past that has been annoying) did **not** get a 3.12 job.

**Comment by gforsyth** [comment]
NEP 29 drop-date for Python 3.9 is April 5th, 2024, so either way we'll be back to 3 python versions fairly shortly.

**Review by gforsyth — APPROVED** [review]
:shipit:

**Pull request merged**
