### PR TITLE
CI: Disabling conda package job

### PR DESCRIPTION
**Pull request by datapythonista**
xref https://github.com/conda-forge/ibis-framework-feedstock/pull/50#issuecomment-702994281
xref https://github.com/ibis-project/ibis/pull/2426#issuecomment-702883144

### CODE REVIEW

**Review by jreback — APPROVED** [review]
yep

**Comment by jreback** [comment]
let's hope we have a green build

**Comment by jreback** [comment]
looks like kudu/impala/clickhouse failed?

**Comment by datapythonista** [comment]
Superseded by #2447, closing

**Pull request closed without merging**
