### PR TITLE
test(tpcds): add query 66 to the TPC-DS test suite

### PR DESCRIPTION
**Pull request by deepyaman**

### CODE REVIEW

**Comment by deepyaman** [comment]
Think this is the query executing in Clickhouse:

```sql
CREATE VIEW ibis_clickhouse_metadata_5qxxvtcgfjhlrhodk7k6nwzcee AS
SELECT   w_warehouse_name,
         w_warehouse_sq_ft,
         w_city,
         w_county,
         w_state,
         w_country,
         ship_carriers,
         year_,
         Sum(jan_sales)                     AS jan_sales,
         Sum(feb_sales)                     AS feb_sales,
         Sum(mar_sales)                     AS mar_sales,
         Sum(apr_sales)                     AS apr_sales,
         Sum(may_sales)                     AS may_sales,
         Sum(jun_sales)                     AS jun_sales,
         Sum(jul_sales)                     AS jul_sales,
         Sum(aug_sales)                     AS aug_sales,
         Sum(sep_sales)                     AS sep_sales,
         Sum(oct_sales)                     AS oct_sales,
         Sum(nov_sales)                     AS nov_sales,
         Sum(dec_sales)                     AS dec_sales,
         Sum(jan_sales / w_warehouse_sq_ft) AS jan_sales_per_sq_foot,
         Sum(feb_sales / w_warehouse_sq_ft) AS feb_sales_per_sq_foot,
         Sum(mar_sales / w_warehouse_sq_ft) AS mar_sales_per_sq_foot,
         Sum(apr_sales / w_warehouse_sq_ft) AS apr_sales_per_sq_foot,
         Sum(may_sales / w_warehouse_sq_ft) AS may_sales_per_sq_foot,
         Sum(jun_sales / w_warehouse_sq_ft) AS jun_sales_per_sq_foot,
         Sum(jul_sales / w_warehouse_sq_ft) AS jul_sales_per_sq_foot,
         Sum(aug_sales / w_warehouse_sq_ft) AS aug_sales_per_sq_foot,
         Sum(sep_sales / w_warehouse_sq_ft) AS sep_sales_per_sq_foot,
         Sum(oct_sales / w_warehouse_sq_ft) AS oct_sales_per_sq_foot,
         Sum(nov_sales / w_warehouse_sq_ft) AS nov_sales_per_sq_foot,
         Sum(dec_sales / w_warehouse_sq_ft) AS dec_sales_per_sq_foot,
         Sum(jan_net)                       AS jan_net,
         Sum(feb_net)                       AS feb_net,
         Sum(mar_net)                       AS mar_net,
         Sum(apr_net)                       AS apr_net,
         Sum(may_net)                       AS may_net,
         Sum(jun_net)                       AS jun_net,
         Sum(jul_net)                       AS jul_net,
         Sum(aug_net)                       AS aug_net,
         Sum(sep_net)                       AS sep_net,
         Sum(oct_net)                       AS oct_net,
         Sum(nov_net)                       AS nov_net,
         Sum(dec_net)                       AS dec_net
FROM     (
                  SELECT   w_warehouse_name,
                           w_warehouse_sq_ft,
                           w_city,
                           w_county,
                           w_state,
                           w_country,
                           'DHL,BARIAN' AS ship_carriers,
                           d_year       AS year_,
                           Sum(
                           CASE
                                    WHEN d_moy = 1 THEN ws_ext_sales_price * ws_quantity
                                    ELSE 0
                           END) AS jan_sales,
                           Sum(
                           CASE
                                    WHEN d_moy = 2 THEN ws_ext_sales_price * ws_quantity
                                    ELSE 0
                           END) AS feb_sales,
                           Sum(
                           CASE
                                    WHEN d_moy = 3 THEN ws_ext_sales_price * ws_quantity
                                    ELSE 0
                           END) AS mar_sales,
                           Sum(
                           CASE
                                    WHEN d_moy = 4 THEN ws_ext_sales_price * ws_quantity
                                    ELSE 0
                           END) AS apr_sales,
                           Sum(
                           CASE
                                    WHEN d_moy = 5 THEN ws_ext_sales_price * ws_quantity
                                    ELSE 0
                           END) AS may_sales,
                           Sum(
                           CASE
                                    WHEN d_moy = 6 THEN ws_ext_sales_price * ws_quantity
                                    ELSE 0
                           END) AS jun_sales,
                           Sum(
                           CASE
                                    WHEN d_moy = 7 THEN ws_ext_sales_price * ws_quantity
                                    ELSE 0
                           END) AS jul_sales,
                           Sum(
                           CASE
                                    WHEN d_moy = 8 THEN ws_ext_sales_price * ws_quantity
                                    ELSE 0
                           END) AS aug_sales,
                           Sum(
                           CASE
                                    WHEN d_moy = 9 THEN ws_ext_sales_price * ws_quantity
                                    ELSE 0
                           END) AS sep_sales,
                           Sum(
                           CASE
                                    WHEN d_moy = 10 THEN ws_ext_sales_price * ws_quantity
                                    ELSE 0
                           END) AS oct_sales,
                           Sum(
                           CASE
                                    WHEN d_moy = 11 THEN ws_ext_sales_price * ws_quantity
                                    ELSE 0
                           END) AS nov_sales,
                           Sum(
                           CASE
                                    WHEN d_moy = 12 THEN ws_ext_sales_price * ws_quantity
                                    ELSE 0
                           END) AS dec_sales,
                           Sum(
                           CASE
                                    WHEN d_moy = 1 THEN ws_net_paid * ws_quantity
                                    ELSE 0
                           END) AS jan_net,
                           Sum(
                           CASE
                                    WHEN d_moy = 2 THEN ws_net_paid * ws_quantity
                                    ELSE 0
                           END) AS feb_net,
                           Sum(
                           CASE
                                    WHEN d_moy = 3 THEN ws_net_paid * ws_quantity
                                    ELSE 0
                           END) AS mar_net,
                           Sum(
                           CASE
                                    WHEN d_moy = 4 THEN ws_net_paid * ws_quantity
                                    ELSE 0
                           END) AS apr_net,
                           Sum(
                           CASE
                                    WHEN d_moy = 5 THEN ws_net_paid * ws_quantity
                                    ELSE 0
                           END) AS may_net,
                           Sum(
                           CASE
                                    WHEN d_moy = 6 THEN ws_net_paid * ws_quantity
                                    ELSE 0
                           END) AS jun_net,
                           Sum(
                           CASE
                                    WHEN d_moy = 7 THEN ws_net_paid * ws_quantity
                                    ELSE 0
                           END) AS jul_net,
                           Sum(
                           CASE
                                    WHEN d_moy = 8 THEN ws_net_paid * ws_quantity
                                    ELSE 0
                           END) AS aug_net,
                           Sum(
                           CASE
                                    WHEN d_moy = 9 THEN ws_net_paid * ws_quantity
                                    ELSE 0
                           END) AS sep_net,
                           Sum(
                           CASE
                                    WHEN d_moy = 10 THEN ws_net_paid * ws_quantity
                                    ELSE 0
                           END) AS oct_net,
                           Sum(
                           CASE
                                    WHEN d_moy = 11 THEN ws_net_paid * ws_quantity
                                    ELSE 0
                           END) AS nov_net,
                           Sum(
                           CASE
                                    WHEN d_moy = 12 THEN ws_net_paid * ws_quantity
                                    ELSE 0
                           END) AS dec_net
                  FROM     tpcds.web_sales,
                           tpcds.warehouse,
                           tpcds.date_dim,
                           tpcds.time_dim,
                           tpcds.ship_mode
                  WHERE    ws_warehouse_sk = w_warehouse_sk
                  AND      ws_sold_date_sk = d_date_sk
                  AND      ws_sold_time_sk = t_time_sk
                  AND      ws_ship_mode_sk = sm_ship_mode_sk
                  AND      d_year = 2001
                  AND      t_time BETWEEN 30838 AND      30838 + 28800
                  AND      sm_carrier                         IN ('DHL',
                                                                  'BARIAN')
                  GROUP BY w_warehouse_name,
                           w_warehouse_sq_ft,
                           w_city,
                           w_county,
                           w_state,
                           w_country,
                           d_year
                  UNION ALL
                  SELECT   w_warehouse_name,
                           w_warehouse_sq_ft,
                           w_city,
                           w_county,
                           w_state,
                           w_country,
                           'DHL,BARIAN' AS ship_carriers,
                           d_year       AS year_,
                           Sum(
                           CASE
                                    WHEN d_moy = 1 THEN cs_sales_price * cs_quantity
                                    ELSE 0
                           END) AS jan_sales,
                           Sum(
                           CASE
                                    WHEN d_moy = 2 THEN cs_sales_price * cs_quantity
                                    ELSE 0
                           END) AS feb_sales,
                           Sum(
                           CASE
                                    WHEN d_moy = 3 THEN cs_sales_price * cs_quantity
                                    ELSE 0
                           END) AS mar_sales,
                           Sum(
                           CASE
                                    WHEN d_moy = 4 THEN cs_sales_price * cs_quantity
                                    ELSE 0
                           END) AS apr_sales,
                           Sum(
                           CASE
                                    WHEN d_moy = 5 THEN cs_sales_price * cs_quantity
                                    ELSE 0
                           END) AS may_sales,
                           Sum(
                           CASE
                                    WHEN d_moy = 6 THEN cs_sales_price * cs_quantity
                                    ELSE 0
                           END) AS jun_sales,
                           Sum(
                           CASE
                                    WHEN d_moy = 7 THEN cs_sales_price * cs_quantity
                                    ELSE 0
                           END) AS jul_sales,
                           Sum(
                           CASE
                                    WHEN d_moy = 8 THEN cs_sales_price * cs_quantity
                                    ELSE 0
                           END) AS aug_sales,
                           Sum(
                           CASE
                                    WHEN d_moy = 9 THEN cs_sales_price * cs_quantity
                                    ELSE 0
                           END) AS sep_sales,
                           Sum(
                           CASE
                                    WHEN d_moy = 10 THEN cs_sales_price * cs_quantity
                                    ELSE 0
                           END) AS oct_sales,
                           Sum(
                           CASE
                                    WHEN d_moy = 11 THEN cs_sales_price * cs_quantity
                                    ELSE 0
                           END) AS nov_sales,
                           Sum(
                           CASE
                                    WHEN d_moy = 12 THEN cs_sales_price * cs_quantity
                                    ELSE 0
                           END) AS dec_sales,
                           Sum(
                           CASE
                                    WHEN d_moy = 1 THEN cs_net_paid_inc_tax * cs_quantity
                                    ELSE 0
                           END) AS jan_net,
                           Sum(
                           CASE
                                    WHEN d_moy = 2 THEN cs_net_paid_inc_tax * cs_quantity
                                    ELSE 0
                           END) AS feb_net,
                           Sum(
                           CASE
                                    WHEN d_moy = 3 THEN cs_net_paid_inc_tax * cs_quantity
                                    ELSE 0
                           END) AS mar_net,
                           Sum(
                           CASE
                                    WHEN d_moy = 4 THEN cs_net_paid_inc_tax * cs_quantity
                                    ELSE 0
                           END) AS apr_net,
                           Sum(
                           CASE
                                    WHEN d_moy = 5 THEN cs_net_paid_inc_tax * cs_quantity
                                    ELSE 0
                           END) AS may_net,
                           Sum(
                           CASE
                                    WHEN d_moy = 6 THEN cs_net_paid_inc_tax * cs_quantity
                                    ELSE 0
                           END) AS jun_net,
                           Sum(
                           CASE
                                    WHEN d_moy = 7 THEN cs_net_paid_inc_tax * cs_quantity
                                    ELSE 0
                           END) AS jul_net,
                           Sum(
                           CASE
                                    WHEN d_moy = 8 THEN cs_net_paid_inc_tax * cs_quantity
                                    ELSE 0
                           END) AS aug_net,
                           Sum(
                           CASE
                                    WHEN d_moy = 9 THEN cs_net_paid_inc_tax * cs_quantity
                                    ELSE 0
                           END) AS sep_net,
                           Sum(
                           CASE
                                    WHEN d_moy = 10 THEN cs_net_paid_inc_tax * cs_quantity
                                    ELSE 0
                           END) AS oct_net,
                           Sum(
                           CASE
                                    WHEN d_moy = 11 THEN cs_net_paid_inc_tax * cs_quantity
                                    ELSE 0
                           END) AS nov_net,
                           Sum(
                           CASE
                                    WHEN d_moy = 12 THEN cs_net_paid_inc_tax * cs_quantity
                                    ELSE 0
                           END) AS dec_net
                  FROM     tpcds.catalog_sales,
                           tpcds.warehouse,
                           tpcds.date_dim,
                           tpcds.time_dim,
                           tpcds.ship_mode
                  WHERE    cs_warehouse_sk = w_warehouse_sk
                  AND      cs_sold_date_sk = d_date_sk
                  AND      cs_sold_time_sk = t_time_sk
                  AND      cs_ship_mode_sk = sm_ship_mode_sk
                  AND      d_year = 2001
                  AND      t_time BETWEEN 30838 AND      30838 + 28800
                  AND      sm_carrier                         IN ('DHL',
                                                                  'BARIAN')
                  GROUP BY w_warehouse_name,
                           w_warehouse_sq_ft,
                           w_city,
                           w_county,
                           w_state,
                           w_country,
                           d_year) AS x
GROUP BY w_warehouse_name,
         w_warehouse_sq_ft,
         w_city,
         w_county,
         w_state,
         w_country,
         ship_carriers,
         year_
ORDER BY w_warehouse_name nulls first limit 100
```

**Comment by cpcloud** [comment]
> Clickhouse fails because it can't execute the raw SQL query (i.e. before we even get to the Ibis expression part):
> 
> `Code: 184. DB::Exception: Aggregate function sum(jan_sales) AS jan_sales is found inside another aggregate function in query. (ILLEGAL_AGGREGATION) (version 24.7.3.42 (official build))`

Ugh, this is because of their bizzaro "reference previous columns in the same `SELECT`" ... "feature".

In the outer select there's,

```
  ,sum(jan_sales) as jan_sales
```

follwed by

```
  sum(jan_sales/w_warehouse_sq_ft) as jan_sales_per_sq_foot
```

and because of the first alias to `jan_sales` the *second* `jan_sales` reference there expands to

```
  sum(sum(jan_sales)/w_warehouse_sq_ft) as jan_sales_per_sq_foot
```

This is one of the most annoying features ever.

**Comment by cpcloud** [comment]
I guess my point is that the problem has nothing to do with correlation, AFAICT this query doesn't contain any correlated queries.

**Comment by cpcloud** [comment]
In a follow-up we can also change the aliases to be a bit more acommodating.

**Pull request merged**
