### PR TITLE
refactor: remove dead code along with pytz dependency

### LINKED ISSUE #2552: refactor: simplify convert_datetime64_to_timestamp in pandas/dask backends
https://github.com/ibis-project/ibis/pull/2541#discussion_r533426767

We go out of our way to support object typed datetimes (https://github.com/ibis-project/ibis/pull/2541#discussion_r533426767)

### PR DESCRIPTION
**Pull request by cpcloud**
This PR removes some dead code as well as pytz, since that was the only place it was being used. Closes #2552

### CODE REVIEW

**Comment by cpcloud** [comment]
@jreback Can you review when you get a chance?

**Comment by cpcloud** [comment]
@jreback Any chance you can review this today? Would like to get it in for the release if possible.

**Review by jreback — APPROVED** [review]
lgtm

**Pull request merged**
