### PR TITLE
CI: Adding workflow to self-assign issues

### PR DESCRIPTION
**Pull request by datapythonista**
Now that hacktoberfest is approaching, and I'm also thinking on organizing a sprint to take care of many "good first issue", I think it may be useful to let people assign issues to themselves via a comment. Adding it here.

Will add docs in a follow up, the contributing page needs several updates, and I'll add about assigning issues there.

### CODE REVIEW

**Comment by jreback** [comment]
same action as in pandas right? okie dokie.

**Review by jreback — APPROVED** [review]

**Comment by datapythonista** [comment]
Same exact action, but I changed `take` for `/take`, since seems that it's more standard in GitHub Actions to start with slash commands for a bot.

**Comment by jreback** [comment]
> Same exact action, but I changed `take` for `/take`, since seems that it's more standard in GitHub Actions to start with slash commands for a bot.

oh wow! ok makes sense, prob should update the pandas one (or accept both for a while)?

**Comment by datapythonista** [comment]
> prob should update the pandas one (or accept both for a while)?

Yes, I was thinking about it. May be we can accept both for a while, but write a comment if the old version is used, to let the user know about the change. I'll have a look later.

**Pull request merged**
