### PR TITLE
refactor(ir): remove `ibis.expr.streaming`

### PR DESCRIPTION
**Pull request by kszucs**
We shouldn't introduce a new module for a single object just yet. If there will be more streaming related construct we can factor them out to a separate module.

### CODE REVIEW

**Comment by cpcloud** [comment]
cc @chloeh13q @deepyaman

**Review by jcrist — COMMENTED** [review]
We know there will be new streaming-only apis. What harm is there in keeping `Watermark` in its own submodule for now? I'm not against removing it, but it also doesn't seem useful to remove it either.

**Comment by kszucs** [comment]
No harm per se, but we used to have a similar TimeContext file containing implementation details of the pandas and dask backends slightly related to the ibis IR and it mostly provided noise and import cycles.

Watermark seems like a container to push implementation specific details down to the flink backend. 
It would be nice to see support for streaming operations in at least one additional backend before crafting a new streaming API. 

> We know there will be new streaming-only apis.
We can pull them out to appropiate files once we are there, but even then `ibis/expr/types/streaming.py` could be a mroe suitable location for that.

**Review by jcrist — APPROVED** [review]
Seems harmless.

**Pull request merged**
