### PR TITLE
DOC: Fix website CNAME and stop using a fork as a base

### PR DESCRIPTION
**Pull request by datapythonista**
https://ibis-project.org is currently broken. The problem comes from the domain change from docs.ibis-project.org to ibis-project.org. We updated the domain in the github setting of the project, but the setting is overwritten by the `CNAME` file in the repo. This file is coming from the fork https://github.com/cpcloud/docs.ibis-project.org, which is used as a base to build the website/docs. I opened https://github.com/cpcloud/docs.ibis-project.org/pull/1 for an immediate fix, but doesn't look like the fork is being maintained. And I think it's a bad practice and unnecessary to use that fork as a base.

So, in this PR I create the repo that will be pushed to GitHub pages from scratch, instead of cloning the fork. I fix the `CNAME` content, which now is in the Azure setting, and not in the fork. And I speed up things a bit, by starting the docker container of the docs just once, instead of starting it for every command.

### CODE REVIEW

**Comment by jreback** [comment]
looks good, ping no green

**Comment by datapythonista** [comment]
@jreback this is green now, but I had to do some extra changes to pass, and simplified things a bit. You'll have to have another look.

**Comment by jreback** [comment]
lgtm. let's see the docs push :->

**Comment by jreback** [comment]
hm still getting a 404 on https://ibis-project.org/ any idea?

**Comment by jreback** [comment]
hm still getting a 404 on https://ibis-project.org/ any idea?

**Comment by datapythonista** [comment]
Was just checking it. Seems like the push failed, something to do with git. Will have a look and open a PR when I figure out. The push doesn't run for PRs, so can't test much until merged.

**Pull request merged**
