### PR TITLE
fix(deps): remove the upper bounds for `pyarrow`

### LINKED ISSUE #10492: feat: please consider not setting upper bounds on dependencies
### Is your feature request related to a problem?

Ibis currently sets upper bounds on dependencies. E.g. the latest release pins `pyarrow<18`

### What is the motivation behind your request?

This causes issues in CI. For example [here](https://github.com/vega/altair/pull/3591) it was blocking upgrading to Python 3.13

### Describe the solution you'd like

I'd suggest not setting upper bounds on dependencies, as suggested here https://iscinumpy.dev/post/bound-version-constraints/

> Capping dependencies has long term negative effects, especially for libraries, and should never be taken lightly. A library is not installed in isolation; it has to live with other libraries in a shared environment. Only add a cap if a dependency is known to be incompatible or there is a high (>75%) chance of it being incompatible in its next release. Do not cap by default - capping dependencies makes your software incompatible with other libraries that also have strict lower limits on dependencies, and limits future fixes. 

### What version of ibis are you running?

9.5.0

### What backend(s) are you using, if any?

Polars

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by deepyaman**
## Issues closed

* Resolves #10492

### CODE REVIEW

**Comment by gforsyth** [comment]
I'm in favor of this.  I think we should remove more than just the `pyarrow` upper pin, but I'll also let @cpcloud weigh in here.

**Comment by cpcloud** [comment]
Seems like it's probably fine to remove upper bounds on some of these, pyarrow is probably the most important one, and we do the others in follow-ups as folks have time.

**Comment by cpcloud** [comment]
@deepyaman Can you update the PR and resolve the conflicts?

**Review by cpcloud — APPROVED** [review]

**Comment by cpcloud** [comment]
Made it a `fix` PR so that it'll show up in the release notes.

**Pull request merged**
