### PR TITLE
feat: add easy type hints to GroupBy

### PR DESCRIPTION
**Pull request by NickCrews**
I just wrote this in the GitHub web UI so no idea if this will pass mypy

### CODE REVIEW

**Comment by NickCrews** [comment]
pre-commit.ci autofix

**Comment by NickCrews** [comment]
Wow, that's the first time I've use the pre-commit bot, that is awesome!

**Comment by NickCrews** [comment]
Oh, does Ibis not actually do any type checking? I don't see any mypy config anywhere...

**Review by cpcloud — APPROVED** [review]
We don't run any mypy checks, but this is still helpful for autocompletion!

**Pull request merged**
