### PR TITLE
BUG: fix datamgr.py fail if IBIS_TEST_OMNISCIDB_DATABASE=omnisci

### LINKED ISSUE #2049: datamgr.py fails if IBIS_TEST_OMNISCIDB_DATABASE=omnisci
If I try to use default omniscidb database name `omnisci`, then variable database doesn't get initialized in line 377 and I get an exception like this:

```
Traceback (most recent call last):
  File "./datamgr.py", line 623, in <module>
    cli(auto_envvar_prefix='IBIS_TEST')
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "./datamgr.py", line 377, in omniscidb
    dbname=database,
UnboundLocalError: local variable 'database' referenced before assignment
```

Suggested fix is to initialize `database` variable:
```
diff --git a/ci/datamgr.py b/ci/datamgr.py
index f36705a..b0c7eda 100755
--- a/ci/datamgr.py
+++ b/ci/datamgr.py
@@ -368,6 +368,8 @@ def omniscidb(schema, tables, data_directory, **params):
         except Exception:
             logger.exception('OmniSci DDL statement %r failed', stmt)
         conn.close()
+    else:
+        database = default_db

     conn = pymapd.connect(
         host=params['host'],
```

### PR DESCRIPTION
**Pull request by anmyachev**
closes #2049

### CODE REVIEW

**Comment by anmyachev** [comment]
@xmnlab the PR ready for review

**Comment by xmnlab** [comment]
@anmyachev could you add a release note for that pls?  thanks!

**Comment by anmyachev** [comment]
@xmnlab release note was be added. Thanks for review!

**Comment by xmnlab** [comment]
Thanks @anmyachev !

**Pull request merged**
