### PR TITLE
fix(bigquery): truncate when casting float to int

### PR DESCRIPTION
**Pull request by sudonhim**
BREAKING CHANGE: when using the bigquery backend, floats will be truncated instead of rounded to the nearest integer

### CODE REVIEW

**Comment by cpcloud** [comment]
Does this PR supersede #6110? If so, can you close #6110? Thanks!

**Comment by sudonhim** [comment]
@cpcloud Done! GitHub newbie here, I didn't realize draft PRs were public :)

**Comment by cpcloud** [comment]
@sudonhim No worries, happy to help!

Are you able to test this against BigQuery?

We have testing set up to run against `master`, but we aren't currently able to test it locally (which will be possible soon, but unclear exactly when).

**Comment by cpcloud** [comment]
Impala failures are unrelated.

> I'm assuming that matching Python (like Pandas does) is correct here, hence this change.

Yep!

@tswast Mind having a look at this?

**Review by tswast — APPROVED** [review]
Thanks so much!

**Pull request merged**
