### PR TITLE
[WIP] feat: add dask windows

### PR DESCRIPTION
**Pull request by gerrymanoim**
Previously dask supported "noop" windows. This PR adds some limited window functionality. Draft to see how far I can reasonably get while keeping this a reasonable size. 

Notes:
- dask only supports single value sorts, so any window with grouping and sorting is not supported
- I'm trying to keep the structure quite close the pandas backend, which will make some eventual consolidation and refactoring much easier to do. However, the pandas windowing code definitely needs some broad refactoring so things look a bit messy.

### CODE REVIEW

**Comment by cpcloud** [comment]
@gerrymanoim We're planning on a 3.2.0 release around the beginning of September. Do you think you'll be able to finish this up by then?

**Comment by cpcloud** [comment]
@gerrymanoim Are you still working on this?

**Comment by gerrymanoim** [comment]
Hey - apologies I missed your first message. 

Yes - this is still on our list of things we want to do - I don't have an ETA unfortunately for when I'll next carve out time to work on this. You can close this if you'd like.

**Comment by cpcloud** [comment]
Closing. Please reopen if you get a chance to work on it later!

**Pull request closed without merging**
