### PR TITLE
docs: fix sample code

### PR DESCRIPTION
**Pull request by eitsupi**
Looks like an old code that was not updated in #2440.

### CODE REVIEW

**Comment by cpcloud** [comment]
As soon as GitHub Actions shenanigans resolves, I'll merge this.

**Review by cpcloud — APPROVED** [review]
Thanks!

**Comment by jreback** [comment]
@cpcloud i guess we don't fail the doc build
on failures?

**Comment by cpcloud** [comment]
@jreback The docs build didn't fail https://github.com/ibis-project/ibis/runs/4642894218?check_suite_focus=true

**Comment by cpcloud** [comment]
If you're referring to whether the doc build executes no matter what, then yes it does.

**Comment by jreback** [comment]
oh would be nice
to have it fail
on errors
and warnings
if possible

**Pull request merged**
