### PR TITLE
feat(chdb): simple prototype of an embedded clickhouse backend

### PR DESCRIPTION
**Pull request by kszucs**
A really basic but functional backend implementation prototype for `chDB` which is an embedded distribution of `clickhouse-local`. The [chDB project](https://github.com/chdb-io/chdb) seems to be in-progress, but could be a good material to start with.

I put up the PR mostly for discussion purposes.

### CODE REVIEW

**Comment by lostmygithubaccount** [comment]
I like it a lot conceptually. Can you add a small writeup somewhere on how someone could play around with this?

**Comment by cpcloud** [comment]
I like this!

@lostmygithubaccount It looks like this is missing some basics that will prevent playing around with it (the `table` method of the backend is not implemented, and you can't do much without that). I suspect a bit of work is needed to get this into a playable state.

**Comment by cpcloud** [comment]
Having more options for fast local analytics backends, especially if there's a backend that can actually go from dev to prod with no rewrites because it's the same backend just deployed differently, is a good thing IMO.

**Comment by lostmygithubaccount** [comment]
> Having more options for fast local analytics backends, especially if there's a backend that can actually go from dev to prod with no rewrites because it's the same backend just deployed differently, is a good thing IMO.

agreed -- between DuckDB/MotherDuck, Polars/Polars Company, and Clickhouse here hopefully we have a great experience in this direction soon!

**Comment by cpcloud** [comment]
Closing this out for now! Love the idea, but this would need to be a bit more fleshed out.

@seandavi Is a local clickhouse backend something you'd be interested in?

**Pull request closed without merging**
