### PR TITLE
refactor: remove deprecated functions and classes

### PR DESCRIPTION
**Pull request by kszucs**
BREAKING CHANGE: functions, methods and classes marked as deprecated are removed now

### CODE REVIEW

**Comment by kszucs** [comment]
This feels pretty satisfying :)

@cpcloud I'm thinking about maintaining a 4.0 branch which we can periodically rebase on top of the master branch. That would allow us to moving forward with breaking changes.

**Comment by jreback** [comment]
let's hold off on this for a bit

**Comment by kszucs** [comment]
> let's hold off on this for a bit

It's not supposed to merged before the 3.1 release, unless we merge it to a 4.0 development branch.

**Comment by kszucs** [comment]
@cpcloud I just created a `4.x.x` branch for the next major release and updated this PR to be merged there.

**Review by kszucs — COMMENTED** [review]
+1, merging on green

**Pull request merged**
