### PR TITLE
Remove experimental mentions for OmniSciDB and Pandas backends

### PR DESCRIPTION
**Pull request by xmnlab**

### CODE REVIEW

**Comment by jreback** [comment]
are we on released versions of omnisci deps? (and images)?

**Comment by jreback** [comment]
also can remove the experimental label from pandas i think

**Comment by xmnlab** [comment]
good point. I will open a PR to use the last stable OmniSci image.

about pandas, sounds good. I will remove its experimental label too.

**Comment by jreback** [comment]
lgtm

**Comment by jreback** [comment]
thanks

**Pull request merged**
