### PR TITLE
SUPP: Rename mapd to omniscidb backend

### PR DESCRIPTION
**Pull request by xmnlab**
depends on #1860

In this PR
- Rename mapd backend to omniscidb

### CODE REVIEW

**Comment by xmnlab** [comment]
cc @niviksha

**Comment by xmnlab** [comment]
@cpcloud it is done for a review :) thanks!

**Comment by xmnlab** [comment]
conflicts fixed. it is ready again for review.

**Comment by cpcloud** [comment]
@xmnlab I think that because this is a wholesale rename we should bump ibis to `2.0.0`, thoughts?

**Comment by xmnlab** [comment]
@cpcloud  thanks for the review! yes, you're right `2.0.0` sounds great!

**Pull request merged**
