### PR TITLE
Make backend registries standard and clearer

### PR DESCRIPTION
**Pull request by datapythonista**
Backends so far have a not very clear and not standard way to define their operations registries. In some cases it's defined in the `compliler.py` file, and in some others in `operations.py`. When using `operations.py`, the visibility of the objects in the file doesn't seem to make much change. There are many public functions that shouldn't be, as aren't used outside the file. And the `_operation_registry` object, which is the only public object used elsewhere, is marked as private.

In this PR I standardize backends to use `registry.py`, with a single public object `operation_registry`.

Starting by Clickhouse, if it works as expected, I'll continue with the rest.

### CODE REVIEW

**Comment by jreback** [comment]
ok this looks fine. Can you add a test to asssert that the namespaces are clean at this point? (or may have to wait on that)?

**Comment by jreback** [comment]
cc @icexelloss if comments

**Comment by datapythonista** [comment]
> ok this looks fine. Can you add a test to asssert that the namespaces are clean at this point? (or may have to wait on that)?

Probably better to wait. I'm planning to still iterate further, I think we can remove several things from the public API of the base backend. When it starts to looks final I also want to document what's there, add docstrings and add the objects to a page in the docs. Probably better to test the namespace at that point.

**Comment by jreback** [comment]
> > ok this looks fine. Can you add a test to asssert that the namespaces are clean at this point? (or may have to wait on that)?
> 
> Probably better to wait. I'm planning to still iterate further, I think we can remove several things from the public API of the base backend. When it starts to looks final I also want to document what's there, add docstrings and add the objects to a page in the docs. Probably better to test the namespace at that point.

sounds good

**Comment by datapythonista** [comment]
@icexelloss when you've got time, mind having a look at this, and #2727 please? I'm blocked by these two PRs to continue the clean up of the backend API, and should be quite fast to have a look at them. Thanks!

**Comment by datapythonista** [comment]
@jreback do you think we can move forward with this? This is blocking me from continuing with the refactoring. Happy to take care of any further feedback as a follow up.

**Comment by icexelloss** [comment]
@datapythonista Sorry for the delay. Looks good to me.

**Review by jreback — APPROVED** [review]
thanks @datapythonista

**Pull request merged**
