### PR TITLE
Missing geospatial ops for OmniSciDB

### PR DESCRIPTION
**Pull request by ian-r-rose**
This adds a few geospatial ops to the omniscidb backend (probably added since the last time there was a pass through geospatial ops).
* ST_DWithin
* ST_Intersects
* ST_Disjoint

### CODE REVIEW

**Comment by xmnlab** [comment]
hey @ian-r-rose it seems lint check is failing
have you executed `make develop`? that is pretty helpful because it add back, flake8 and isort as git pre-commit hook

**Comment by ian-r-rose** [comment]
That flake8 failure is not a line I touched :/

I have run `make develop`, but it's currently broken in my env.

**Comment by xmnlab** [comment]
is it raising any error message? or it just doesn't work?

**Comment by ian-r-rose** [comment]
Flake8 failing with `ValueError: failed to parse CPython sys.version: '3.7.3 (default, Mar 27 2019, 22:11:17) \n[GCC 7.3.0]'`. Not sure where the problem is, but I was willing to chalk it up to a broken environment :)

**Pull request merged**
