### PR TITLE
chore: gate pyarrow imports in DuckDB backend

### PR DESCRIPTION
**Pull request by gforsyth**
I don't think pyarrow is a strict dependency of DuckDB and we have the machinery to make it friendlier.

### CODE REVIEW

**Comment by jcrist** [comment]
This makes sense to me. I think we'll also want to remove `pyarrow` from the duckdb extra here (https://github.com/ibis-project/ibis/blob/45156f5ba03d8ff69e8a002364a44b15d4302bc7/pyproject.toml#L131).

**Comment by cpcloud** [comment]
I don't think we should remove the extra, otherwise when you run `pip install ibis-framework[duckdb]` you get an install that doesn't have enough for all the public duckdb backend APIs to work.

**Comment by cpcloud** [comment]
Is the idea to fail at runtime when someone tries to run `to_pyarrow()`?

**Comment by cpcloud** [comment]
Hm, maybe it's not a big deal to remove it. How are we going to test the `to_pyarrow()` functionality in CI for the duckdb backend?

**Comment by cpcloud** [comment]
Ah, we have `pyarrow` as a test dependency for other reasons, so this should "just work".

**Comment by gforsyth** [comment]
I forgot about the custom record batch reader and I'm not sure this is worth it anymore.  I was mostly trying to fix an annoying dependency issue with ibis-substrait, but I can handle it over there instead.

**Pull request closed without merging**
