### PR TITLE
docs(build): cache notebooks during render

### PR DESCRIPTION
**Pull request by cpcloud**
This PR enables notebook caching via jupyter-cache. Locally I observed between 2-3x faster rendering. Happy to not merge this if people do not think it is enough of an improvement.

### CODE REVIEW

**Comment by cpcloud** [comment]
Oh, I think we just updated the same thing in the same place.

**Comment by cpcloud** [comment]
@lostmygithubaccount if you approve, we can merge

**Review by lostmygithubaccount — APPROVED** [review]
thanks!

**Review by gforsyth — APPROVED** [review]
>2x speedup locally

SHIPIT

**Pull request merged**
