### PR TITLE
fix(snowflake): use `convert_timezone` for timezone conversion instead of invalid postgres `AT TIME ZONE` syntax

### PR DESCRIPTION
**Pull request by cpcloud**
Partially addresses #6292 by using the correct syntax for timezone conversion.

### CODE REVIEW

**Comment by cpcloud** [comment]
Snowflake looks good:

```
cloud in 🌐 falcon in …/ibis on  fix-snowflake-timezone-conversion is 📦 v5.1.0 via 🐍 v3.10.11 via ❄️  impure (ibis-3.10.11-env)
❯ pytest -m snowflake -n auto --dist loadgroup --snapshot-update -q
bringing up nodes...
...........x.x....x......x...............xxx.x.....xxx..x.x....x..x....x.xxxxxx....xx...x.xxx.xx.x.x.....x.... [ 11%]
.x........x....xx.............x........x.x......................................x.....x....x.................. [ 23%]
x..x..............x....x........x.....x..x..........x..x...x...x..xx....x...x...xxx.......x........xx..x...... [ 35%]
......x....xx.x..x.xx.xx..x..x.x...x.....x....x.....x.....................x.....xx............................ [ 47%]
x...........................xx.x......x..x...xx.x.xxx........x..x..xxx.x...x.xxx...x...xxx...x...x.....x..xx.. [ 59%]
.....x.......x...x...x......xx....................x....x.......x.............xx.....s......................... [ 71%]
....sx...s.x...................................x.......................................x...s.................. [ 83%]
.x....x....x........s......x..................................x...........xs..s.........x................xx... [ 95%]
..........x.................................                                                                   [100%]
777 passed, 7 skipped, 140 xfailed in 215.76s (0:03:35)
```

**Review by gforsyth — APPROVED** [review]
:shipit:

**Comment by pzarabadip** [comment]
Hi @cpcloud We need this fix in our downstream packages. Is there any chance that you may publish a release with changes ported via this PR?
Currently, we need to point to the head of main which makes dependency management a bit tedious. 
Cheers

**Comment by cpcloud** [comment]
@pzarabadip Hi there 👋🏻 

> Is there any chance that you may publish a release with changes ported via this PR?

We plan to publish a release at the end of June, so if it's not a huge amount of trouble to wait two weeks then you can upgrade to 6.0 then.

Is waiting a couple weeks acceptable?

> Currently, we need to point to the head of main which makes dependency management a bit tedious.

On the plus side it sounds like the upgrade to 6.0 will be relatively painless if you're tracking upstream!

**Comment by cpcloud** [comment]
@pzarabadip Would a pre-release work for you? I think we could probably cut that pretty easily.

Once that's available then since you're managing dependencies with poetry then adding the `allow-prereleases` flag should get you what you want:

```toml
ibis-framework = { version = ..., allow-prereleases = true }
```

**Comment by cpcloud** [comment]
@pzarabadip We've got a pre-release up!

https://pypi.org/project/ibis-framework/5.1.1.dev467/

Going forward we'll also have pre-releases published off of `master` every Sunday to PyPI.

**Comment by pzarabadip** [comment]
Thanks very much @cpcloud. It works nicely in our side. Cheers

**Pull request merged**
