### PR TITLE
chore: backport a few fixes and one feature to `6.x.x`

### PR DESCRIPTION
**Pull request by cpcloud**
This PR backports a few fixes to the `6.x.x` branch from `master`, and sets up the ability to release from the `6.x.x` branch.

Backporting was requested by @tswast (for BigQuery DataFrames), and also by some folks from the trino side so they can measure ibis + trino usage.

After this PR is merged, I'll cut a 6.2 release using the `release.yml` workflow run from the 6.x.x branch. This PR includes a change to `.releaserc.js` that allow `semantic-release` to run from the 6.x.x branch, which should be enough to allow it to successfully cut a release.

### CODE REVIEW

**Comment by cpcloud** [comment]
Backporting was requested by @tswast (for BigQuery DataFrames), and also by some folks from the trino side so they can measure ibis + trino usage.

**Comment by cpcloud** [comment]
BigQuery tests are passing:

```
…/ibis on  backport-setup-6.x.x is 📦 v6.1.0 via 🐍 v3.10.12 via ❄️  impure (ibis-3.10.12-env) took 1m10s
❯ pytest -m bigquery -n auto --dist loadgroup --snapshot-update -q
bringing up nodes...
.........................xx.................x.x............x....x..x.......................xxxx.xxxxxxxxxxxx..xx....x..x.............................x............................................... [ 13%]
...........................x...................................xx.xxx.xxx.x..xx..xx.xxxxx..xx...x...xx.x.x..x.......x.x....x...........x.....x.x....x.....xx.x....x....x......xx.............x....... [ 27%]
x.........................x..............................xxx.x............x...x......x..x...........x..............x.x..x...xx......xx..x...xx............xxxx....x......x..x.x..xx..xx..xx...x..xxx. [ 41%]
...x..xx..............x..x..x.......x..x...........x.x.x...x........xx...xxx...........xxx...x......x.......x....x...x..x.x...x.xxx.xxx...x..x.s..........x...xxssss...xx.x.xx.x.xx.s........x..x..... [ 55%]
xx...x........x..x.................................x...............x..........x................................x.x.......x.x....x....x..............x...xxxxx....x.xxx.x.xx.x.x..x...xs.x........x... [ 68%]
....x.........x........................................................................................................x....x...............................................................x........ [ 82%]
....................................x...........x..................................................................xx..xx......x....x.x..xxx......s........xxxx.x..............x.............xx.x.x.. [ 96%]
.x..x.xx.x.x.......x.x.x.......xxxxxxxxxxxxxxxx..                                                                                                                                                     [100%]
1178 passed, 8 skipped, 243 xfailed in 204.60s (0:03:24)
```

Snowflake tests are passing:

```
…/ibis on  backport-setup-6.x.x is 📦 v6.1.0 via 🐍 v3.10.12 via ❄️  impure (ibis-3.10.12-env)
❯ pytest -m snowflake -n auto --dist loadgroup --snapshot-update -q
bringing up nodes...
...........................................................................................x.....x......x......x................x.x.........................................x.x........x........x.... [ 16%]
......x..x.........x........................x.x..............x....x.x.....xx...........x.x........x.....x.xx.x.......x.....x....x..x.x...xx.xx..x...........x...s....x...........x..x.............x.. [ 33%]
.x..x....x.x................xx..xxxx......x..xxxx......x.......x..x............x.x..............x.........x..........x............................................................x.................. [ 50%]
.....s..........x............xxx.....x.xxx......x....xxx.......x.x..x...xx..xxxxxxxxxxxxxsss.x.x.s...x.....xx........x......x.......x....x..x..x..............xx..................................... [ 67%]
...........x....x...............x.......x..x....................x....x.....xx.x.....x.....x....x..........x..............s...s...x..........x..x....s...xx...xx.x........x.........x......x...x...x.. [ 84%]
.......x.....s...x.x.......................................x................................................................xx.......x...xxxx.x.x..xxx..x.xx.x.xxx...xxxx..xxxxxxx                    [100%]
983 passed, 10 skipped, 170 xfailed in 360.57s (0:06:00)
```

**Comment by cpcloud** [comment]
For transparency here is the output of running

```
ci/release/dry_run.sh
```

image

**Comment by tswast** [comment]
Thanks so much!

**Pull request merged**
